# COMMENTS:
#
# Images are named like this:
# chara Clothes Expression Fade Flip
# Add Fade/Flip when needed
#
# Choromatsu has the following clothes:
# SchoolS SchoolW Bathrobe Bathtowel MainPark Naked Pj Sera
#
# Choromatsu has the following expressions:
# Neutral Angry Blank Dark Displeased1 Displeased2 Happy1 Happy2 Nervous Shocked Surprise Thinking
#
# Adding New Images:
# Use the same naming convention, copy paste the right code per commented section.
# The numbers are for head animation, for expressions such as dark, leave it as "" if it has no number behind.
# Remember every image needs normal, flip, fade, flip fade.
# Every new outfit also needs all the expressions (just in case)

#Choromatsu Images
image choro Bathrobe Angry1 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","01","02","bathrobe","",0,"","false",800,950))
image choro Bathrobe Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","01","02","bathrobe","",0,"","true",800,950))
image choro Bathrobe Angry1 Flip= Transform("choro Bathrobe Angry1",xzoom=-1.0)
image choro Bathrobe Angry1 Fade Flip= Transform("choro Bathrobe Angry1 Fade",xzoom=-1.0)
image choro Bathrobe Angry2 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","03","04","bathrobe","",0,"","false",800,950))
image choro Bathrobe Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","03","04","bathrobe","",0,"","true",800,950))
image choro Bathrobe Angry2 Flip= Transform("choro Bathrobe Angry2",xzoom=-1.0)
image choro Bathrobe Angry2 Fade Flip= Transform("choro Bathrobe Angry2 Fade",xzoom=-1.0)
image choro Bathrobe Angry3 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","05","06","bathrobe","",0,"","false",800,950))
image choro Bathrobe Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","05","06","bathrobe","",0,"","true",800,950))
image choro Bathrobe Angry3 Flip= Transform("choro Bathrobe Angry3",xzoom=-1.0)
image choro Bathrobe Angry3 Fade Flip= Transform("choro Bathrobe Angry3 Fade",xzoom=-1.0)
image choro Bathrobe Dark = DynamicDisplayable(renpy.curry(charComposite)("choro","dark","","","bathrobe","",0,"","false",800,950))
image choro Bathrobe Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","dark","","","bathrobe","",0,"","true",800,950))
image choro Bathrobe Dark Flip= Transform("choro Bathrobe Dark",xzoom=-1.0)
image choro Bathrobe Dark Fade Flip= Transform("choro Bathrobe Dark Fade",xzoom=-1.0)
image choro Bathrobe Blank = DynamicDisplayable(renpy.curry(charComposite)("choro","blank","01","02","bathrobe","",0,"","false",800,950))
image choro Bathrobe Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","blank","01","02","bathrobe","",0,"","true",800,950))
image choro Bathrobe Blank Flip= Transform("choro Bathrobe Blank",xzoom=-1.0)
image choro Bathrobe Blank Fade Flip= Transform("choro Bathrobe Blank Fade",xzoom=-1.0)
image choro Bathrobe Displeased1 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","01","02","bathrobe","",0,"","false",800,950))
image choro Bathrobe Displeased1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","01","02","bathrobe","",0,"","true",800,950))
image choro Bathrobe Displeased1 Flip= Transform("choro Bathrobe Displeased1",xzoom=-1.0)
image choro Bathrobe Displeased1 Fade Flip= Transform("choro Bathrobe Displeased1 Fade",xzoom=-1.0)
image choro Bathrobe Displeased2 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","03","04","bathrobe","",0,"","false",800,950))
image choro Bathrobe Displeased2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","03","04","bathrobe","",0,"","true",800,950))
image choro Bathrobe Displeased2 Flip= Transform("choro Bathrobe Displeased2",xzoom=-1.0)
image choro Bathrobe Displeased2 Fade Flip= Transform("choro Bathrobe Displeased2 Fade",xzoom=-1.0)
image choro Bathrobe Displeased3 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","05","06","bathrobe","",0,"","false",800,950))
image choro Bathrobe Displeased3 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","05","06","bathrobe","",0,"","true",800,950))
image choro Bathrobe Displeased3 Flip= Transform("choro Bathrobe Displeased3",xzoom=-1.0)
image choro Bathrobe Displeased3 Fade Flip= Transform("choro Bathrobe Displeased3 Fade",xzoom=-1.0)
image choro Bathrobe Happy1 = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","01","02","bathrobe","",0,"","false",800,950))
image choro Bathrobe Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","01","02","bathrobe","",0,"","true",800,950))
image choro Bathrobe Happy1 Flip= Transform("choro Bathrobe Happy1",xzoom=-1.0)
image choro Bathrobe Happy1 Fade Flip= Transform("choro Bathrobe Happy1 Fade",xzoom=-1.0)
image choro Bathrobe Happy2 = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","03","04","bathrobe","",0,"","false",800,950))
image choro Bathrobe Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","03","04","bathrobe","",0,"","true",800,950))
image choro Bathrobe Happy2 Flip= Transform("choro Bathrobe Happy2",xzoom=-1.0)
image choro Bathrobe Happy2 Fade Flip= Transform("choro Bathrobe Happy2 Fade",xzoom=-1.0)
image choro Bathrobe Nervous = DynamicDisplayable(renpy.curry(charComposite)("choro","nervous","01","02","bathrobe","",0,"","false",800,950))
image choro Bathrobe Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","nervous","01","02","bathrobe","",0,"","true",800,950))
image choro Bathrobe Nervous Flip= Transform("choro Bathrobe Nervous",xzoom=-1.0)
image choro Bathrobe Nervous Fade Flip= Transform("choro Bathrobe Nervous Fade",xzoom=-1.0)
image choro Bathrobe Neutral = DynamicDisplayable(renpy.curry(charComposite)("choro","neutral","01","02","bathrobe","",0,"","false",800,950))
image choro Bathrobe Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","neutral","01","02","bathrobe","",0,"","true",800,950))
image choro Bathrobe Neutral Flip= Transform("choro Bathrobe Neutral",xzoom=-1.0)
image choro Bathrobe Neutral Fade Flip= Transform("choro Bathrobe Neutral Fade",xzoom=-1.0)
image choro Bathrobe Shocked = DynamicDisplayable(renpy.curry(charComposite)("choro","shocked","01","02","bathrobe","",0,"","false",800,950))
image choro Bathrobe Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","shocked","01","02","bathrobe","",0,"","true",800,950))
image choro Bathrobe Shocked Flip= Transform("choro Bathrobe Shocked",xzoom=-1.0)
image choro Bathrobe Shocked Fade Flip= Transform("choro Bathrobe Shocked Fade",xzoom=-1.0)
image choro Bathrobe Surprised = DynamicDisplayable(renpy.curry(charComposite)("choro","surprised","01","02","bathrobe","",0,"","false",800,950))
image choro Bathrobe Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","surprised","01","02","bathrobe","",0,"","true",800,950))
image choro Bathrobe Surprised Flip= Transform("choro Bathrobe Surprised",xzoom=-1.0)
image choro Bathrobe Surprised Fade Flip= Transform("choro Bathrobe Surprised Fade",xzoom=-1.0)
image choro Bathrobe Thinking = DynamicDisplayable(renpy.curry(charComposite)("choro","thinking","01","02","bathrobe","",0,"","false",800,950))
image choro Bathrobe Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","thinking","01","02","bathrobe","",0,"","true",800,950))
image choro Bathrobe Thinking Flip= Transform("choro Bathrobe Thinking",xzoom=-1.0)
image choro Bathrobe Thinking Fade Flip= Transform("choro Bathrobe Thinking Fade",xzoom=-1.0)
image choro Casual Angry1 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","01","02","casual","",0,"","false",800,950))
image choro Casual Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","01","02","casual","",0,"","true",800,950))
image choro Casual Angry1 Flip= Transform("choro Casual Angry1",xzoom=-1.0)
image choro Casual Angry1 Fade Flip= Transform("choro Casual Angry1 Fade",xzoom=-1.0)
image choro Casual Angry2 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","03","04","casual","",0,"","false",800,950))
image choro Casual Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","03","04","casual","",0,"","true",800,950))
image choro Casual Angry2 Flip= Transform("choro Casual Angry2",xzoom=-1.0)
image choro Casual Angry2 Fade Flip= Transform("choro Casual Angry2 Fade",xzoom=-1.0)
image choro Casual Angry3 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","05","06","casual","",0,"","false",800,950))
image choro Casual Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","05","06","casual","",0,"","true",800,950))
image choro Casual Angry3 Flip= Transform("choro Casual Angry3",xzoom=-1.0)
image choro Casual Angry3 Fade Flip= Transform("choro Casual Angry3 Fade",xzoom=-1.0)
image choro Casual Dark = DynamicDisplayable(renpy.curry(charComposite)("choro","dark","","","casual","",0,"","false",800,950))
image choro Casual Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","dark","","","casual","",0,"","true",800,950))
image choro Casual Dark Flip= Transform("choro Casual Dark",xzoom=-1.0)
image choro Casual Dark Fade Flip= Transform("choro Casual Dark Fade",xzoom=-1.0)
image choro Casual Blank = DynamicDisplayable(renpy.curry(charComposite)("choro","blank","01","02","casual","",0,"","false",800,950))
image choro Casual Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","blank","01","02","casual","",0,"","true",800,950))
image choro Casual Blank Flip= Transform("choro Casual Blank",xzoom=-1.0)
image choro Casual Blank Fade Flip= Transform("choro Casual Blank Fade",xzoom=-1.0)
image choro Casual Displeased1 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","01","02","casual","",0,"","false",800,950))
image choro Casual Displeased1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","01","02","casual","",0,"","true",800,950))
image choro Casual Displeased1 Flip= Transform("choro Casual Displeased1",xzoom=-1.0)
image choro Casual Displeased1 Fade Flip= Transform("choro Casual Displeased1 Fade",xzoom=-1.0)
image choro Casual Displeased2 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","03","04","casual","",0,"","false",800,950))
image choro Casual Displeased2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","03","04","casual","",0,"","true",800,950))
image choro Casual Displeased2 Flip= Transform("choro Casual Displeased2",xzoom=-1.0)
image choro Casual Displeased2 Fade Flip= Transform("choro Casual Displeased2 Fade",xzoom=-1.0)
image choro Casual Displeased3 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","05","06","casual","",0,"","false",800,950))
image choro Casual Displeased3 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","05","06","casual","",0,"","true",800,950))
image choro Casual Displeased3 Flip= Transform("choro Casual Displeased3",xzoom=-1.0)
image choro Casual Displeased3 Fade Flip= Transform("choro Casual Displeased3 Fade",xzoom=-1.0)
image choro Casual Happy1 = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","01","02","casual","",0,"","false",800,950))
image choro Casual Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","01","02","casual","",0,"","true",800,950))
image choro Casual Happy1 Flip= Transform("choro Casual Happy1",xzoom=-1.0)
image choro Casual Happy1 Fade Flip= Transform("choro Casual Happy1 Fade",xzoom=-1.0)
image choro Casual Happy2 = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","03","04","casual","",0,"","false",800,950))
image choro Casual Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","03","04","casual","",0,"","true",800,950))
image choro Casual Happy2 Flip= Transform("choro Casual Happy2",xzoom=-1.0)
image choro Casual Happy2 Fade Flip= Transform("choro Casual Happy2 Fade",xzoom=-1.0)
image choro Casual Nervous = DynamicDisplayable(renpy.curry(charComposite)("choro","nervous","01","02","casual","",0,"","false",800,950))
image choro Casual Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","nervous","01","02","casual","",0,"","true",800,950))
image choro Casual Nervous Flip= Transform("choro Casual Nervous",xzoom=-1.0)
image choro Casual Nervous Fade Flip= Transform("choro Casual Nervous Fade",xzoom=-1.0)
image choro Casual Neutral = DynamicDisplayable(renpy.curry(charComposite)("choro","neutral","01","02","casual","",0,"","false",800,950))
image choro Casual Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","neutral","01","02","casual","",0,"","true",800,950))
image choro Casual Neutral Flip= Transform("choro Casual Neutral",xzoom=-1.0)
image choro Casual Neutral Fade Flip= Transform("choro Casual Neutral Fade",xzoom=-1.0)
image choro Casual Shocked = DynamicDisplayable(renpy.curry(charComposite)("choro","shocked","01","02","casual","",0,"","false",800,950))
image choro Casual Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","shocked","01","02","casual","",0,"","true",800,950))
image choro Casual Shocked Flip= Transform("choro Casual Shocked",xzoom=-1.0)
image choro Casual Shocked Fade Flip= Transform("choro Casual Shocked Fade",xzoom=-1.0)
image choro Casual Surprised = DynamicDisplayable(renpy.curry(charComposite)("choro","surprised","01","02","casual","",0,"","false",800,950))
image choro Casual Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","surprised","01","02","casual","",0,"","true",800,950))
image choro Casual Surprised Flip= Transform("choro Casual Surprised",xzoom=-1.0)
image choro Casual Surprised Fade Flip= Transform("choro Casual Surprised Fade",xzoom=-1.0)
image choro Casual Thinking = DynamicDisplayable(renpy.curry(charComposite)("choro","thinking","01","02","casual","",0,"","false",800,950))
image choro Casual Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","thinking","01","02","casual","",0,"","true",800,950))
image choro Casual Thinking Flip= Transform("choro Casual Thinking",xzoom=-1.0)
image choro Casual Thinking Fade Flip= Transform("choro Casual Thinking Fade",xzoom=-1.0)
image choro Mainpark Angry1 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","01","02","mainpark","",0,"","false",800,950))
image choro Mainpark Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","01","02","mainpark","",0,"","true",800,950))
image choro Mainpark Angry1 Flip= Transform("choro Mainpark Angry1",xzoom=-1.0)
image choro Mainpark Angry1 Fade Flip= Transform("choro Mainpark Angry1 Fade",xzoom=-1.0)
image choro Mainpark Angry2 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","03","04","mainpark","",0,"","false",800,950))
image choro Mainpark Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","03","04","mainpark","",0,"","true",800,950))
image choro Mainpark Angry2 Flip= Transform("choro Mainpark Angry2",xzoom=-1.0)
image choro Mainpark Angry2 Fade Flip= Transform("choro Mainpark Angry2 Fade",xzoom=-1.0)
image choro Mainpark Angry3 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","05","06","mainpark","",0,"","false",800,950))
image choro Mainpark Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","05","06","mainpark","",0,"","true",800,950))
image choro Mainpark Angry3 Flip= Transform("choro Mainpark Angry3",xzoom=-1.0)
image choro Mainpark Angry3 Fade Flip= Transform("choro Mainpark Angry3 Fade",xzoom=-1.0)
image choro Mainpark Dark = DynamicDisplayable(renpy.curry(charComposite)("choro","dark","","","mainpark","",0,"","false",800,950))
image choro Mainpark Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","dark","","","mainpark","",0,"","true",800,950))
image choro Mainpark Dark Flip= Transform("choro Mainpark Dark",xzoom=-1.0)
image choro Mainpark Dark Fade Flip= Transform("choro Mainpark Dark Fade",xzoom=-1.0)
image choro Mainpark Blank = DynamicDisplayable(renpy.curry(charComposite)("choro","blank","01","02","mainpark","",0,"","false",800,950))
image choro Mainpark Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","blank","01","02","mainpark","",0,"","true",800,950))
image choro Mainpark Blank Flip= Transform("choro Mainpark Blank",xzoom=-1.0)
image choro Mainpark Blank Fade Flip= Transform("choro Mainpark Blank Fade",xzoom=-1.0)
image choro Mainpark Displeased1 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","01","02","mainpark","",0,"","false",800,950))
image choro Mainpark Displeased1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","01","02","mainpark","",0,"","true",800,950))
image choro Mainpark Displeased1 Flip= Transform("choro Mainpark Displeased1",xzoom=-1.0)
image choro Mainpark Displeased1 Fade Flip= Transform("choro Mainpark Displeased1 Fade",xzoom=-1.0)
image choro Mainpark Displeased2 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","03","04","mainpark","",0,"","false",800,950))
image choro Mainpark Displeased2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","03","04","mainpark","",0,"","true",800,950))
image choro Mainpark Displeased2 Flip= Transform("choro Mainpark Displeased2",xzoom=-1.0)
image choro Mainpark Displeased2 Fade Flip= Transform("choro Mainpark Displeased2 Fade",xzoom=-1.0)
image choro Mainpark Displeased3 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","05","06","mainpark","",0,"","false",800,950))
image choro Mainpark Displeased3 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","05","06","mainpark","",0,"","true",800,950))
image choro Mainpark Displeased3 Flip= Transform("choro Mainpark Displeased3",xzoom=-1.0)
image choro Mainpark Displeased3 Fade Flip= Transform("choro Mainpark Displeased3 Fade",xzoom=-1.0)
image choro Mainpark Happy1 = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","01","02","mainpark","",0,"","false",800,950))
image choro Mainpark Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","01","02","mainpark","",0,"","true",800,950))
image choro Mainpark Happy1 Flip= Transform("choro Mainpark Happy1",xzoom=-1.0)
image choro Mainpark Happy1 Fade Flip= Transform("choro Mainpark Happy1 Fade",xzoom=-1.0)
image choro Mainpark Happy2 = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","03","04","mainpark","",0,"","false",800,950))
image choro Mainpark Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","03","04","mainpark","",0,"","true",800,950))
image choro Mainpark Happy2 Flip= Transform("choro Mainpark Happy2",xzoom=-1.0)
image choro Mainpark Happy2 Fade Flip= Transform("choro Mainpark Happy2 Fade",xzoom=-1.0)
image choro Mainpark Nervous = DynamicDisplayable(renpy.curry(charComposite)("choro","nervous","01","02","mainpark","",0,"","false",800,950))
image choro Mainpark Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","nervous","01","02","mainpark","",0,"","true",800,950))
image choro Mainpark Nervous Flip= Transform("choro Mainpark Nervous",xzoom=-1.0)
image choro Mainpark Nervous Fade Flip= Transform("choro Mainpark Nervous Fade",xzoom=-1.0)
image choro Mainpark Neutral = DynamicDisplayable(renpy.curry(charComposite)("choro","neutral","01","02","mainpark","",0,"","false",800,950))
image choro Mainpark Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","neutral","01","02","mainpark","",0,"","true",800,950))
image choro Mainpark Neutral Flip= Transform("choro Mainpark Neutral",xzoom=-1.0)
image choro Mainpark Neutral Fade Flip= Transform("choro Mainpark Neutral Fade",xzoom=-1.0)
image choro Mainpark Shocked = DynamicDisplayable(renpy.curry(charComposite)("choro","shocked","01","02","mainpark","",0,"","false",800,950))
image choro Mainpark Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","shocked","01","02","mainpark","",0,"","true",800,950))
image choro Mainpark Shocked Flip= Transform("choro Mainpark Shocked",xzoom=-1.0)
image choro Mainpark Shocked Fade Flip= Transform("choro Mainpark Shocked Fade",xzoom=-1.0)
image choro Mainpark Surprised = DynamicDisplayable(renpy.curry(charComposite)("choro","surprised","01","02","mainpark","",0,"","false",800,950))
image choro Mainpark Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","surprised","01","02","mainpark","",0,"","true",800,950))
image choro Mainpark Surprised Flip= Transform("choro Mainpark Surprised",xzoom=-1.0)
image choro Mainpark Surprised Fade Flip= Transform("choro Mainpark Surprised Fade",xzoom=-1.0)
image choro Mainpark Thinking = DynamicDisplayable(renpy.curry(charComposite)("choro","thinking","01","02","mainpark","",0,"","false",800,950))
image choro Mainpark Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","thinking","01","02","mainpark","",0,"","true",800,950))
image choro Mainpark Thinking Flip= Transform("choro Mainpark Thinking",xzoom=-1.0)
image choro Mainpark Thinking Fade Flip= Transform("choro Mainpark Thinking Fade",xzoom=-1.0)
image choro Maintee Angry1 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","01","02","maintee","",0,"","false",800,950))
image choro Maintee Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","01","02","maintee","",0,"","true",800,950))
image choro Maintee Angry1 Flip= Transform("choro Maintee Angry1",xzoom=-1.0)
image choro Maintee Angry1 Fade Flip= Transform("choro Maintee Angry1 Fade",xzoom=-1.0)
image choro Maintee Angry2 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","03","04","maintee","",0,"","false",800,950))
image choro Maintee Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","03","04","maintee","",0,"","true",800,950))
image choro Maintee Angry2 Flip= Transform("choro Maintee Angry2",xzoom=-1.0)
image choro Maintee Angry2 Fade Flip= Transform("choro Maintee Angry2 Fade",xzoom=-1.0)
image choro Maintee Angry3 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","05","06","maintee","",0,"","false",800,950))
image choro Maintee Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","05","06","maintee","",0,"","true",800,950))
image choro Maintee Angry3 Flip= Transform("choro Maintee Angry3",xzoom=-1.0)
image choro Maintee Angry3 Fade Flip= Transform("choro Maintee Angry3 Fade",xzoom=-1.0)
image choro Maintee Dark = DynamicDisplayable(renpy.curry(charComposite)("choro","dark","","","maintee","",0,"","false",800,950))
image choro Maintee Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","dark","","","maintee","",0,"","true",800,950))
image choro Maintee Dark Flip= Transform("choro Maintee Dark",xzoom=-1.0)
image choro Maintee Dark Fade Flip= Transform("choro Maintee Dark Fade",xzoom=-1.0)
image choro Maintee Blank = DynamicDisplayable(renpy.curry(charComposite)("choro","blank","01","02","maintee","",0,"","false",800,950))
image choro Maintee Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","blank","01","02","maintee","",0,"","true",800,950))
image choro Maintee Blank Flip= Transform("choro Maintee Blank",xzoom=-1.0)
image choro Maintee Blank Fade Flip= Transform("choro Maintee Blank Fade",xzoom=-1.0)
image choro Maintee Displeased1 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","01","02","maintee","",0,"","false",800,950))
image choro Maintee Displeased1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","01","02","maintee","",0,"","true",800,950))
image choro Maintee Displeased1 Flip= Transform("choro Maintee Displeased1",xzoom=-1.0)
image choro Maintee Displeased1 Fade Flip= Transform("choro Maintee Displeased1 Fade",xzoom=-1.0)
image choro Maintee Displeased2 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","03","04","maintee","",0,"","false",800,950))
image choro Maintee Displeased2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","03","04","maintee","",0,"","true",800,950))
image choro Maintee Displeased2 Flip= Transform("choro Maintee Displeased2",xzoom=-1.0)
image choro Maintee Displeased2 Fade Flip= Transform("choro Maintee Displeased2 Fade",xzoom=-1.0)
image choro Maintee Displeased3 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","05","06","maintee","",0,"","false",800,950))
image choro Maintee Displeased3 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","05","06","maintee","",0,"","true",800,950))
image choro Maintee Displeased3 Flip= Transform("choro Maintee Displeased3",xzoom=-1.0)
image choro Maintee Displeased3 Fade Flip= Transform("choro Maintee Displeased3 Fade",xzoom=-1.0)
image choro Maintee Happy1 = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","01","02","maintee","",0,"","false",800,950))
image choro Maintee Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","01","02","maintee","",0,"","true",800,950))
image choro Maintee Happy1 Flip= Transform("choro Maintee Happy1",xzoom=-1.0)
image choro Maintee Happy1 Fade Flip= Transform("choro Maintee Happy1 Fade",xzoom=-1.0)
image choro Maintee Happy2 = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","03","04","maintee","",0,"","false",800,950))
image choro Maintee Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","03","04","maintee","",0,"","true",800,950))
image choro Maintee Happy2 Flip= Transform("choro Maintee Happy2",xzoom=-1.0)
image choro Maintee Happy2 Fade Flip= Transform("choro Maintee Happy2 Fade",xzoom=-1.0)
image choro Maintee Nervous = DynamicDisplayable(renpy.curry(charComposite)("choro","nervous","01","02","maintee","",0,"","false",800,950))
image choro Maintee Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","nervous","01","02","maintee","",0,"","true",800,950))
image choro Maintee Nervous Flip= Transform("choro Maintee Nervous",xzoom=-1.0)
image choro Maintee Nervous Fade Flip= Transform("choro Maintee Nervous Fade",xzoom=-1.0)
image choro Maintee Neutral = DynamicDisplayable(renpy.curry(charComposite)("choro","neutral","01","02","maintee","",0,"","false",800,950))
image choro Maintee Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","neutral","01","02","maintee","",0,"","true",800,950))
image choro Maintee Neutral Flip= Transform("choro Maintee Neutral",xzoom=-1.0)
image choro Maintee Neutral Fade Flip= Transform("choro Maintee Neutral Fade",xzoom=-1.0)
image choro Maintee Shocked = DynamicDisplayable(renpy.curry(charComposite)("choro","shocked","01","02","maintee","",0,"","false",800,950))
image choro Maintee Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","shocked","01","02","maintee","",0,"","true",800,950))
image choro Maintee Shocked Flip= Transform("choro Maintee Shocked",xzoom=-1.0)
image choro Maintee Shocked Fade Flip= Transform("choro Maintee Shocked Fade",xzoom=-1.0)
image choro Maintee Surprised = DynamicDisplayable(renpy.curry(charComposite)("choro","surprised","01","02","maintee","",0,"","false",800,950))
image choro Maintee Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","surprised","01","02","maintee","",0,"","true",800,950))
image choro Maintee Surprised Flip= Transform("choro Maintee Surprised",xzoom=-1.0)
image choro Maintee Surprised Fade Flip= Transform("choro Maintee Surprised Fade",xzoom=-1.0)
image choro Maintee Thinking = DynamicDisplayable(renpy.curry(charComposite)("choro","thinking","01","02","maintee","",0,"","false",800,950))
image choro Maintee Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","thinking","01","02","maintee","",0,"","true",800,950))
image choro Maintee Thinking Flip= Transform("choro Maintee Thinking",xzoom=-1.0)
image choro Maintee Thinking Fade Flip= Transform("choro Maintee Thinking Fade",xzoom=-1.0)
image choro PJ Angry1 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","01","02","pj","",0,"","false",800,950))
image choro PJ Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","01","02","pj","",0,"","true",800,950))
image choro PJ Angry1 Flip= Transform("choro PJ Angry1",xzoom=-1.0)
image choro PJ Angry1 Fade Flip= Transform("choro PJ Angry1 Fade",xzoom=-1.0)
image choro PJ Angry2 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","03","04","pj","",0,"","false",800,950))
image choro PJ Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","03","04","pj","",0,"","true",800,950))
image choro PJ Angry2 Flip= Transform("choro PJ Angry2",xzoom=-1.0)
image choro PJ Angry2 Fade Flip= Transform("choro PJ Angry2 Fade",xzoom=-1.0)
image choro PJ Angry3 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","05","06","pj","",0,"","false",800,950))
image choro PJ Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","05","06","pj","",0,"","true",800,950))
image choro PJ Angry3 Flip= Transform("choro PJ Angry3",xzoom=-1.0)
image choro PJ Angry3 Fade Flip= Transform("choro PJ Angry3 Fade",xzoom=-1.0)
image choro PJ Dark = DynamicDisplayable(renpy.curry(charComposite)("choro","dark","","","pj","",0,"","false",800,950))
image choro PJ Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","dark","","","pj","",0,"","true",800,950))
image choro PJ Dark Flip= Transform("choro PJ Dark",xzoom=-1.0)
image choro PJ Dark Fade Flip= Transform("choro PJ Dark Fade",xzoom=-1.0)
image choro PJ Blank = DynamicDisplayable(renpy.curry(charComposite)("choro","blank","01","02","pj","",0,"","false",800,950))
image choro PJ Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","blank","01","02","pj","",0,"","true",800,950))
image choro PJ Blank Flip= Transform("choro PJ Blank",xzoom=-1.0)
image choro PJ Blank Fade Flip= Transform("choro PJ Blank Fade",xzoom=-1.0)
image choro PJ Displeased1 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","01","02","pj","",0,"","false",800,950))
image choro PJ Displeased1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","01","02","pj","",0,"","true",800,950))
image choro PJ Displeased1 Flip= Transform("choro PJ Displeased1",xzoom=-1.0)
image choro PJ Displeased1 Fade Flip= Transform("choro PJ Displeased1 Fade",xzoom=-1.0)
image choro PJ Displeased2 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","03","04","pj","",0,"","false",800,950))
image choro PJ Displeased2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","03","04","pj","",0,"","true",800,950))
image choro PJ Displeased2 Flip= Transform("choro PJ Displeased2",xzoom=-1.0)
image choro PJ Displeased2 Fade Flip= Transform("choro PJ Displeased2 Fade",xzoom=-1.0)
image choro PJ Displeased3 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","05","06","pj","",0,"","false",800,950))
image choro PJ Displeased3 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","05","06","pj","",0,"","true",800,950))
image choro PJ Displeased3 Flip= Transform("choro PJ Displeased3",xzoom=-1.0)
image choro PJ Displeased3 Fade Flip= Transform("choro PJ Displeased3 Fade",xzoom=-1.0)
image choro PJ Happy1 = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","01","02","pj","",0,"","false",800,950))
image choro PJ Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","01","02","pj","",0,"","true",800,950))
image choro PJ Happy1 Flip= Transform("choro PJ Happy1",xzoom=-1.0)
image choro PJ Happy1 Fade Flip= Transform("choro PJ Happy1 Fade",xzoom=-1.0)
image choro PJ Happy2 = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","03","04","pj","",0,"","false",800,950))
image choro PJ Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","03","04","pj","",0,"","true",800,950))
image choro PJ Happy2 Flip= Transform("choro PJ Happy2",xzoom=-1.0)
image choro PJ Happy2 Fade Flip= Transform("choro PJ Happy2 Fade",xzoom=-1.0)
image choro PJ Nervous = DynamicDisplayable(renpy.curry(charComposite)("choro","nervous","01","02","pj","",0,"","false",800,950))
image choro PJ Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","nervous","01","02","pj","",0,"","true",800,950))
image choro PJ Nervous Flip= Transform("choro PJ Nervous",xzoom=-1.0)
image choro PJ Nervous Fade Flip= Transform("choro PJ Nervous Fade",xzoom=-1.0)
image choro PJ Neutral = DynamicDisplayable(renpy.curry(charComposite)("choro","neutral","01","02","pj","",0,"","false",800,950))
image choro PJ Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","neutral","01","02","pj","",0,"","true",800,950))
image choro PJ Neutral Flip= Transform("choro PJ Neutral",xzoom=-1.0)
image choro PJ Neutral Fade Flip= Transform("choro PJ Neutral Fade",xzoom=-1.0)
image choro PJ Shocked = DynamicDisplayable(renpy.curry(charComposite)("choro","shocked","01","02","pj","",0,"","false",800,950))
image choro PJ Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","shocked","01","02","pj","",0,"","true",800,950))
image choro PJ Shocked Flip= Transform("choro PJ Shocked",xzoom=-1.0)
image choro PJ Shocked Fade Flip= Transform("choro PJ Shocked Fade",xzoom=-1.0)
image choro PJ Surprised = DynamicDisplayable(renpy.curry(charComposite)("choro","surprised","01","02","pj","",0,"","false",800,950))
image choro PJ Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","surprised","01","02","pj","",0,"","true",800,950))
image choro PJ Surprised Flip= Transform("choro PJ Surprised",xzoom=-1.0)
image choro PJ Surprised Fade Flip= Transform("choro PJ Surprised Fade",xzoom=-1.0)
image choro PJ Thinking = DynamicDisplayable(renpy.curry(charComposite)("choro","thinking","01","02","pj","",0,"","false",800,950))
image choro PJ Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","thinking","01","02","pj","",0,"","true",800,950))
image choro PJ Thinking Flip= Transform("choro PJ Thinking",xzoom=-1.0)
image choro PJ Thinking Fade Flip= Transform("choro PJ Thinking Fade",xzoom=-1.0)
image choro SchoolS Angry1 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","01","02","schools","",0,"","false",800,950))
image choro SchoolS Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","01","02","schools","",0,"","true",800,950))
image choro SchoolS Angry1 Flip= Transform("choro SchoolS Angry1",xzoom=-1.0)
image choro SchoolS Angry1 Fade Flip= Transform("choro SchoolS Angry1 Fade",xzoom=-1.0)
image choro SchoolS Angry2 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","03","04","schools","",0,"","false",800,950))
image choro SchoolS Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","03","04","schools","",0,"","true",800,950))
image choro SchoolS Angry2 Flip= Transform("choro SchoolS Angry2",xzoom=-1.0)
image choro SchoolS Angry2 Fade Flip= Transform("choro SchoolS Angry2 Fade",xzoom=-1.0)
image choro SchoolS Angry3 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","05","06","schools","",0,"","false",800,950))
image choro SchoolS Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","05","06","schools","",0,"","true",800,950))
image choro SchoolS Angry3 Flip= Transform("choro SchoolS Angry3",xzoom=-1.0)
image choro SchoolS Angry3 Fade Flip= Transform("choro SchoolS Angry3 Fade",xzoom=-1.0)
image choro SchoolS Dark = DynamicDisplayable(renpy.curry(charComposite)("choro","dark","","","schools","",0,"","false",800,950))
image choro SchoolS Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","dark","","","schools","",0,"","true",800,950))
image choro SchoolS Dark Flip= Transform("choro SchoolS Dark",xzoom=-1.0)
image choro SchoolS Dark Fade Flip= Transform("choro SchoolS Dark Fade",xzoom=-1.0)
image choro SchoolS Blank = DynamicDisplayable(renpy.curry(charComposite)("choro","blank","01","02","schools","",0,"","false",800,950))
image choro SchoolS Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","blank","01","02","schools","",0,"","true",800,950))
image choro SchoolS Blank Flip= Transform("choro SchoolS Blank",xzoom=-1.0)
image choro SchoolS Blank Fade Flip= Transform("choro SchoolS Blank Fade",xzoom=-1.0)
image choro SchoolS Displeased1 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","01","02","schools","",0,"","false",800,950))
image choro SchoolS Displeased1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","01","02","schools","",0,"","true",800,950))
image choro SchoolS Displeased1 Flip= Transform("choro SchoolS Displeased1",xzoom=-1.0)
image choro SchoolS Displeased1 Fade Flip= Transform("choro SchoolS Displeased1 Fade",xzoom=-1.0)
image choro SchoolS Displeased2 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","03","04","schools","",0,"","false",800,950))
image choro SchoolS Displeased2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","03","04","schools","",0,"","true",800,950))
image choro SchoolS Displeased2 Flip= Transform("choro SchoolS Displeased2",xzoom=-1.0)
image choro SchoolS Displeased2 Fade Flip= Transform("choro SchoolS Displeased2 Fade",xzoom=-1.0)
image choro SchoolS Displeased3 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","05","06","schools","",0,"","false",800,950))
image choro SchoolS Displeased3 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","05","06","schools","",0,"","true",800,950))
image choro SchoolS Displeased3 Flip= Transform("choro SchoolS Displeased3",xzoom=-1.0)
image choro SchoolS Displeased3 Fade Flip= Transform("choro SchoolS Displeased3 Fade",xzoom=-1.0)
image choro SchoolS Happy1 = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","01","02","schools","",0,"","false",800,950))
image choro SchoolS Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","01","02","schools","",0,"","true",800,950))
image choro SchoolS Happy1 Flip= Transform("choro SchoolS Happy1",xzoom=-1.0)
image choro SchoolS Happy1 Fade Flip= Transform("choro SchoolS Happy1 Fade",xzoom=-1.0)
image choro SchoolS Happy2 = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","03","04","schools","",0,"","false",800,950))
image choro SchoolS Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","03","04","schools","",0,"","true",800,950))
image choro SchoolS Happy2 Flip= Transform("choro SchoolS Happy2",xzoom=-1.0)
image choro SchoolS Happy2 Fade Flip= Transform("choro SchoolS Happy2 Fade",xzoom=-1.0)
image choro SchoolS Nervous = DynamicDisplayable(renpy.curry(charComposite)("choro","nervous","01","02","schools","",0,"","false",800,950))
image choro SchoolS Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","nervous","01","02","schools","",0,"","true",800,950))
image choro SchoolS Nervous Flip= Transform("choro SchoolS Nervous",xzoom=-1.0)
image choro SchoolS Nervous Fade Flip= Transform("choro SchoolS Nervous Fade",xzoom=-1.0)
image choro SchoolS Neutral = DynamicDisplayable(renpy.curry(charComposite)("choro","neutral","01","02","schools","",0,"","false",800,950))
image choro SchoolS Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","neutral","01","02","schools","",0,"","true",800,950))
image choro SchoolS Neutral Flip= Transform("choro SchoolS Neutral",xzoom=-1.0)
image choro SchoolS Neutral Fade Flip= Transform("choro SchoolS Neutral Fade",xzoom=-1.0)
image choro SchoolS Shocked = DynamicDisplayable(renpy.curry(charComposite)("choro","shocked","01","02","schools","",0,"","false",800,950))
image choro SchoolS Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","shocked","01","02","schools","",0,"","true",800,950))
image choro SchoolS Shocked Flip= Transform("choro SchoolS Shocked",xzoom=-1.0)
image choro SchoolS Shocked Fade Flip= Transform("choro SchoolS Shocked Fade",xzoom=-1.0)
image choro SchoolS Surprised = DynamicDisplayable(renpy.curry(charComposite)("choro","surprised","01","02","schools","",0,"","false",800,950))
image choro SchoolS Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","surprised","01","02","schools","",0,"","true",800,950))
image choro SchoolS Surprised Flip= Transform("choro SchoolS Surprised",xzoom=-1.0)
image choro SchoolS Surprised Fade Flip= Transform("choro SchoolS Surprised Fade",xzoom=-1.0)
image choro SchoolS Thinking = DynamicDisplayable(renpy.curry(charComposite)("choro","thinking","01","02","schools","",0,"","false",800,950))
image choro SchoolS Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","thinking","01","02","schools","",0,"","true",800,950))
image choro SchoolS Thinking Flip= Transform("choro SchoolS Thinking",xzoom=-1.0)
image choro SchoolS Thinking Fade Flip= Transform("choro SchoolS Thinking Fade",xzoom=-1.0)
image choro SchoolW Angry1 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","01","02","schoolw","",0,"","false",800,950))
image choro SchoolW Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","01","02","schoolw","",0,"","true",800,950))
image choro SchoolW Angry1 Flip= Transform("choro SchoolW Angry1",xzoom=-1.0)
image choro SchoolW Angry1 Fade Flip= Transform("choro SchoolW Angry1 Fade",xzoom=-1.0)
image choro SchoolW Angry2 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","03","04","schoolw","",0,"","false",800,950))
image choro SchoolW Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","03","04","schoolw","",0,"","true",800,950))
image choro SchoolW Angry2 Flip= Transform("choro SchoolW Angry2",xzoom=-1.0)
image choro SchoolW Angry2 Fade Flip= Transform("choro SchoolW Angry2 Fade",xzoom=-1.0)
image choro SchoolW Angry3 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","05","06","schoolw","",0,"","false",800,950))
image choro SchoolW Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","05","06","schoolw","",0,"","true",800,950))
image choro SchoolW Angry3 Flip= Transform("choro SchoolW Angry3",xzoom=-1.0)
image choro SchoolW Angry3 Fade Flip= Transform("choro SchoolW Angry3 Fade",xzoom=-1.0)
image choro SchoolW Dark = DynamicDisplayable(renpy.curry(charComposite)("choro","dark","","","schoolw","",0,"","false",800,950))
image choro SchoolW Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","dark","","","schoolw","",0,"","true",800,950))
image choro SchoolW Dark Flip= Transform("choro SchoolW Dark",xzoom=-1.0)
image choro SchoolW Dark Fade Flip= Transform("choro SchoolW Dark Fade",xzoom=-1.0)
image choro SchoolW Blank = DynamicDisplayable(renpy.curry(charComposite)("choro","blank","01","02","schoolw","",0,"","false",800,950))
image choro SchoolW Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","blank","01","02","schoolw","",0,"","true",800,950))
image choro SchoolW Blank Flip= Transform("choro SchoolW Blank",xzoom=-1.0)
image choro SchoolW Blank Fade Flip= Transform("choro SchoolW Blank Fade",xzoom=-1.0)
image choro SchoolW Displeased1 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","01","02","schoolw","",0,"","false",800,950))
image choro SchoolW Displeased1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","01","02","schoolw","",0,"","true",800,950))
image choro SchoolW Displeased1 Flip= Transform("choro SchoolW Displeased1",xzoom=-1.0)
image choro SchoolW Displeased1 Fade Flip= Transform("choro SchoolW Displeased1 Fade",xzoom=-1.0)
image choro SchoolW Displeased2 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","03","04","schoolw","",0,"","false",800,950))
image choro SchoolW Displeased2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","03","04","schoolw","",0,"","true",800,950))
image choro SchoolW Displeased2 Flip= Transform("choro SchoolW Displeased2",xzoom=-1.0)
image choro SchoolW Displeased2 Fade Flip= Transform("choro SchoolW Displeased2 Fade",xzoom=-1.0)
image choro SchoolW Displeased3 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","05","06","schoolw","",0,"","false",800,950))
image choro SchoolW Displeased3 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","05","06","schoolw","",0,"","true",800,950))
image choro SchoolW Displeased3 Flip= Transform("choro SchoolW Displeased3",xzoom=-1.0)
image choro SchoolW Displeased3 Fade Flip= Transform("choro SchoolW Displeased3 Fade",xzoom=-1.0)
image choro SchoolW Happy1 = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","01","02","schoolw","",0,"","false",800,950))
image choro SchoolW Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","01","02","schoolw","",0,"","true",800,950))
image choro SchoolW Happy1 Flip= Transform("choro SchoolW Happy1",xzoom=-1.0)
image choro SchoolW Happy1 Fade Flip= Transform("choro SchoolW Happy1 Fade",xzoom=-1.0)
image choro SchoolW Happy2 = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","03","04","schoolw","",0,"","false",800,950))
image choro SchoolW Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","03","04","schoolw","",0,"","true",800,950))
image choro SchoolW Happy2 Flip= Transform("choro SchoolW Happy2",xzoom=-1.0)
image choro SchoolW Happy2 Fade Flip= Transform("choro SchoolW Happy2 Fade",xzoom=-1.0)
image choro SchoolW Nervous = DynamicDisplayable(renpy.curry(charComposite)("choro","nervous","01","02","schoolw","",0,"","false",800,950))
image choro SchoolW Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","nervous","01","02","schoolw","",0,"","true",800,950))
image choro SchoolW Nervous Flip= Transform("choro SchoolW Nervous",xzoom=-1.0)
image choro SchoolW Nervous Fade Flip= Transform("choro SchoolW Nervous Fade",xzoom=-1.0)
image choro SchoolW Neutral = DynamicDisplayable(renpy.curry(charComposite)("choro","neutral","01","02","schoolw","",0,"","false",800,950))
image choro SchoolW Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","neutral","01","02","schoolw","",0,"","true",800,950))
image choro SchoolW Neutral Flip= Transform("choro SchoolW Neutral",xzoom=-1.0)
image choro SchoolW Neutral Fade Flip= Transform("choro SchoolW Neutral Fade",xzoom=-1.0)
image choro SchoolW Shocked = DynamicDisplayable(renpy.curry(charComposite)("choro","shocked","01","02","schoolw","",0,"","false",800,950))
image choro SchoolW Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","shocked","01","02","schoolw","",0,"","true",800,950))
image choro SchoolW Shocked Flip= Transform("choro SchoolW Shocked",xzoom=-1.0)
image choro SchoolW Shocked Fade Flip= Transform("choro SchoolW Shocked Fade",xzoom=-1.0)
image choro SchoolW Surprised = DynamicDisplayable(renpy.curry(charComposite)("choro","surprised","01","02","schoolw","",0,"","false",800,950))
image choro SchoolW Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","surprised","01","02","schoolw","",0,"","true",800,950))
image choro SchoolW Surprised Flip= Transform("choro SchoolW Surprised",xzoom=-1.0)
image choro SchoolW Surprised Fade Flip= Transform("choro SchoolW Surprised Fade",xzoom=-1.0)
image choro SchoolW Thinking = DynamicDisplayable(renpy.curry(charComposite)("choro","thinking","01","02","schoolw","",0,"","false",800,950))
image choro SchoolW Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","thinking","01","02","schoolw","",0,"","true",800,950))
image choro SchoolW Thinking Flip= Transform("choro SchoolW Thinking",xzoom=-1.0)
image choro SchoolW Thinking Fade Flip= Transform("choro SchoolW Thinking Fade",xzoom=-1.0)
image choro Naked Angry1 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","01","02","naked","",0,"","false",800,950))
image choro Naked Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","01","02","naked","",0,"","true",800,950))
image choro Naked Angry1 Flip= Transform("choro Naked Angry1",xzoom=-1.0)
image choro Naked Angry1 Fade Flip= Transform("choro Naked Angry1 Fade",xzoom=-1.0)
image choro Naked Angry2 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","03","04","naked","",0,"","false",800,950))
image choro Naked Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","03","04","naked","",0,"","true",800,950))
image choro Naked Angry2 Flip= Transform("choro Naked Angry2",xzoom=-1.0)
image choro Naked Angry2 Fade Flip= Transform("choro Naked Angry2 Fade",xzoom=-1.0)
image choro Naked Angry3 = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","05","06","naked","",0,"","false",800,950))
image choro Naked Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","angry","05","06","naked","",0,"","true",800,950))
image choro Naked Angry3 Flip= Transform("choro Naked Angry3",xzoom=-1.0)
image choro Naked Angry3 Fade Flip= Transform("choro Naked Angry3 Fade",xzoom=-1.0)
image choro Naked Dark = DynamicDisplayable(renpy.curry(charComposite)("choro","dark","","","naked","",0,"","false",800,950))
image choro Naked Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","dark","","","naked","",0,"","true",800,950))
image choro Naked Dark Flip= Transform("choro Naked Dark",xzoom=-1.0)
image choro Naked Dark Fade Flip= Transform("choro Naked Dark Fade",xzoom=-1.0)
image choro Naked Blank = DynamicDisplayable(renpy.curry(charComposite)("choro","blank","01","02","naked","",0,"","false",800,950))
image choro Naked Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","blank","01","02","naked","",0,"","true",800,950))
image choro Naked Blank Flip= Transform("choro Naked Blank",xzoom=-1.0)
image choro Naked Blank Fade Flip= Transform("choro Naked Blank Fade",xzoom=-1.0)
image choro Naked Displeased1 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","01","02","naked","",0,"","false",800,950))
image choro Naked Displeased1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","01","02","naked","",0,"","true",800,950))
image choro Naked Displeased1 Flip= Transform("choro Naked Displeased1",xzoom=-1.0)
image choro Naked Displeased1 Fade Flip= Transform("choro Naked Displeased1 Fade",xzoom=-1.0)
image choro Naked Displeased2 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","03","04","naked","",0,"","false",800,950))
image choro Naked Displeased2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","03","04","naked","",0,"","true",800,950))
image choro Naked Displeased2 Flip= Transform("choro Naked Displeased2",xzoom=-1.0)
image choro Naked Displeased2 Fade Flip= Transform("choro Naked Displeased2 Fade",xzoom=-1.0)
image choro Naked Displeased3 = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","05","06","naked","",0,"","false",800,950))
image choro Naked Displeased3 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","displeased","05","06","naked","",0,"","true",800,950))
image choro Naked Displeased3 Flip= Transform("choro Naked Displeased3",xzoom=-1.0)
image choro Naked Displeased3 Fade Flip= Transform("choro Naked Displeased3 Fade",xzoom=-1.0)
image choro Naked Happy1 = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","01","02","naked","",0,"","false",800,950))
image choro Naked Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","01","02","naked","",0,"","true",800,950))
image choro Naked Happy1 Flip= Transform("choro Naked Happy1",xzoom=-1.0)
image choro Naked Happy1 Fade Flip= Transform("choro Naked Happy1 Fade",xzoom=-1.0)
image choro Naked Happy2 = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","03","04","naked","",0,"","false",800,950))
image choro Naked Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","happy","03","04","naked","",0,"","true",800,950))
image choro Naked Happy2 Flip= Transform("choro Naked Happy2",xzoom=-1.0)
image choro Naked Happy2 Fade Flip= Transform("choro Naked Happy2 Fade",xzoom=-1.0)
image choro Naked Nervous = DynamicDisplayable(renpy.curry(charComposite)("choro","nervous","01","02","naked","",0,"","false",800,950))
image choro Naked Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","nervous","01","02","naked","",0,"","true",800,950))
image choro Naked Nervous Flip= Transform("choro Naked Nervous",xzoom=-1.0)
image choro Naked Nervous Fade Flip= Transform("choro Naked Nervous Fade",xzoom=-1.0)
image choro Naked Neutral = DynamicDisplayable(renpy.curry(charComposite)("choro","neutral","01","02","naked","",0,"","false",800,950))
image choro Naked Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","neutral","01","02","naked","",0,"","true",800,950))
image choro Naked Neutral Flip= Transform("choro Naked Neutral",xzoom=-1.0)
image choro Naked Neutral Fade Flip= Transform("choro Naked Neutral Fade",xzoom=-1.0)
image choro Naked Shocked = DynamicDisplayable(renpy.curry(charComposite)("choro","shocked","01","02","naked","",0,"","false",800,950))
image choro Naked Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","shocked","01","02","naked","",0,"","true",800,950))
image choro Naked Shocked Flip= Transform("choro Naked Shocked",xzoom=-1.0)
image choro Naked Shocked Fade Flip= Transform("choro Naked Shocked Fade",xzoom=-1.0)
image choro Naked Surprised = DynamicDisplayable(renpy.curry(charComposite)("choro","surprised","01","02","naked","",0,"","false",800,950))
image choro Naked Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","surprised","01","02","naked","",0,"","true",800,950))
image choro Naked Surprised Flip= Transform("choro Naked Surprised",xzoom=-1.0)
image choro Naked Surprised Fade Flip= Transform("choro Naked Surprised Fade",xzoom=-1.0)
image choro Naked Thinking = DynamicDisplayable(renpy.curry(charComposite)("choro","thinking","01","02","naked","",0,"","false",800,950))
image choro Naked Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("choro","thinking","01","02","naked","",0,"","true",800,950))
image choro Naked Thinking Flip= Transform("choro Naked Thinking",xzoom=-1.0)
image choro Naked Thinking Fade Flip= Transform("choro Naked Thinking Fade",xzoom=-1.0)
