# COMMENTS:
#
# Images are named like this:
# chara Clothes Expression Fade Flip
# Add Fade/Flip when needed
#
# Ichimatsu has the following clothes:
# SchoolS SchoolW Bathrobe Bathtowel MainPark Naked Pj Sera
#
# Ichimatsu has the following expressions:
# Neutral Angry Displeased Happy Shocked Stare
#
# Adding New Images:
# Use the same naming convention, copy paste the right code per commented section.
# The numbers are for head animation, for expressions such as dark, leave it as "" if it has no number behind.
# Remember every image needs normal, flip, fade, flip fade.
# Every new outfit also needs all the expressions (just in case)

#Ichimatsu Images
image ichi Bathrobe Angry1 = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","01","02","bathrobe","",0,"","false",800,950))
image ichi Bathrobe Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","01","02","bathrobe","",0,"","true",800,950))
image ichi Bathrobe Angry1 Flip= Transform("ichi Bathrobe Angry1",xzoom=-1.0)
image ichi Bathrobe Angry1 Fade Flip= Transform("ichi Bathrobe Angry1 Fade",xzoom=-1.0)
image ichi Bathrobe Angry2 = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","03","04","bathrobe","",0,"","false",800,950))
image ichi Bathrobe Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","03","04","bathrobe","",0,"","true",800,950))
image ichi Bathrobe Angry2 Flip= Transform("ichi Bathrobe Angry2",xzoom=-1.0)
image ichi Bathrobe Angry2 Fade Flip= Transform("ichi Bathrobe Angry2 Fade",xzoom=-1.0)
image ichi Bathrobe Dark = DynamicDisplayable(renpy.curry(charComposite)("ichi","dark","","","bathrobe","",0,"","false",800,950))
image ichi Bathrobe Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","dark","","","bathrobe","",0,"","true",800,950))
image ichi Bathrobe Dark Flip= Transform("ichi Bathrobe Dark",xzoom=-1.0)
image ichi Bathrobe Dark Fade Flip= Transform("ichi Bathrobe Dark Fade",xzoom=-1.0)
image ichi Bathrobe Blank = DynamicDisplayable(renpy.curry(charComposite)("ichi","blank","01","02","bathrobe","",0,"","false",800,950))
image ichi Bathrobe Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","blank","01","02","bathrobe","",0,"","true",800,950))
image ichi Bathrobe Blank Flip= Transform("ichi Bathrobe Blank",xzoom=-1.0)
image ichi Bathrobe Blank Fade Flip= Transform("ichi Bathrobe Blank Fade",xzoom=-1.0)
image ichi Bathrobe Displeased = DynamicDisplayable(renpy.curry(charComposite)("ichi","displeased","01","02","bathrobe","",0,"","false",800,950))
image ichi Bathrobe Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","displeased","01","02","bathrobe","",0,"","true",800,950))
image ichi Bathrobe Displeased Flip= Transform("ichi Bathrobe Displeased",xzoom=-1.0)
image ichi Bathrobe Displeased Fade Flip= Transform("ichi Bathrobe Displeased Fade",xzoom=-1.0)
image ichi Bathrobe Gasp = DynamicDisplayable(renpy.curry(charComposite)("ichi","gasp","01","02","bathrobe","",0,"","false",800,950))
image ichi Bathrobe Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","gasp","01","02","bathrobe","",0,"","true",800,950))
image ichi Bathrobe Gasp Flip= Transform("ichi Bathrobe Gasp",xzoom=-1.0)
image ichi Bathrobe Gasp Fade Flip= Transform("ichi Bathrobe Gasp Fade",xzoom=-1.0)
image ichi Bathrobe Happy1 = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","01","02","bathrobe","",0,"","false",800,950))
image ichi Bathrobe Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","01","02","bathrobe","",0,"","true",800,950))
image ichi Bathrobe Happy1 Flip= Transform("ichi Bathrobe Happy1",xzoom=-1.0)
image ichi Bathrobe Happy1 Fade Flip= Transform("ichi Bathrobe Happy1 Fade",xzoom=-1.0)
image ichi Bathrobe Happy2 = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","03","04","bathrobe","",0,"","false",800,950))
image ichi Bathrobe Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","03","04","bathrobe","",0,"","true",800,950))
image ichi Bathrobe Happy2 Flip= Transform("ichi Bathrobe Happy2",xzoom=-1.0)
image ichi Bathrobe Happy2 Fade Flip= Transform("ichi Bathrobe Happy2 Fade",xzoom=-1.0)
image ichi Bathrobe Nervous = DynamicDisplayable(renpy.curry(charComposite)("ichi","nervous","01","02","bathrobe","",0,"","false",800,950))
image ichi Bathrobe Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","nervous","01","02","bathrobe","",0,"","true",800,950))
image ichi Bathrobe Nervous Flip= Transform("ichi Bathrobe Nervous",xzoom=-1.0)
image ichi Bathrobe Nervous Fade Flip= Transform("ichi Bathrobe Nervous Fade",xzoom=-1.0)
image ichi Bathrobe Neutral = DynamicDisplayable(renpy.curry(charComposite)("ichi","neutral","01","02","bathrobe","",0,"","false",800,950))
image ichi Bathrobe Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","neutral","01","02","bathrobe","",0,"","true",800,950))
image ichi Bathrobe Neutral Flip= Transform("ichi Bathrobe Neutral",xzoom=-1.0)
image ichi Bathrobe Neutral Fade Flip= Transform("ichi Bathrobe Neutral Fade",xzoom=-1.0)
image ichi Bathrobe Shocked = DynamicDisplayable(renpy.curry(charComposite)("ichi","shocked","01","02","bathrobe","",0,"","false",800,950))
image ichi Bathrobe Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","shocked","01","02","bathrobe","",0,"","true",800,950))
image ichi Bathrobe Shocked Flip= Transform("ichi Bathrobe Shocked",xzoom=-1.0)
image ichi Bathrobe Shocked Fade Flip= Transform("ichi Bathrobe Shocked Fade",xzoom=-1.0)
image ichi Bathrobe Thinking = DynamicDisplayable(renpy.curry(charComposite)("ichi","thinking","01","02","bathrobe","",0,"","false",800,950))
image ichi Bathrobe Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","thinking","01","02","bathrobe","",0,"","true",800,950))
image ichi Bathrobe Thinking Flip= Transform("ichi Bathrobe Thinking",xzoom=-1.0)
image ichi Bathrobe Thinking Fade Flip= Transform("ichi Bathrobe Thinking Fade",xzoom=-1.0)
image ichi Casual Angry1 = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","01","02","casual","","","",0,"","false",800,950))
image ichi Casual Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","01","02","casual","","","",0,"","true",800,950))
image ichi Casual Angry1 Flip= Transform("ichi Casual Angry1",xzoom=-1.0)
image ichi Casual Angry1 Fade Flip= Transform("ichi Casual Angry1 Fade",xzoom=-1.0)
image ichi Casual Angry2 = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","03","04","casual","","","",0,"","false",800,950))
image ichi Casual Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","03","04","casual","","","",0,"","true",800,950))
image ichi Casual Angry2 Flip= Transform("ichi Casual Angry2",xzoom=-1.0)
image ichi Casual Angry2 Fade Flip= Transform("ichi Casual Angry2 Fade",xzoom=-1.0)
image ichi Casual Dark = DynamicDisplayable(renpy.curry(charComposite)("ichi","dark","","","casual","","","",0,"","false",800,950))
image ichi Casual Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","dark","","","casual","","","",0,"","true",800,950))
image ichi Casual Dark Flip= Transform("ichi Casual Dark",xzoom=-1.0)
image ichi Casual Dark Fade Flip= Transform("ichi Casual Dark Fade",xzoom=-1.0)
image ichi Casual Blank = DynamicDisplayable(renpy.curry(charComposite)("ichi","blank","01","02","casual","","","",0,"","false",800,950))
image ichi Casual Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","blank","01","02","casual","","","",0,"","true",800,950))
image ichi Casual Blank Flip= Transform("ichi Casual Blank",xzoom=-1.0)
image ichi Casual Blank Fade Flip= Transform("ichi Casual Blank Fade",xzoom=-1.0)
image ichi Casual Displeased = DynamicDisplayable(renpy.curry(charComposite)("ichi","displeased","01","02","casual","","","",0,"","false",800,950))
image ichi Casual Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","displeased","01","02","casual","","","",0,"","true",800,950))
image ichi Casual Displeased Flip= Transform("ichi Casual Displeased",xzoom=-1.0)
image ichi Casual Displeased Fade Flip= Transform("ichi Casual Displeased Fade",xzoom=-1.0)
image ichi Casual Gasp = DynamicDisplayable(renpy.curry(charComposite)("ichi","gasp","01","02","casual","","","",0,"","false",800,950))
image ichi Casual Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","gasp","01","02","casual","","","",0,"","true",800,950))
image ichi Casual Gasp Flip= Transform("ichi Casual Gasp",xzoom=-1.0)
image ichi Casual Gasp Fade Flip= Transform("ichi Casual Gasp Fade",xzoom=-1.0)
image ichi Casual Happy1 = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","01","02","casual","","","",0,"","false",800,950))
image ichi Casual Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","01","02","casual","","","",0,"","true",800,950))
image ichi Casual Happy1 Flip= Transform("ichi Casual Happy1",xzoom=-1.0)
image ichi Casual Happy1 Fade Flip= Transform("ichi Casual Happy1 Fade",xzoom=-1.0)
image ichi Casual Happy2 = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","03","04","casual","","","",0,"","false",800,950))
image ichi Casual Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","03","04","casual","","","",0,"","true",800,950))
image ichi Casual Happy2 Flip= Transform("ichi Casual Happy2",xzoom=-1.0)
image ichi Casual Happy2 Fade Flip= Transform("ichi Casual Happy2 Fade",xzoom=-1.0)
image ichi Casual Nervous = DynamicDisplayable(renpy.curry(charComposite)("ichi","nervous","01","02","casual","","","",0,"","false",800,950))
image ichi Casual Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","nervous","01","02","casual","","","",0,"","true",800,950))
image ichi Casual Nervous Flip= Transform("ichi Casual Nervous",xzoom=-1.0)
image ichi Casual Nervous Fade Flip= Transform("ichi Casual Nervous Fade",xzoom=-1.0)
image ichi Casual Neutral = DynamicDisplayable(renpy.curry(charComposite)("ichi","neutral","01","02","casual","","","",0,"","false",800,950))
image ichi Casual Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","neutral","01","02","casual","","","",0,"","true",800,950))
image ichi Casual Neutral Flip= Transform("ichi Casual Neutral",xzoom=-1.0)
image ichi Casual Neutral Fade Flip= Transform("ichi Casual Neutral Fade",xzoom=-1.0)
image ichi Casual Shocked = DynamicDisplayable(renpy.curry(charComposite)("ichi","shocked","01","02","casual","","","",0,"","false",800,950))
image ichi Casual Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","shocked","01","02","casual","","","",0,"","true",800,950))
image ichi Casual Shocked Flip= Transform("ichi Casual Shocked",xzoom=-1.0)
image ichi Casual Shocked Fade Flip= Transform("ichi Casual Shocked Fade",xzoom=-1.0)
image ichi Casual Thinking = DynamicDisplayable(renpy.curry(charComposite)("ichi","thinking","01","02","casual","","","",0,"","false",800,950))
image ichi Casual Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","thinking","01","02","casual","","","",0,"","true",800,950))
image ichi Casual Thinking Flip= Transform("ichi Casual Thinking",xzoom=-1.0)
image ichi Casual Thinking Fade Flip= Transform("ichi Casual Thinking Fade",xzoom=-1.0)
image ichi Mainpark Angry1 = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","01","02","mainpark","",0,"","false",800,950))
image ichi Mainpark Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","01","02","mainpark","",0,"","true",800,950))
image ichi Mainpark Angry1 Flip= Transform("ichi Mainpark Angry1",xzoom=-1.0)
image ichi Mainpark Angry1 Fade Flip= Transform("ichi Mainpark Angry1 Fade",xzoom=-1.0)
image ichi Mainpark Angry2 = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","03","04","mainpark","",0,"","false",800,950))
image ichi Mainpark Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","03","04","mainpark","",0,"","true",800,950))
image ichi Mainpark Angry2 Flip= Transform("ichi Mainpark Angry2",xzoom=-1.0)
image ichi Mainpark Angry2 Fade Flip= Transform("ichi Mainpark Angry2 Fade",xzoom=-1.0)
image ichi Mainpark Dark = DynamicDisplayable(renpy.curry(charComposite)("ichi","dark","","","mainpark","",0,"","false",800,950))
image ichi Mainpark Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","dark","","","mainpark","",0,"","true",800,950))
image ichi Mainpark Dark Flip= Transform("ichi Mainpark Dark",xzoom=-1.0)
image ichi Mainpark Dark Fade Flip= Transform("ichi Mainpark Dark Fade",xzoom=-1.0)
image ichi Mainpark Blank = DynamicDisplayable(renpy.curry(charComposite)("ichi","blank","01","02","mainpark","",0,"","false",800,950))
image ichi Mainpark Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","blank","01","02","mainpark","",0,"","true",800,950))
image ichi Mainpark Blank Flip= Transform("ichi Mainpark Blank",xzoom=-1.0)
image ichi Mainpark Blank Fade Flip= Transform("ichi Mainpark Blank Fade",xzoom=-1.0)
image ichi Mainpark Displeased = DynamicDisplayable(renpy.curry(charComposite)("ichi","displeased","01","02","mainpark","",0,"","false",800,950))
image ichi Mainpark Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","displeased","01","02","mainpark","",0,"","true",800,950))
image ichi Mainpark Displeased Flip= Transform("ichi Mainpark Displeased",xzoom=-1.0)
image ichi Mainpark Displeased Fade Flip= Transform("ichi Mainpark Displeased Fade",xzoom=-1.0)
image ichi Mainpark Gasp = DynamicDisplayable(renpy.curry(charComposite)("ichi","gasp","01","02","mainpark","",0,"","false",800,950))
image ichi Mainpark Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","gasp","01","02","mainpark","",0,"","true",800,950))
image ichi Mainpark Gasp Flip= Transform("ichi Mainpark Gasp",xzoom=-1.0)
image ichi Mainpark Gasp Fade Flip= Transform("ichi Mainpark Gasp Fade",xzoom=-1.0)
image ichi Mainpark Happy1 = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","01","02","mainpark","",0,"","false",800,950))
image ichi Mainpark Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","01","02","mainpark","",0,"","true",800,950))
image ichi Mainpark Happy1 Flip= Transform("ichi Mainpark Happy1",xzoom=-1.0)
image ichi Mainpark Happy1 Fade Flip= Transform("ichi Mainpark Happy1 Fade",xzoom=-1.0)
image ichi Mainpark Happy2 = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","03","04","mainpark","",0,"","false",800,950))
image ichi Mainpark Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","03","04","mainpark","",0,"","true",800,950))
image ichi Mainpark Happy2 Flip= Transform("ichi Mainpark Happy2",xzoom=-1.0)
image ichi Mainpark Happy2 Fade Flip= Transform("ichi Mainpark Happy2 Fade",xzoom=-1.0)
image ichi Mainpark Nervous = DynamicDisplayable(renpy.curry(charComposite)("ichi","nervous","01","02","mainpark","",0,"","false",800,950))
image ichi Mainpark Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","nervous","01","02","mainpark","",0,"","true",800,950))
image ichi Mainpark Nervous Flip= Transform("ichi Mainpark Nervous",xzoom=-1.0)
image ichi Mainpark Nervous Fade Flip= Transform("ichi Mainpark Nervous Fade",xzoom=-1.0)
image ichi Mainpark Neutral = DynamicDisplayable(renpy.curry(charComposite)("ichi","neutral","01","02","mainpark","",0,"","false",800,950))
image ichi Mainpark Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","neutral","01","02","mainpark","",0,"","true",800,950))
image ichi Mainpark Neutral Flip= Transform("ichi Mainpark Neutral",xzoom=-1.0)
image ichi Mainpark Neutral Fade Flip= Transform("ichi Mainpark Neutral Fade",xzoom=-1.0)
image ichi Mainpark Shocked = DynamicDisplayable(renpy.curry(charComposite)("ichi","shocked","01","02","mainpark","",0,"","false",800,950))
image ichi Mainpark Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","shocked","01","02","mainpark","",0,"","true",800,950))
image ichi Mainpark Shocked Flip= Transform("ichi Mainpark Shocked",xzoom=-1.0)
image ichi Mainpark Shocked Fade Flip= Transform("ichi Mainpark Shocked Fade",xzoom=-1.0)
image ichi Mainpark Thinking = DynamicDisplayable(renpy.curry(charComposite)("ichi","thinking","01","02","mainpark","",0,"","false",800,950))
image ichi Mainpark Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","thinking","01","02","mainpark","",0,"","true",800,950))
image ichi Mainpark Thinking Flip= Transform("ichi Mainpark Thinking",xzoom=-1.0)
image ichi Mainpark Thinking Fade Flip= Transform("ichi Mainpark Thinking Fade",xzoom=-1.0)
image ichi Maintee Angry1 = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","01","02","maintee","",0,"","false",800,950))
image ichi Maintee Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","01","02","maintee","",0,"","true",800,950))
image ichi Maintee Angry1 Flip= Transform("ichi Maintee Angry1",xzoom=-1.0)
image ichi Maintee Angry1 Fade Flip= Transform("ichi Maintee Angry1 Fade",xzoom=-1.0)
image ichi Maintee Angry2 = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","03","04","maintee","",0,"","false",800,950))
image ichi Maintee Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","03","04","maintee","",0,"","true",800,950))
image ichi Maintee Angry2 Flip= Transform("ichi Maintee Angry2",xzoom=-1.0)
image ichi Maintee Angry2 Fade Flip= Transform("ichi Maintee Angry2 Fade",xzoom=-1.0)
image ichi Maintee Dark = DynamicDisplayable(renpy.curry(charComposite)("ichi","dark","","","maintee","",0,"","false",800,950))
image ichi Maintee Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","dark","","","maintee","",0,"","true",800,950))
image ichi Maintee Dark Flip= Transform("ichi Maintee Dark",xzoom=-1.0)
image ichi Maintee Dark Fade Flip= Transform("ichi Maintee Dark Fade",xzoom=-1.0)
image ichi Maintee Blank = DynamicDisplayable(renpy.curry(charComposite)("ichi","blank","01","02","maintee","",0,"","false",800,950))
image ichi Maintee Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","blank","01","02","maintee","",0,"","true",800,950))
image ichi Maintee Blank Flip= Transform("ichi Maintee Blank",xzoom=-1.0)
image ichi Maintee Blank Fade Flip= Transform("ichi Maintee Blank Fade",xzoom=-1.0)
image ichi Maintee Displeased = DynamicDisplayable(renpy.curry(charComposite)("ichi","displeased","01","02","maintee","",0,"","false",800,950))
image ichi Maintee Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","displeased","01","02","maintee","",0,"","true",800,950))
image ichi Maintee Displeased Flip= Transform("ichi Maintee Displeased",xzoom=-1.0)
image ichi Maintee Displeased Fade Flip= Transform("ichi Maintee Displeased Fade",xzoom=-1.0)
image ichi Maintee Gasp = DynamicDisplayable(renpy.curry(charComposite)("ichi","gasp","01","02","maintee","",0,"","false",800,950))
image ichi Maintee Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","gasp","01","02","maintee","",0,"","true",800,950))
image ichi Maintee Gasp Flip= Transform("ichi Maintee Gasp",xzoom=-1.0)
image ichi Maintee Gasp Fade Flip= Transform("ichi Maintee Gasp Fade",xzoom=-1.0)
image ichi Maintee Happy1 = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","01","02","maintee","",0,"","false",800,950))
image ichi Maintee Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","01","02","maintee","",0,"","true",800,950))
image ichi Maintee Happy1 Flip= Transform("ichi Maintee Happy1",xzoom=-1.0)
image ichi Maintee Happy1 Fade Flip= Transform("ichi Maintee Happy1 Fade",xzoom=-1.0)
image ichi Maintee Happy2 = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","03","04","maintee","",0,"","false",800,950))
image ichi Maintee Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","03","04","maintee","",0,"","true",800,950))
image ichi Maintee Happy2 Flip= Transform("ichi Maintee Happy2",xzoom=-1.0)
image ichi Maintee Happy2 Fade Flip= Transform("ichi Maintee Happy2 Fade",xzoom=-1.0)
image ichi Maintee Nervous = DynamicDisplayable(renpy.curry(charComposite)("ichi","nervous","01","02","maintee","",0,"","false",800,950))
image ichi Maintee Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","nervous","01","02","maintee","",0,"","true",800,950))
image ichi Maintee Nervous Flip= Transform("ichi Maintee Nervous",xzoom=-1.0)
image ichi Maintee Nervous Fade Flip= Transform("ichi Maintee Nervous Fade",xzoom=-1.0)
image ichi Maintee Neutral = DynamicDisplayable(renpy.curry(charComposite)("ichi","neutral","01","02","maintee","",0,"","false",800,950))
image ichi Maintee Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","neutral","01","02","maintee","",0,"","true",800,950))
image ichi Maintee Neutral Flip= Transform("ichi Maintee Neutral",xzoom=-1.0)
image ichi Maintee Neutral Fade Flip= Transform("ichi Maintee Neutral Fade",xzoom=-1.0)
image ichi Maintee Shocked = DynamicDisplayable(renpy.curry(charComposite)("ichi","shocked","01","02","maintee","",0,"","false",800,950))
image ichi Maintee Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","shocked","01","02","maintee","",0,"","true",800,950))
image ichi Maintee Shocked Flip= Transform("ichi Maintee Shocked",xzoom=-1.0)
image ichi Maintee Shocked Fade Flip= Transform("ichi Maintee Shocked Fade",xzoom=-1.0)
image ichi Maintee Thinking = DynamicDisplayable(renpy.curry(charComposite)("ichi","thinking","01","02","maintee","",0,"","false",800,950))
image ichi Maintee Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","thinking","01","02","maintee","",0,"","true",800,950))
image ichi Maintee Thinking Flip= Transform("ichi Maintee Thinking",xzoom=-1.0)
image ichi Maintee Thinking Fade Flip= Transform("ichi Maintee Thinking Fade",xzoom=-1.0)
image ichi PJ Angry1 = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","01","02","pj","",0,"","false",800,950))
image ichi PJ Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","01","02","pj","",0,"","true",800,950))
image ichi PJ Angry1 Flip= Transform("ichi PJ Angry1",xzoom=-1.0)
image ichi PJ Angry1 Fade Flip= Transform("ichi PJ Angry1 Fade",xzoom=-1.0)
image ichi PJ Angry2 = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","03","04","pj","",0,"","false",800,950))
image ichi PJ Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","03","04","pj","",0,"","true",800,950))
image ichi PJ Angry2 Flip= Transform("ichi PJ Angry2",xzoom=-1.0)
image ichi PJ Angry2 Fade Flip= Transform("ichi PJ Angry2 Fade",xzoom=-1.0)
image ichi PJ Dark = DynamicDisplayable(renpy.curry(charComposite)("ichi","dark","","","pj","",0,"","false",800,950))
image ichi PJ Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","dark","","","pj","",0,"","true",800,950))
image ichi PJ Dark Flip= Transform("ichi PJ Dark",xzoom=-1.0)
image ichi PJ Dark Fade Flip= Transform("ichi PJ Dark Fade",xzoom=-1.0)
image ichi PJ Blank = DynamicDisplayable(renpy.curry(charComposite)("ichi","blank","01","02","pj","",0,"","false",800,950))
image ichi PJ Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","blank","01","02","pj","",0,"","true",800,950))
image ichi PJ Blank Flip= Transform("ichi PJ Blank",xzoom=-1.0)
image ichi PJ Blank Fade Flip= Transform("ichi PJ Blank Fade",xzoom=-1.0)
image ichi PJ Displeased = DynamicDisplayable(renpy.curry(charComposite)("ichi","displeased","01","02","pj","",0,"","false",800,950))
image ichi PJ Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","displeased","01","02","pj","",0,"","true",800,950))
image ichi PJ Displeased Flip= Transform("ichi PJ Displeased",xzoom=-1.0)
image ichi PJ Displeased Fade Flip= Transform("ichi PJ Displeased Fade",xzoom=-1.0)
image ichi PJ Gasp = DynamicDisplayable(renpy.curry(charComposite)("ichi","gasp","01","02","pj","",0,"","false",800,950))
image ichi PJ Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","gasp","01","02","pj","",0,"","true",800,950))
image ichi PJ Gasp Flip= Transform("ichi PJ Gasp",xzoom=-1.0)
image ichi PJ Gasp Fade Flip= Transform("ichi PJ Gasp Fade",xzoom=-1.0)
image ichi PJ Happy1 = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","01","02","pj","",0,"","false",800,950))
image ichi PJ Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","01","02","pj","",0,"","true",800,950))
image ichi PJ Happy1 Flip= Transform("ichi PJ Happy1",xzoom=-1.0)
image ichi PJ Happy1 Fade Flip= Transform("ichi PJ Happy1 Fade",xzoom=-1.0)
image ichi PJ Happy2 = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","03","04","pj","",0,"","false",800,950))
image ichi PJ Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","03","04","pj","",0,"","true",800,950))
image ichi PJ Happy2 Flip= Transform("ichi PJ Happy2",xzoom=-1.0)
image ichi PJ Happy2 Fade Flip= Transform("ichi PJ Happy2 Fade",xzoom=-1.0)
image ichi PJ Nervous = DynamicDisplayable(renpy.curry(charComposite)("ichi","nervous","01","02","pj","",0,"","false",800,950))
image ichi PJ Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","nervous","01","02","pj","",0,"","true",800,950))
image ichi PJ Nervous Flip= Transform("ichi PJ Nervous",xzoom=-1.0)
image ichi PJ Nervous Fade Flip= Transform("ichi PJ Nervous Fade",xzoom=-1.0)
image ichi PJ Neutral = DynamicDisplayable(renpy.curry(charComposite)("ichi","neutral","01","02","pj","",0,"","false",800,950))
image ichi PJ Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","neutral","01","02","pj","",0,"","true",800,950))
image ichi PJ Neutral Flip= Transform("ichi PJ Neutral",xzoom=-1.0)
image ichi PJ Neutral Fade Flip= Transform("ichi PJ Neutral Fade",xzoom=-1.0)
image ichi PJ Shocked = DynamicDisplayable(renpy.curry(charComposite)("ichi","shocked","01","02","pj","",0,"","false",800,950))
image ichi PJ Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","shocked","01","02","pj","",0,"","true",800,950))
image ichi PJ Shocked Flip= Transform("ichi PJ Shocked",xzoom=-1.0)
image ichi PJ Shocked Fade Flip= Transform("ichi PJ Shocked Fade",xzoom=-1.0)
image ichi PJ Thinking = DynamicDisplayable(renpy.curry(charComposite)("ichi","thinking","01","02","pj","",0,"","false",800,950))
image ichi PJ Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","thinking","01","02","pj","",0,"","true",800,950))
image ichi PJ Thinking Flip= Transform("ichi PJ Thinking",xzoom=-1.0)
image ichi PJ Thinking Fade Flip= Transform("ichi PJ Thinking Fade",xzoom=-1.0)
image ichi SchoolS Angry1 = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","01","02","schools","",0,"","false",800,950))
image ichi SchoolS Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","01","02","schools","",0,"","true",800,950))
image ichi SchoolS Angry1 Flip= Transform("ichi SchoolS Angry1",xzoom=-1.0)
image ichi SchoolS Angry1 Fade Flip= Transform("ichi SchoolS Angry1 Fade",xzoom=-1.0)
image ichi SchoolS Angry2 = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","03","04","schools","",0,"","false",800,950))
image ichi SchoolS Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","03","04","schools","",0,"","true",800,950))
image ichi SchoolS Angry2 Flip= Transform("ichi SchoolS Angry2",xzoom=-1.0)
image ichi SchoolS Angry2 Fade Flip= Transform("ichi SchoolS Angry2 Fade",xzoom=-1.0)
image ichi SchoolS Dark = DynamicDisplayable(renpy.curry(charComposite)("ichi","dark","","","schools","",0,"","false",800,950))
image ichi SchoolS Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","dark","","","schools","",0,"","true",800,950))
image ichi SchoolS Dark Flip= Transform("ichi SchoolS Dark",xzoom=-1.0)
image ichi SchoolS Dark Fade Flip= Transform("ichi SchoolS Dark Fade",xzoom=-1.0)
image ichi SchoolS Blank = DynamicDisplayable(renpy.curry(charComposite)("ichi","blank","01","02","schools","",0,"","false",800,950))
image ichi SchoolS Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","blank","01","02","schools","",0,"","true",800,950))
image ichi SchoolS Blank Flip= Transform("ichi SchoolS Blank",xzoom=-1.0)
image ichi SchoolS Blank Fade Flip= Transform("ichi SchoolS Blank Fade",xzoom=-1.0)
image ichi SchoolS Displeased = DynamicDisplayable(renpy.curry(charComposite)("ichi","displeased","01","02","schools","",0,"","false",800,950))
image ichi SchoolS Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","displeased","01","02","schools","",0,"","true",800,950))
image ichi SchoolS Displeased Flip= Transform("ichi SchoolS Displeased",xzoom=-1.0)
image ichi SchoolS Displeased Fade Flip= Transform("ichi SchoolS Displeased Fade",xzoom=-1.0)
image ichi SchoolS Gasp = DynamicDisplayable(renpy.curry(charComposite)("ichi","gasp","01","02","schools","",0,"","false",800,950))
image ichi SchoolS Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","gasp","01","02","schools","",0,"","true",800,950))
image ichi SchoolS Gasp Flip= Transform("ichi SchoolS Gasp",xzoom=-1.0)
image ichi SchoolS Gasp Fade Flip= Transform("ichi SchoolS Gasp Fade",xzoom=-1.0)
image ichi SchoolS Happy1 = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","01","02","schools","",0,"","false",800,950))
image ichi SchoolS Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","01","02","schools","",0,"","true",800,950))
image ichi SchoolS Happy1 Flip= Transform("ichi SchoolS Happy1",xzoom=-1.0)
image ichi SchoolS Happy1 Fade Flip= Transform("ichi SchoolS Happy1 Fade",xzoom=-1.0)
image ichi SchoolS Happy2 = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","03","04","schools","",0,"","false",800,950))
image ichi SchoolS Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","03","04","schools","",0,"","true",800,950))
image ichi SchoolS Happy2 Flip= Transform("ichi SchoolS Happy2",xzoom=-1.0)
image ichi SchoolS Happy2 Fade Flip= Transform("ichi SchoolS Happy2 Fade",xzoom=-1.0)
image ichi SchoolS Nervous = DynamicDisplayable(renpy.curry(charComposite)("ichi","nervous","01","02","schools","",0,"","false",800,950))
image ichi SchoolS Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","nervous","01","02","schools","",0,"","true",800,950))
image ichi SchoolS Nervous Flip= Transform("ichi SchoolS Nervous",xzoom=-1.0)
image ichi SchoolS Nervous Fade Flip= Transform("ichi SchoolS Nervous Fade",xzoom=-1.0)
image ichi SchoolS Neutral = DynamicDisplayable(renpy.curry(charComposite)("ichi","neutral","01","02","schools","",0,"","false",800,950))
image ichi SchoolS Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","neutral","01","02","schools","",0,"","true",800,950))
image ichi SchoolS Neutral Flip= Transform("ichi SchoolS Neutral",xzoom=-1.0)
image ichi SchoolS Neutral Fade Flip= Transform("ichi SchoolS Neutral Fade",xzoom=-1.0)
image ichi SchoolS Shocked = DynamicDisplayable(renpy.curry(charComposite)("ichi","shocked","01","02","schools","",0,"","false",800,950))
image ichi SchoolS Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","shocked","01","02","schools","",0,"","true",800,950))
image ichi SchoolS Shocked Flip= Transform("ichi SchoolS Shocked",xzoom=-1.0)
image ichi SchoolS Shocked Fade Flip= Transform("ichi SchoolS Shocked Fade",xzoom=-1.0)
image ichi SchoolS Thinking = DynamicDisplayable(renpy.curry(charComposite)("ichi","thinking","01","02","schools","",0,"","false",800,950))
image ichi SchoolS Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","thinking","01","02","schools","",0,"","true",800,950))
image ichi SchoolS Thinking Flip= Transform("ichi SchoolS Thinking",xzoom=-1.0)
image ichi SchoolS Thinking Fade Flip= Transform("ichi SchoolS Thinking Fade",xzoom=-1.0)
image ichi SchoolW Angry1 = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","01","02","schoolw","",0,"","false",800,950))
image ichi SchoolW Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","01","02","schoolw","",0,"","true",800,950))
image ichi SchoolW Angry1 Flip= Transform("ichi SchoolW Angry1",xzoom=-1.0)
image ichi SchoolW Angry1 Fade Flip= Transform("ichi SchoolW Angry1 Fade",xzoom=-1.0)
image ichi SchoolW Angry2 = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","03","04","schoolw","",0,"","false",800,950))
image ichi SchoolW Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","03","04","schoolw","",0,"","true",800,950))
image ichi SchoolW Angry2 Flip= Transform("ichi SchoolW Angry2",xzoom=-1.0)
image ichi SchoolW Angry2 Fade Flip= Transform("ichi SchoolW Angry2 Fade",xzoom=-1.0)
image ichi SchoolW Dark = DynamicDisplayable(renpy.curry(charComposite)("ichi","dark","","","schoolw","",0,"","false",800,950))
image ichi SchoolW Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","dark","","","schoolw","",0,"","true",800,950))
image ichi SchoolW Dark Flip= Transform("ichi SchoolW Dark",xzoom=-1.0)
image ichi SchoolW Dark Fade Flip= Transform("ichi SchoolW Dark Fade",xzoom=-1.0)
image ichi SchoolW Blank = DynamicDisplayable(renpy.curry(charComposite)("ichi","blank","01","02","schoolw","",0,"","false",800,950))
image ichi SchoolW Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","blank","01","02","schoolw","",0,"","true",800,950))
image ichi SchoolW Blank Flip= Transform("ichi SchoolW Blank",xzoom=-1.0)
image ichi SchoolW Blank Fade Flip= Transform("ichi SchoolW Blank Fade",xzoom=-1.0)
image ichi SchoolW Displeased = DynamicDisplayable(renpy.curry(charComposite)("ichi","displeased","01","02","schoolw","",0,"","false",800,950))
image ichi SchoolW Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","displeased","01","02","schoolw","",0,"","true",800,950))
image ichi SchoolW Displeased Flip= Transform("ichi SchoolW Displeased",xzoom=-1.0)
image ichi SchoolW Displeased Fade Flip= Transform("ichi SchoolW Displeased Fade",xzoom=-1.0)
image ichi SchoolW Gasp = DynamicDisplayable(renpy.curry(charComposite)("ichi","gasp","01","02","schoolw","",0,"","false",800,950))
image ichi SchoolW Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","gasp","01","02","schoolw","",0,"","true",800,950))
image ichi SchoolW Gasp Flip= Transform("ichi SchoolW Gasp",xzoom=-1.0)
image ichi SchoolW Gasp Fade Flip= Transform("ichi SchoolW Gasp Fade",xzoom=-1.0)
image ichi SchoolW Happy1 = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","01","02","schoolw","",0,"","false",800,950))
image ichi SchoolW Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","01","02","schoolw","",0,"","true",800,950))
image ichi SchoolW Happy1 Flip= Transform("ichi SchoolW Happy1",xzoom=-1.0)
image ichi SchoolW Happy1 Fade Flip= Transform("ichi SchoolW Happy1 Fade",xzoom=-1.0)
image ichi SchoolW Happy2 = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","03","04","schoolw","",0,"","false",800,950))
image ichi SchoolW Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","03","04","schoolw","",0,"","true",800,950))
image ichi SchoolW Happy2 Flip= Transform("ichi SchoolW Happy2",xzoom=-1.0)
image ichi SchoolW Happy2 Fade Flip= Transform("ichi SchoolW Happy2 Fade",xzoom=-1.0)
image ichi SchoolW Nervous = DynamicDisplayable(renpy.curry(charComposite)("ichi","nervous","01","02","schoolw","",0,"","false",800,950))
image ichi SchoolW Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","nervous","01","02","schoolw","",0,"","true",800,950))
image ichi SchoolW Nervous Flip= Transform("ichi SchoolW Nervous",xzoom=-1.0)
image ichi SchoolW Nervous Fade Flip= Transform("ichi SchoolW Nervous Fade",xzoom=-1.0)
image ichi SchoolW Neutral = DynamicDisplayable(renpy.curry(charComposite)("ichi","neutral","01","02","schoolw","",0,"","false",800,950))
image ichi SchoolW Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","neutral","01","02","schoolw","",0,"","true",800,950))
image ichi SchoolW Neutral Flip= Transform("ichi SchoolW Neutral",xzoom=-1.0)
image ichi SchoolW Neutral Fade Flip= Transform("ichi SchoolW Neutral Fade",xzoom=-1.0)
image ichi SchoolW Shocked = DynamicDisplayable(renpy.curry(charComposite)("ichi","shocked","01","02","schoolw","",0,"","false",800,950))
image ichi SchoolW Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","shocked","01","02","schoolw","",0,"","true",800,950))
image ichi SchoolW Shocked Flip= Transform("ichi SchoolW Shocked",xzoom=-1.0)
image ichi SchoolW Shocked Fade Flip= Transform("ichi SchoolW Shocked Fade",xzoom=-1.0)
image ichi SchoolW Thinking = DynamicDisplayable(renpy.curry(charComposite)("ichi","thinking","01","02","schoolw","",0,"","false",800,950))
image ichi SchoolW Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","thinking","01","02","schoolw","",0,"","true",800,950))
image ichi SchoolW Thinking Flip= Transform("ichi SchoolW Thinking",xzoom=-1.0)
image ichi SchoolW Thinking Fade Flip= Transform("ichi SchoolW Thinking Fade",xzoom=-1.0)
image ichi Naked Angry1 = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","01","02","naked","",0,"","false",800,950))
image ichi Naked Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","01","02","naked","",0,"","true",800,950))
image ichi Naked Angry1 Flip= Transform("ichi Naked Angry1",xzoom=-1.0)
image ichi Naked Angry1 Fade Flip= Transform("ichi Naked Angry1 Fade",xzoom=-1.0)
image ichi Naked Angry2 = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","03","04","naked","",0,"","false",800,950))
image ichi Naked Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","angry","03","04","naked","",0,"","true",800,950))
image ichi Naked Angry2 Flip= Transform("ichi Naked Angry2",xzoom=-1.0)
image ichi Naked Angry2 Fade Flip= Transform("ichi Naked Angry2 Fade",xzoom=-1.0)
image ichi Naked Dark = DynamicDisplayable(renpy.curry(charComposite)("ichi","dark","","","naked","",0,"","false",800,950))
image ichi Naked Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","dark","","","naked","",0,"","true",800,950))
image ichi Naked Dark Flip= Transform("ichi Naked Dark",xzoom=-1.0)
image ichi Naked Dark Fade Flip= Transform("ichi Naked Dark Fade",xzoom=-1.0)
image ichi Naked Blank = DynamicDisplayable(renpy.curry(charComposite)("ichi","blank","01","02","naked","",0,"","false",800,950))
image ichi Naked Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","blank","01","02","naked","",0,"","true",800,950))
image ichi Naked Blank Flip= Transform("ichi Naked Blank",xzoom=-1.0)
image ichi Naked Blank Fade Flip= Transform("ichi Naked Blank Fade",xzoom=-1.0)
image ichi Naked Displeased = DynamicDisplayable(renpy.curry(charComposite)("ichi","displeased","01","02","naked","",0,"","false",800,950))
image ichi Naked Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","displeased","01","02","naked","",0,"","true",800,950))
image ichi Naked Displeased Flip= Transform("ichi Naked Displeased",xzoom=-1.0)
image ichi Naked Displeased Fade Flip= Transform("ichi Naked Displeased Fade",xzoom=-1.0)
image ichi Naked Gasp = DynamicDisplayable(renpy.curry(charComposite)("ichi","gasp","01","02","naked","",0,"","false",800,950))
image ichi Naked Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","gasp","01","02","naked","",0,"","true",800,950))
image ichi Naked Gasp Flip= Transform("ichi Naked Gasp",xzoom=-1.0)
image ichi Naked Gasp Fade Flip= Transform("ichi Naked Gasp Fade",xzoom=-1.0)
image ichi Naked Happy1 = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","01","02","naked","",0,"","false",800,950))
image ichi Naked Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","01","02","naked","",0,"","true",800,950))
image ichi Naked Happy1 Flip= Transform("ichi Naked Happy1",xzoom=-1.0)
image ichi Naked Happy1 Fade Flip= Transform("ichi Naked Happy1 Fade",xzoom=-1.0)
image ichi Naked Happy2 = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","03","04","naked","",0,"","false",800,950))
image ichi Naked Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","happy","03","04","naked","",0,"","true",800,950))
image ichi Naked Happy2 Flip= Transform("ichi Naked Happy2",xzoom=-1.0)
image ichi Naked Happy2 Fade Flip= Transform("ichi Naked Happy2 Fade",xzoom=-1.0)
image ichi Naked Nervous = DynamicDisplayable(renpy.curry(charComposite)("ichi","nervous","01","02","naked","",0,"","false",800,950))
image ichi Naked Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","nervous","01","02","naked","",0,"","true",800,950))
image ichi Naked Nervous Flip= Transform("ichi Naked Nervous",xzoom=-1.0)
image ichi Naked Nervous Fade Flip= Transform("ichi Naked Nervous Fade",xzoom=-1.0)
image ichi Naked Neutral = DynamicDisplayable(renpy.curry(charComposite)("ichi","neutral","01","02","naked","",0,"","false",800,950))
image ichi Naked Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","neutral","01","02","naked","",0,"","true",800,950))
image ichi Naked Neutral Flip= Transform("ichi Naked Neutral",xzoom=-1.0)
image ichi Naked Neutral Fade Flip= Transform("ichi Naked Neutral Fade",xzoom=-1.0)
image ichi Naked Shocked = DynamicDisplayable(renpy.curry(charComposite)("ichi","shocked","01","02","naked","",0,"","false",800,950))
image ichi Naked Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","shocked","01","02","naked","",0,"","true",800,950))
image ichi Naked Shocked Flip= Transform("ichi Naked Shocked",xzoom=-1.0)
image ichi Naked Shocked Fade Flip= Transform("ichi Naked Shocked Fade",xzoom=-1.0)
image ichi Naked Thinking = DynamicDisplayable(renpy.curry(charComposite)("ichi","thinking","01","02","naked","",0,"","false",800,950))
image ichi Naked Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("ichi","thinking","01","02","naked","",0,"","true",800,950))
image ichi Naked Thinking Flip= Transform("ichi Naked Thinking",xzoom=-1.0)
image ichi Naked Thinking Fade Flip= Transform("ichi Naked Thinking Fade",xzoom=-1.0)