# COMMENTS:
#
# Images are named like this:
# chara Clothes Expression Fade Flip
# Add Fade/Flip when needed
#
# Jyushimatsu has the following clothes:
# SchoolS SchoolW Bathrobe Bathtowel MainPark Naked Pj Sera
#
# Jyushimatsu has the following expressions:
# Neutral Blank
#
# Adding New Images:
# Use the same naming convention, copy paste the right code per commented section.
# The numbers are for head animation, for expressions such as dark, leave it as "" if it has no number behind.
# Remember every image needs normal, flip, fade, flip fade.
# Every new outfit also needs all the expressions (just in case)

#Jyushimatsu Images
image jyushi Bathrobe Angry = DynamicDisplayable(renpy.curry(charComposite)("jyushi","angry","01","02","bathrobe","",0,"","false",800,950))
image jyushi Bathrobe Angry Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","angry","01","02","bathrobe","",0,"","true",800,950))
image jyushi Bathrobe Angry Flip= Transform("jyushi Bathrobe Angry",xzoom=-1.0)
image jyushi Bathrobe Angry Fade Flip= Transform("jyushi Bathrobe Angry Fade",xzoom=-1.0)
image jyushi Bathrobe Dark = DynamicDisplayable(renpy.curry(charComposite)("jyushi","dark","","","bathrobe","",0,"","false",800,950))
image jyushi Bathrobe Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","dark","","","bathrobe","",0,"","true",800,950))
image jyushi Bathrobe Dark Flip= Transform("jyushi Bathrobe Dark",xzoom=-1.0)
image jyushi Bathrobe Dark Fade Flip= Transform("jyushi Bathrobe Dark Fade",xzoom=-1.0)
image jyushi Bathrobe Blank = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blank","01","02","bathrobe","",0,"","false",800,950))
image jyushi Bathrobe Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blank","01","02","bathrobe","",0,"","true",800,950))
image jyushi Bathrobe Blank Flip= Transform("jyushi Bathrobe Blank",xzoom=-1.0)
image jyushi Bathrobe Blank Fade Flip= Transform("jyushi Bathrobe Blank Fade",xzoom=-1.0)
image jyushi Bathrobe Blush = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blush","01","02","bathrobe","",0,"","false",800,950))
image jyushi Bathrobe Blush Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blush","01","02","bathrobe","",0,"","true",800,950))
image jyushi Bathrobe Blush Flip= Transform("jyushi Bathrobe Blush",xzoom=-1.0)
image jyushi Bathrobe Blush Fade Flip= Transform("jyushi Bathrobe Blush Fade",xzoom=-1.0)
image jyushi Bathrobe Displeased = DynamicDisplayable(renpy.curry(charComposite)("jyushi","displeased","01","02","bathrobe","",0,"","false",800,950))
image jyushi Bathrobe Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","displeased","01","02","bathrobe","",0,"","true",800,950))
image jyushi Bathrobe Displeased Flip= Transform("jyushi Bathrobe Displeased",xzoom=-1.0)
image jyushi Bathrobe Displeased Fade Flip= Transform("jyushi Bathrobe Displeased Fade",xzoom=-1.0)
image jyushi Bathrobe Gasp = DynamicDisplayable(renpy.curry(charComposite)("jyushi","gasp","01","02","bathrobe","",0,"","false",800,950))
image jyushi Bathrobe Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","gasp","01","02","bathrobe","",0,"","true",800,950))
image jyushi Bathrobe Gasp Flip= Transform("jyushi Bathrobe Gasp",xzoom=-1.0)
image jyushi Bathrobe Gasp Fade Flip= Transform("jyushi Bathrobe Gasp Fade",xzoom=-1.0)
image jyushi Bathrobe Happy = DynamicDisplayable(renpy.curry(charComposite)("jyushi","happy","","","bathrobe","",0,"","false",800,950))
image jyushi Bathrobe Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","happy","","","bathrobe","",0,"","true",800,950))
image jyushi Bathrobe Happy Flip= Transform("jyushi Bathrobe Happy",xzoom=-1.0)
image jyushi Bathrobe Happy Fade Flip= Transform("jyushi Bathrobe Happy Fade",xzoom=-1.0)
image jyushi Bathrobe Nervous = DynamicDisplayable(renpy.curry(charComposite)("jyushi","nervous","01","02","bathrobe","",0,"","false",800,950))
image jyushi Bathrobe Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","nervous","01","02","bathrobe","",0,"","true",800,950))
image jyushi Bathrobe Nervous Flip= Transform("jyushi Bathrobe Nervous",xzoom=-1.0)
image jyushi Bathrobe Nervous Fade Flip= Transform("jyushi Bathrobe Nervous Fade",xzoom=-1.0)
image jyushi Bathrobe Neutral = DynamicDisplayable(renpy.curry(charComposite)("jyushi","neutral","01","02","bathrobe","",0,"","false",800,950))
image jyushi Bathrobe Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","neutral","01","02","bathrobe","",0,"","true",800,950))
image jyushi Bathrobe Neutral Flip= Transform("jyushi Bathrobe Neutral",xzoom=-1.0)
image jyushi Bathrobe Neutral Fade Flip= Transform("jyushi Bathrobe Neutral Fade",xzoom=-1.0)
image jyushi Bathrobe Shocked = DynamicDisplayable(renpy.curry(charComposite)("jyushi","shocked","01","02","bathrobe","",0,"","false",800,950))
image jyushi Bathrobe Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","shocked","01","02","bathrobe","",0,"","true",800,950))
image jyushi Bathrobe Shocked Flip= Transform("jyushi Bathrobe Shocked",xzoom=-1.0)
image jyushi Bathrobe Shocked Fade Flip= Transform("jyushi Bathrobe Shocked Fade",xzoom=-1.0)
image jyushi Bathrobe Thinking = DynamicDisplayable(renpy.curry(charComposite)("jyushi","thinking","01","02","bathrobe","",0,"","false",800,950))
image jyushi Bathrobe Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","thinking","01","02","bathrobe","",0,"","true",800,950))
image jyushi Bathrobe Thinking Flip= Transform("jyushi Bathrobe Thinking",xzoom=-1.0)
image jyushi Bathrobe Thinking Fade Flip= Transform("jyushi Bathrobe Thinking Fade",xzoom=-1.0)
image jyushi Casual Angry = DynamicDisplayable(renpy.curry(charComposite)("jyushi","angry","01","02","casual","",0,"","false",800,950))
image jyushi Casual Angry Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","angry","01","02","casual","",0,"","true",800,950))
image jyushi Casual Angry Flip= Transform("jyushi Casual Angry",xzoom=-1.0)
image jyushi Casual Angry Fade Flip= Transform("jyushi Casual Angry Fade",xzoom=-1.0)
image jyushi Casual Dark = DynamicDisplayable(renpy.curry(charComposite)("jyushi","dark","","","casual","",0,"","false",800,950))
image jyushi Casual Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","dark","","","casual","",0,"","true",800,950))
image jyushi Casual Dark Flip= Transform("jyushi Casual Dark",xzoom=-1.0)
image jyushi Casual Dark Fade Flip= Transform("jyushi Casual Dark Fade",xzoom=-1.0)
image jyushi Casual Blank = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blank","01","02","casual","",0,"","false",800,950))
image jyushi Casual Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blank","01","02","casual","",0,"","true",800,950))
image jyushi Casual Blank Flip= Transform("jyushi Casual Blank",xzoom=-1.0)
image jyushi Casual Blank Fade Flip= Transform("jyushi Casual Blank Fade",xzoom=-1.0)
image jyushi Casual Blush = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blush","01","02","casual","",0,"","false",800,950))
image jyushi Casual Blush Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blush","01","02","casual","",0,"","true",800,950))
image jyushi Casual Blush Flip= Transform("jyushi Casual Blush",xzoom=-1.0)
image jyushi Casual Blush Fade Flip= Transform("jyushi Casual Blush Fade",xzoom=-1.0)
image jyushi Casual Displeased = DynamicDisplayable(renpy.curry(charComposite)("jyushi","displeased","01","02","casual","",0,"","false",800,950))
image jyushi Casual Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","displeased","01","02","casual","",0,"","true",800,950))
image jyushi Casual Displeased Flip= Transform("jyushi Casual Displeased",xzoom=-1.0)
image jyushi Casual Displeased Fade Flip= Transform("jyushi Casual Displeased Fade",xzoom=-1.0)
image jyushi Casual Gasp = DynamicDisplayable(renpy.curry(charComposite)("jyushi","gasp","01","02","casual","",0,"","false",800,950))
image jyushi Casual Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","gasp","01","02","casual","",0,"","true",800,950))
image jyushi Casual Gasp Flip= Transform("jyushi Casual Gasp",xzoom=-1.0)
image jyushi Casual Gasp Fade Flip= Transform("jyushi Casual Gasp Fade",xzoom=-1.0)
image jyushi Casual Happy = DynamicDisplayable(renpy.curry(charComposite)("jyushi","happy","","","casual","",0,"","false",800,950))
image jyushi Casual Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","happy","","","casual","",0,"","true",800,950))
image jyushi Casual Happy Flip= Transform("jyushi Casual Happy",xzoom=-1.0)
image jyushi Casual Happy Fade Flip= Transform("jyushi Casual Happy Fade",xzoom=-1.0)
image jyushi Casual Nervous = DynamicDisplayable(renpy.curry(charComposite)("jyushi","nervous","01","02","casual","",0,"","false",800,950))
image jyushi Casual Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","nervous","01","02","casual","",0,"","true",800,950))
image jyushi Casual Nervous Flip= Transform("jyushi Casual Nervous",xzoom=-1.0)
image jyushi Casual Nervous Fade Flip= Transform("jyushi Casual Nervous Fade",xzoom=-1.0)
image jyushi Casual Neutral = DynamicDisplayable(renpy.curry(charComposite)("jyushi","neutral","01","02","casual","",0,"","false",800,950))
image jyushi Casual Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","neutral","01","02","casual","",0,"","true",800,950))
image jyushi Casual Neutral Flip= Transform("jyushi Casual Neutral",xzoom=-1.0)
image jyushi Casual Neutral Fade Flip= Transform("jyushi Casual Neutral Fade",xzoom=-1.0)
image jyushi Casual Shocked = DynamicDisplayable(renpy.curry(charComposite)("jyushi","shocked","01","02","casual","",0,"","false",800,950))
image jyushi Casual Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","shocked","01","02","casual","",0,"","true",800,950))
image jyushi Casual Shocked Flip= Transform("jyushi Casual Shocked",xzoom=-1.0)
image jyushi Casual Shocked Fade Flip= Transform("jyushi Casual Shocked Fade",xzoom=-1.0)
image jyushi Casual Thinking = DynamicDisplayable(renpy.curry(charComposite)("jyushi","thinking","01","02","casual","",0,"","false",800,950))
image jyushi Casual Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","thinking","01","02","casual","",0,"","true",800,950))
image jyushi Casual Thinking Flip= Transform("jyushi Casual Thinking",xzoom=-1.0)
image jyushi Casual Thinking Fade Flip= Transform("jyushi Casual Thinking Fade",xzoom=-1.0)
image jyushi Mainpark Angry = DynamicDisplayable(renpy.curry(charComposite)("jyushi","angry","01","02","mainpark","",0,"","false",800,950))
image jyushi Mainpark Angry Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","angry","01","02","mainpark","",0,"","true",800,950))
image jyushi Mainpark Angry Flip= Transform("jyushi Mainpark Angry",xzoom=-1.0)
image jyushi Mainpark Angry Fade Flip= Transform("jyushi Mainpark Angry Fade",xzoom=-1.0)
image jyushi Mainpark Dark = DynamicDisplayable(renpy.curry(charComposite)("jyushi","dark","","","mainpark","",0,"","false",800,950))
image jyushi Mainpark Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","dark","","","mainpark","",0,"","true",800,950))
image jyushi Mainpark Dark Flip= Transform("jyushi Mainpark Dark",xzoom=-1.0)
image jyushi Mainpark Dark Fade Flip= Transform("jyushi Mainpark Dark Fade",xzoom=-1.0)
image jyushi Mainpark Blank = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blank","01","02","mainpark","",0,"","false",800,950))
image jyushi Mainpark Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blank","01","02","mainpark","",0,"","true",800,950))
image jyushi Mainpark Blank Flip= Transform("jyushi Mainpark Blank",xzoom=-1.0)
image jyushi Mainpark Blank Fade Flip= Transform("jyushi Mainpark Blank Fade",xzoom=-1.0)
image jyushi Mainpark Blush = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blush","01","02","mainpark","",0,"","false",800,950))
image jyushi Mainpark Blush Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blush","01","02","mainpark","",0,"","true",800,950))
image jyushi Mainpark Blush Flip= Transform("jyushi Mainpark Blush",xzoom=-1.0)
image jyushi Mainpark Blush Fade Flip= Transform("jyushi Mainpark Blush Fade",xzoom=-1.0)
image jyushi Mainpark Displeased = DynamicDisplayable(renpy.curry(charComposite)("jyushi","displeased","01","02","mainpark","",0,"","false",800,950))
image jyushi Mainpark Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","displeased","01","02","mainpark","",0,"","true",800,950))
image jyushi Mainpark Displeased Flip= Transform("jyushi Mainpark Displeased",xzoom=-1.0)
image jyushi Mainpark Displeased Fade Flip= Transform("jyushi Mainpark Displeased Fade",xzoom=-1.0)
image jyushi Mainpark Gasp = DynamicDisplayable(renpy.curry(charComposite)("jyushi","gasp","01","02","mainpark","",0,"","false",800,950))
image jyushi Mainpark Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","gasp","01","02","mainpark","",0,"","true",800,950))
image jyushi Mainpark Gasp Flip= Transform("jyushi Mainpark Gasp",xzoom=-1.0)
image jyushi Mainpark Gasp Fade Flip= Transform("jyushi Mainpark Gasp Fade",xzoom=-1.0)
image jyushi Mainpark Happy = DynamicDisplayable(renpy.curry(charComposite)("jyushi","happy","","","mainpark","",0,"","false",800,950))
image jyushi Mainpark Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","happy","","","mainpark","",0,"","true",800,950))
image jyushi Mainpark Happy Flip= Transform("jyushi Mainpark Happy",xzoom=-1.0)
image jyushi Mainpark Happy Fade Flip= Transform("jyushi Mainpark Happy Fade",xzoom=-1.0)
image jyushi Mainpark Nervous = DynamicDisplayable(renpy.curry(charComposite)("jyushi","nervous","01","02","mainpark","",0,"","false",800,950))
image jyushi Mainpark Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","nervous","01","02","mainpark","",0,"","true",800,950))
image jyushi Mainpark Nervous Flip= Transform("jyushi Mainpark Nervous",xzoom=-1.0)
image jyushi Mainpark Nervous Fade Flip= Transform("jyushi Mainpark Nervous Fade",xzoom=-1.0)
image jyushi Mainpark Neutral = DynamicDisplayable(renpy.curry(charComposite)("jyushi","neutral","01","02","mainpark","",0,"","false",800,950))
image jyushi Mainpark Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","neutral","01","02","mainpark","",0,"","true",800,950))
image jyushi Mainpark Neutral Flip= Transform("jyushi Mainpark Neutral",xzoom=-1.0)
image jyushi Mainpark Neutral Fade Flip= Transform("jyushi Mainpark Neutral Fade",xzoom=-1.0)
image jyushi Mainpark Shocked = DynamicDisplayable(renpy.curry(charComposite)("jyushi","shocked","01","02","mainpark","",0,"","false",800,950))
image jyushi Mainpark Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","shocked","01","02","mainpark","",0,"","true",800,950))
image jyushi Mainpark Shocked Flip= Transform("jyushi Mainpark Shocked",xzoom=-1.0)
image jyushi Mainpark Shocked Fade Flip= Transform("jyushi Mainpark Shocked Fade",xzoom=-1.0)
image jyushi Mainpark Thinking = DynamicDisplayable(renpy.curry(charComposite)("jyushi","thinking","01","02","mainpark","",0,"","false",800,950))
image jyushi Mainpark Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","thinking","01","02","mainpark","",0,"","true",800,950))
image jyushi Mainpark Thinking Flip= Transform("jyushi Mainpark Thinking",xzoom=-1.0)
image jyushi Mainpark Thinking Fade Flip= Transform("jyushi Mainpark Thinking Fade",xzoom=-1.0)
image jyushi Maintee Angry = DynamicDisplayable(renpy.curry(charComposite)("jyushi","angry","01","02","maintee","","","","","",0,"","false",800,950))
image jyushi Maintee Angry Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","angry","01","02","maintee","","","","","",0,"","true",800,950))
image jyushi Maintee Angry Flip= Transform("jyushi Maintee Angry",xzoom=-1.0)
image jyushi Maintee Angry Fade Flip= Transform("jyushi Maintee Angry Fade",xzoom=-1.0)
image jyushi Maintee Dark = DynamicDisplayable(renpy.curry(charComposite)("jyushi","dark","","","maintee","","","","","",0,"","false",800,950))
image jyushi Maintee Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","dark","","","maintee","","","","","",0,"","true",800,950))
image jyushi Maintee Dark Flip= Transform("jyushi Maintee Dark",xzoom=-1.0)
image jyushi Maintee Dark Fade Flip= Transform("jyushi Maintee Dark Fade",xzoom=-1.0)
image jyushi Maintee Blank = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blank","01","02","maintee","","","","","",0,"","false",800,950))
image jyushi Maintee Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blank","01","02","maintee","","","","","",0,"","true",800,950))
image jyushi Maintee Blank Flip= Transform("jyushi Maintee Blank",xzoom=-1.0)
image jyushi Maintee Blank Fade Flip= Transform("jyushi Maintee Blank Fade",xzoom=-1.0)
image jyushi Maintee Blush = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blush","01","02","maintee","","","","","",0,"","false",800,950))
image jyushi Maintee Blush Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blush","01","02","maintee","","","","","",0,"","true",800,950))
image jyushi Maintee Blush Flip= Transform("jyushi Maintee Blush",xzoom=-1.0)
image jyushi Maintee Blush Fade Flip= Transform("jyushi Maintee Blush Fade",xzoom=-1.0)
image jyushi Maintee Displeased = DynamicDisplayable(renpy.curry(charComposite)("jyushi","displeased","01","02","maintee","","","","","",0,"","false",800,950))
image jyushi Maintee Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","displeased","01","02","maintee","","","","","",0,"","true",800,950))
image jyushi Maintee Displeased Flip= Transform("jyushi Maintee Displeased",xzoom=-1.0)
image jyushi Maintee Displeased Fade Flip= Transform("jyushi Maintee Displeased Fade",xzoom=-1.0)
image jyushi Maintee Gasp = DynamicDisplayable(renpy.curry(charComposite)("jyushi","gasp","01","02","maintee","","","","","",0,"","false",800,950))
image jyushi Maintee Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","gasp","01","02","maintee","","","","","",0,"","true",800,950))
image jyushi Maintee Gasp Flip= Transform("jyushi Maintee Gasp",xzoom=-1.0)
image jyushi Maintee Gasp Fade Flip= Transform("jyushi Maintee Gasp Fade",xzoom=-1.0)
image jyushi Maintee Happy = DynamicDisplayable(renpy.curry(charComposite)("jyushi","happy","","","maintee","","","","","",0,"","false",800,950))
image jyushi Maintee Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","happy","","","maintee","","","","","",0,"","true",800,950))
image jyushi Maintee Happy Flip= Transform("jyushi Maintee Happy",xzoom=-1.0)
image jyushi Maintee Happy Fade Flip= Transform("jyushi Maintee Happy Fade",xzoom=-1.0)
image jyushi Maintee Nervous = DynamicDisplayable(renpy.curry(charComposite)("jyushi","nervous","01","02","maintee","","","","","",0,"","false",800,950))
image jyushi Maintee Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","nervous","01","02","maintee","","","","","",0,"","true",800,950))
image jyushi Maintee Nervous Flip= Transform("jyushi Maintee Nervous",xzoom=-1.0)
image jyushi Maintee Nervous Fade Flip= Transform("jyushi Maintee Nervous Fade",xzoom=-1.0)
image jyushi Maintee Neutral = DynamicDisplayable(renpy.curry(charComposite)("jyushi","neutral","01","02","maintee","","","","","",0,"","false",800,950))
image jyushi Maintee Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","neutral","01","02","maintee","","","","","",0,"","true",800,950))
image jyushi Maintee Neutral Flip= Transform("jyushi Maintee Neutral",xzoom=-1.0)
image jyushi Maintee Neutral Fade Flip= Transform("jyushi Maintee Neutral Fade",xzoom=-1.0)
image jyushi Maintee Shocked = DynamicDisplayable(renpy.curry(charComposite)("jyushi","shocked","01","02","maintee","","","","","",0,"","false",800,950))
image jyushi Maintee Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","shocked","01","02","maintee","","","","","",0,"","true",800,950))
image jyushi Maintee Shocked Flip= Transform("jyushi Maintee Shocked",xzoom=-1.0)
image jyushi Maintee Shocked Fade Flip= Transform("jyushi Maintee Shocked Fade",xzoom=-1.0)
image jyushi Maintee Thinking = DynamicDisplayable(renpy.curry(charComposite)("jyushi","thinking","01","02","maintee","","","","","",0,"","false",800,950))
image jyushi Maintee Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","thinking","01","02","maintee","","","","","",0,"","true",800,950))
image jyushi Maintee Thinking Flip= Transform("jyushi Maintee Thinking",xzoom=-1.0)
image jyushi Maintee Thinking Fade Flip= Transform("jyushi Maintee Thinking Fade",xzoom=-1.0)
image jyushi PJ Angry = DynamicDisplayable(renpy.curry(charComposite)("jyushi","angry","01","02","pj","",0,"","false",800,950))
image jyushi PJ Angry Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","angry","01","02","pj","",0,"","true",800,950))
image jyushi PJ Angry Flip= Transform("jyushi PJ Angry",xzoom=-1.0)
image jyushi PJ Angry Fade Flip= Transform("jyushi PJ Angry Fade",xzoom=-1.0)
image jyushi PJ Dark = DynamicDisplayable(renpy.curry(charComposite)("jyushi","dark","","","pj","",0,"","false",800,950))
image jyushi PJ Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","dark","","","pj","",0,"","true",800,950))
image jyushi PJ Dark Flip= Transform("jyushi PJ Dark",xzoom=-1.0)
image jyushi PJ Dark Fade Flip= Transform("jyushi PJ Dark Fade",xzoom=-1.0)
image jyushi PJ Blank = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blank","01","02","pj","",0,"","false",800,950))
image jyushi PJ Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blank","01","02","pj","",0,"","true",800,950))
image jyushi PJ Blank Flip= Transform("jyushi PJ Blank",xzoom=-1.0)
image jyushi PJ Blank Fade Flip= Transform("jyushi PJ Blank Fade",xzoom=-1.0)
image jyushi PJ Blush = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blush","01","02","pj","",0,"","false",800,950))
image jyushi PJ Blush Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blush","01","02","pj","",0,"","true",800,950))
image jyushi PJ Blush Flip= Transform("jyushi PJ Blush",xzoom=-1.0)
image jyushi PJ Blush Fade Flip= Transform("jyushi PJ Blush Fade",xzoom=-1.0)
image jyushi PJ Displeased = DynamicDisplayable(renpy.curry(charComposite)("jyushi","displeased","01","02","pj","",0,"","false",800,950))
image jyushi PJ Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","displeased","01","02","pj","",0,"","true",800,950))
image jyushi PJ Displeased Flip= Transform("jyushi PJ Displeased",xzoom=-1.0)
image jyushi PJ Displeased Fade Flip= Transform("jyushi PJ Displeased Fade",xzoom=-1.0)
image jyushi PJ Gasp = DynamicDisplayable(renpy.curry(charComposite)("jyushi","gasp","01","02","pj","",0,"","false",800,950))
image jyushi PJ Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","gasp","01","02","pj","",0,"","true",800,950))
image jyushi PJ Gasp Flip= Transform("jyushi PJ Gasp",xzoom=-1.0)
image jyushi PJ Gasp Fade Flip= Transform("jyushi PJ Gasp Fade",xzoom=-1.0)
image jyushi PJ Happy = DynamicDisplayable(renpy.curry(charComposite)("jyushi","happy","","","pj","",0,"","false",800,950))
image jyushi PJ Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","happy","","","pj","",0,"","true",800,950))
image jyushi PJ Happy Flip= Transform("jyushi PJ Happy",xzoom=-1.0)
image jyushi PJ Happy Fade Flip= Transform("jyushi PJ Happy Fade",xzoom=-1.0)
image jyushi PJ Nervous = DynamicDisplayable(renpy.curry(charComposite)("jyushi","nervous","01","02","pj","",0,"","false",800,950))
image jyushi PJ Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","nervous","01","02","pj","",0,"","true",800,950))
image jyushi PJ Nervous Flip= Transform("jyushi PJ Nervous",xzoom=-1.0)
image jyushi PJ Nervous Fade Flip= Transform("jyushi PJ Nervous Fade",xzoom=-1.0)
image jyushi PJ Neutral = DynamicDisplayable(renpy.curry(charComposite)("jyushi","neutral","01","02","pj","",0,"","false",800,950))
image jyushi PJ Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","neutral","01","02","pj","",0,"","true",800,950))
image jyushi PJ Neutral Flip= Transform("jyushi PJ Neutral",xzoom=-1.0)
image jyushi PJ Neutral Fade Flip= Transform("jyushi PJ Neutral Fade",xzoom=-1.0)
image jyushi PJ Shocked = DynamicDisplayable(renpy.curry(charComposite)("jyushi","shocked","01","02","pj","",0,"","false",800,950))
image jyushi PJ Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","shocked","01","02","pj","",0,"","true",800,950))
image jyushi PJ Shocked Flip= Transform("jyushi PJ Shocked",xzoom=-1.0)
image jyushi PJ Shocked Fade Flip= Transform("jyushi PJ Shocked Fade",xzoom=-1.0)
image jyushi PJ Thinking = DynamicDisplayable(renpy.curry(charComposite)("jyushi","thinking","01","02","pj","",0,"","false",800,950))
image jyushi PJ Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","thinking","01","02","pj","",0,"","true",800,950))
image jyushi PJ Thinking Flip= Transform("jyushi PJ Thinking",xzoom=-1.0)
image jyushi PJ Thinking Fade Flip= Transform("jyushi PJ Thinking Fade",xzoom=-1.0)
image jyushi SchoolS Angry = DynamicDisplayable(renpy.curry(charComposite)("jyushi","angry","01","02","schools","",0,"","false",800,950))
image jyushi SchoolS Angry Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","angry","01","02","schools","",0,"","true",800,950))
image jyushi SchoolS Angry Flip= Transform("jyushi SchoolS Angry",xzoom=-1.0)
image jyushi SchoolS Angry Fade Flip= Transform("jyushi SchoolS Angry Fade",xzoom=-1.0)
image jyushi SchoolS Dark = DynamicDisplayable(renpy.curry(charComposite)("jyushi","dark","","","schools","",0,"","false",800,950))
image jyushi SchoolS Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","dark","","","schools","",0,"","true",800,950))
image jyushi SchoolS Dark Flip= Transform("jyushi SchoolS Dark",xzoom=-1.0)
image jyushi SchoolS Dark Fade Flip= Transform("jyushi SchoolS Dark Fade",xzoom=-1.0)
image jyushi SchoolS Blank = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blank","01","02","schools","",0,"","false",800,950))
image jyushi SchoolS Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blank","01","02","schools","",0,"","true",800,950))
image jyushi SchoolS Blank Flip= Transform("jyushi SchoolS Blank",xzoom=-1.0)
image jyushi SchoolS Blank Fade Flip= Transform("jyushi SchoolS Blank Fade",xzoom=-1.0)
image jyushi SchoolS Blush = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blush","01","02","schools","",0,"","false",800,950))
image jyushi SchoolS Blush Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blush","01","02","schools","",0,"","true",800,950))
image jyushi SchoolS Blush Flip= Transform("jyushi SchoolS Blush",xzoom=-1.0)
image jyushi SchoolS Blush Fade Flip= Transform("jyushi SchoolS Blush Fade",xzoom=-1.0)
image jyushi SchoolS Displeased = DynamicDisplayable(renpy.curry(charComposite)("jyushi","displeased","01","02","schools","",0,"","false",800,950))
image jyushi SchoolS Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","displeased","01","02","schools","",0,"","true",800,950))
image jyushi SchoolS Displeased Flip= Transform("jyushi SchoolS Displeased",xzoom=-1.0)
image jyushi SchoolS Displeased Fade Flip= Transform("jyushi SchoolS Displeased Fade",xzoom=-1.0)
image jyushi SchoolS Gasp = DynamicDisplayable(renpy.curry(charComposite)("jyushi","gasp","01","02","schools","",0,"","false",800,950))
image jyushi SchoolS Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","gasp","01","02","schools","",0,"","true",800,950))
image jyushi SchoolS Gasp Flip= Transform("jyushi SchoolS Gasp",xzoom=-1.0)
image jyushi SchoolS Gasp Fade Flip= Transform("jyushi SchoolS Gasp Fade",xzoom=-1.0)
image jyushi SchoolS Happy = DynamicDisplayable(renpy.curry(charComposite)("jyushi","happy","","","schools","",0,"","false",800,950))
image jyushi SchoolS Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","happy","","","schools","",0,"","true",800,950))
image jyushi SchoolS Happy Flip= Transform("jyushi SchoolS Happy",xzoom=-1.0)
image jyushi SchoolS Happy Fade Flip= Transform("jyushi SchoolS Happy Fade",xzoom=-1.0)
image jyushi SchoolS Nervous = DynamicDisplayable(renpy.curry(charComposite)("jyushi","nervous","01","02","schools","",0,"","false",800,950))
image jyushi SchoolS Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","nervous","01","02","schools","",0,"","true",800,950))
image jyushi SchoolS Nervous Flip= Transform("jyushi SchoolS Nervous",xzoom=-1.0)
image jyushi SchoolS Nervous Fade Flip= Transform("jyushi SchoolS Nervous Fade",xzoom=-1.0)
image jyushi SchoolS Neutral = DynamicDisplayable(renpy.curry(charComposite)("jyushi","neutral","01","02","schools","",0,"","false",800,950))
image jyushi SchoolS Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","neutral","01","02","schools","",0,"","true",800,950))
image jyushi SchoolS Neutral Flip= Transform("jyushi SchoolS Neutral",xzoom=-1.0)
image jyushi SchoolS Neutral Fade Flip= Transform("jyushi SchoolS Neutral Fade",xzoom=-1.0)
image jyushi SchoolS Shocked = DynamicDisplayable(renpy.curry(charComposite)("jyushi","shocked","01","02","schools","",0,"","false",800,950))
image jyushi SchoolS Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","shocked","01","02","schools","",0,"","true",800,950))
image jyushi SchoolS Shocked Flip= Transform("jyushi SchoolS Shocked",xzoom=-1.0)
image jyushi SchoolS Shocked Fade Flip= Transform("jyushi SchoolS Shocked Fade",xzoom=-1.0)
image jyushi SchoolS Thinking = DynamicDisplayable(renpy.curry(charComposite)("jyushi","thinking","01","02","schools","",0,"","false",800,950))
image jyushi SchoolS Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","thinking","01","02","schools","",0,"","true",800,950))
image jyushi SchoolS Thinking Flip= Transform("jyushi SchoolS Thinking",xzoom=-1.0)
image jyushi SchoolS Thinking Fade Flip= Transform("jyushi SchoolS Thinking Fade",xzoom=-1.0)
image jyushi SchoolW Angry = DynamicDisplayable(renpy.curry(charComposite)("jyushi","angry","01","02","schoolw","",0,"","false",800,950))
image jyushi SchoolW Angry Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","angry","01","02","schoolw","",0,"","true",800,950))
image jyushi SchoolW Angry Flip= Transform("jyushi SchoolW Angry",xzoom=-1.0)
image jyushi SchoolW Angry Fade Flip= Transform("jyushi SchoolW Angry Fade",xzoom=-1.0)
image jyushi SchoolW Dark = DynamicDisplayable(renpy.curry(charComposite)("jyushi","dark","","","schoolw","",0,"","false",800,950))
image jyushi SchoolW Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","dark","","","schoolw","",0,"","true",800,950))
image jyushi SchoolW Dark Flip= Transform("jyushi SchoolW Dark",xzoom=-1.0)
image jyushi SchoolW Dark Fade Flip= Transform("jyushi SchoolW Dark Fade",xzoom=-1.0)
image jyushi SchoolW Blank = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blank","01","02","schoolw","",0,"","false",800,950))
image jyushi SchoolW Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blank","01","02","schoolw","",0,"","true",800,950))
image jyushi SchoolW Blank Flip= Transform("jyushi SchoolW Blank",xzoom=-1.0)
image jyushi SchoolW Blank Fade Flip= Transform("jyushi SchoolW Blank Fade",xzoom=-1.0)
image jyushi SchoolW Blush = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blush","01","02","schoolw","",0,"","false",800,950))
image jyushi SchoolW Blush Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blush","01","02","schoolw","",0,"","true",800,950))
image jyushi SchoolW Blush Flip= Transform("jyushi SchoolW Blush",xzoom=-1.0)
image jyushi SchoolW Blush Fade Flip= Transform("jyushi SchoolW Blush Fade",xzoom=-1.0)
image jyushi SchoolW Displeased = DynamicDisplayable(renpy.curry(charComposite)("jyushi","displeased","01","02","schoolw","",0,"","false",800,950))
image jyushi SchoolW Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","displeased","01","02","schoolw","",0,"","true",800,950))
image jyushi SchoolW Displeased Flip= Transform("jyushi SchoolW Displeased",xzoom=-1.0)
image jyushi SchoolW Displeased Fade Flip= Transform("jyushi SchoolW Displeased Fade",xzoom=-1.0)
image jyushi SchoolW Gasp = DynamicDisplayable(renpy.curry(charComposite)("jyushi","gasp","01","02","schoolw","",0,"","false",800,950))
image jyushi SchoolW Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","gasp","01","02","schoolw","",0,"","true",800,950))
image jyushi SchoolW Gasp Flip= Transform("jyushi SchoolW Gasp",xzoom=-1.0)
image jyushi SchoolW Gasp Fade Flip= Transform("jyushi SchoolW Gasp Fade",xzoom=-1.0)
image jyushi SchoolW Happy = DynamicDisplayable(renpy.curry(charComposite)("jyushi","happy","","","schoolw","",0,"","false",800,950))
image jyushi SchoolW Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","happy","","","schoolw","",0,"","true",800,950))
image jyushi SchoolW Happy Flip= Transform("jyushi SchoolW Happy",xzoom=-1.0)
image jyushi SchoolW Happy Fade Flip= Transform("jyushi SchoolW Happy Fade",xzoom=-1.0)
image jyushi SchoolW Nervous = DynamicDisplayable(renpy.curry(charComposite)("jyushi","nervous","01","02","schoolw","",0,"","false",800,950))
image jyushi SchoolW Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","nervous","01","02","schoolw","",0,"","true",800,950))
image jyushi SchoolW Nervous Flip= Transform("jyushi SchoolW Nervous",xzoom=-1.0)
image jyushi SchoolW Nervous Fade Flip= Transform("jyushi SchoolW Nervous Fade",xzoom=-1.0)
image jyushi SchoolW Neutral = DynamicDisplayable(renpy.curry(charComposite)("jyushi","neutral","01","02","schoolw","",0,"","false",800,950))
image jyushi SchoolW Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","neutral","01","02","schoolw","",0,"","true",800,950))
image jyushi SchoolW Neutral Flip= Transform("jyushi SchoolW Neutral",xzoom=-1.0)
image jyushi SchoolW Neutral Fade Flip= Transform("jyushi SchoolW Neutral Fade",xzoom=-1.0)
image jyushi SchoolW Shocked = DynamicDisplayable(renpy.curry(charComposite)("jyushi","shocked","01","02","schoolw","",0,"","false",800,950))
image jyushi SchoolW Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","shocked","01","02","schoolw","",0,"","true",800,950))
image jyushi SchoolW Shocked Flip= Transform("jyushi SchoolW Shocked",xzoom=-1.0)
image jyushi SchoolW Shocked Fade Flip= Transform("jyushi SchoolW Shocked Fade",xzoom=-1.0)
image jyushi SchoolW Thinking = DynamicDisplayable(renpy.curry(charComposite)("jyushi","thinking","01","02","schoolw","",0,"","false",800,950))
image jyushi SchoolW Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","thinking","01","02","schoolw","",0,"","true",800,950))
image jyushi SchoolW Thinking Flip= Transform("jyushi SchoolW Thinking",xzoom=-1.0)
image jyushi SchoolW Thinking Fade Flip= Transform("jyushi SchoolW Thinking Fade",xzoom=-1.0)
image jyushi Naked Angry = DynamicDisplayable(renpy.curry(charComposite)("jyushi","angry","01","02","naked","",0,"","false",800,950))
image jyushi Naked Angry Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","angry","01","02","naked","",0,"","true",800,950))
image jyushi Naked Angry Flip= Transform("jyushi Naked Angry",xzoom=-1.0)
image jyushi Naked Angry Fade Flip= Transform("jyushi Naked Angry Fade",xzoom=-1.0)
image jyushi Naked Dark = DynamicDisplayable(renpy.curry(charComposite)("jyushi","dark","","","naked","",0,"","false",800,950))
image jyushi Naked Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","dark","","","naked","",0,"","true",800,950))
image jyushi Naked Dark Flip= Transform("jyushi Naked Dark",xzoom=-1.0)
image jyushi Naked Dark Fade Flip= Transform("jyushi Naked Dark Fade",xzoom=-1.0)
image jyushi Naked Blank = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blank","01","02","naked","",0,"","false",800,950))
image jyushi Naked Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blank","01","02","naked","",0,"","true",800,950))
image jyushi Naked Blank Flip= Transform("jyushi Naked Blank",xzoom=-1.0)
image jyushi Naked Blank Fade Flip= Transform("jyushi Naked Blank Fade",xzoom=-1.0)
image jyushi Naked Blush = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blush","01","02","naked","",0,"","false",800,950))
image jyushi Naked Blush Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","blush","01","02","naked","",0,"","true",800,950))
image jyushi Naked Blush Flip= Transform("jyushi Naked Blush",xzoom=-1.0)
image jyushi Naked Blush Fade Flip= Transform("jyushi Naked Blush Fade",xzoom=-1.0)
image jyushi Naked Displeased = DynamicDisplayable(renpy.curry(charComposite)("jyushi","displeased","01","02","naked","",0,"","false",800,950))
image jyushi Naked Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","displeased","01","02","naked","",0,"","true",800,950))
image jyushi Naked Displeased Flip= Transform("jyushi Naked Displeased",xzoom=-1.0)
image jyushi Naked Displeased Fade Flip= Transform("jyushi Naked Displeased Fade",xzoom=-1.0)
image jyushi Naked Gasp = DynamicDisplayable(renpy.curry(charComposite)("jyushi","gasp","01","02","naked","",0,"","false",800,950))
image jyushi Naked Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","gasp","01","02","naked","",0,"","true",800,950))
image jyushi Naked Gasp Flip= Transform("jyushi Naked Gasp",xzoom=-1.0)
image jyushi Naked Gasp Fade Flip= Transform("jyushi Naked Gasp Fade",xzoom=-1.0)
image jyushi Naked Happy = DynamicDisplayable(renpy.curry(charComposite)("jyushi","happy","","","naked","",0,"","false",800,950))
image jyushi Naked Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","happy","","","naked","",0,"","true",800,950))
image jyushi Naked Happy Flip= Transform("jyushi Naked Happy",xzoom=-1.0)
image jyushi Naked Happy Fade Flip= Transform("jyushi Naked Happy Fade",xzoom=-1.0)
image jyushi Naked Nervous = DynamicDisplayable(renpy.curry(charComposite)("jyushi","nervous","01","02","naked","",0,"","false",800,950))
image jyushi Naked Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","nervous","01","02","naked","",0,"","true",800,950))
image jyushi Naked Nervous Flip= Transform("jyushi Naked Nervous",xzoom=-1.0)
image jyushi Naked Nervous Fade Flip= Transform("jyushi Naked Nervous Fade",xzoom=-1.0)
image jyushi Naked Neutral = DynamicDisplayable(renpy.curry(charComposite)("jyushi","neutral","01","02","naked","",0,"","false",800,950))
image jyushi Naked Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","neutral","01","02","naked","",0,"","true",800,950))
image jyushi Naked Neutral Flip= Transform("jyushi Naked Neutral",xzoom=-1.0)
image jyushi Naked Neutral Fade Flip= Transform("jyushi Naked Neutral Fade",xzoom=-1.0)
image jyushi Naked Shocked = DynamicDisplayable(renpy.curry(charComposite)("jyushi","shocked","01","02","naked","",0,"","false",800,950))
image jyushi Naked Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","shocked","01","02","naked","",0,"","true",800,950))
image jyushi Naked Shocked Flip= Transform("jyushi Naked Shocked",xzoom=-1.0)
image jyushi Naked Shocked Fade Flip= Transform("jyushi Naked Shocked Fade",xzoom=-1.0)
image jyushi Naked Thinking = DynamicDisplayable(renpy.curry(charComposite)("jyushi","thinking","01","02","naked","",0,"","false",800,950))
image jyushi Naked Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("jyushi","thinking","01","02","naked","",0,"","true",800,950))
image jyushi Naked Thinking Flip= Transform("jyushi Naked Thinking",xzoom=-1.0)
image jyushi Naked Thinking Fade Flip= Transform("jyushi Naked Thinking Fade",xzoom=-1.0)
