# COMMENTS:
#
# Images are named like this:
# chara Clothes Expression Fade Flip
# Add Fade/Flip when needed
#
# Karamatsu has the following clothes:
# SchoolS SchoolW Bathrobe Bathtowel MainPark Naked Pj Sera
#
# Karamatsu has the following expressions:
# Neutral Angry1 Angry2 Blank Dark Displeased Happy
#
# Adding New Images:
# Use the same naming convention, copy paste the right code per commented section.
# The numbers are for head animation, for expressions such as dark, leave it as "" if it has no number behind.
# Remember every image needs normal, flip, fade, flip fade.
# Every new outfit also needs all the expressions (just in case)

#Karamatsu
image kara Bathrobe Angry1 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","01","02","bathrobe","",0,"","false",800,950))
image kara Bathrobe Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","01","02","bathrobe","",0,"","true",800,950))
image kara Bathrobe Angry1 Flip= Transform("kara Bathrobe Angry1",xzoom=-1.0)
image kara Bathrobe Angry1 Fade Flip= Transform("kara Bathrobe Angry1 Fade",xzoom=-1.0)
image kara Bathrobe Angry2 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","03","04","bathrobe","",0,"","false",800,950))
image kara Bathrobe Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","03","04","bathrobe","",0,"","true",800,950))
image kara Bathrobe Angry2 Flip= Transform("kara Bathrobe Angry2",xzoom=-1.0)
image kara Bathrobe Angry2 Fade Flip= Transform("kara Bathrobe Angry2 Fade",xzoom=-1.0)
image kara Bathrobe Angry3 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","05","06","bathrobe","",0,"","false",800,950))
image kara Bathrobe Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","05","06","bathrobe","",0,"","true",800,950))
image kara Bathrobe Angry3 Flip= Transform("kara Bathrobe Angry3",xzoom=-1.0)
image kara Bathrobe Angry3 Fade Flip= Transform("kara Bathrobe Angry3 Fade",xzoom=-1.0)
image kara Bathrobe Angry4 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","07","08","bathrobe","",0,"","false",800,950))
image kara Bathrobe Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","07","08","bathrobe","",0,"","true",800,950))
image kara Bathrobe Angry4 Flip= Transform("kara Bathrobe Angry4",xzoom=-1.0)
image kara Bathrobe Angry4 Fade Flip= Transform("kara Bathrobe Angry4 Fade",xzoom=-1.0)
image kara Bathrobe Dark = DynamicDisplayable(renpy.curry(charComposite)("kara","dark","","","bathrobe","",0,"","false",800,950))
image kara Bathrobe Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","dark","","","bathrobe","",0,"","true",800,950))
image kara Bathrobe Dark Flip= Transform("kara Bathrobe Dark",xzoom=-1.0)
image kara Bathrobe Dark Fade Flip= Transform("kara Bathrobe Dark Fade",xzoom=-1.0)
image kara Bathrobe Blank = DynamicDisplayable(renpy.curry(charComposite)("kara","blank","01","02","bathrobe","",0,"","false",800,950))
image kara Bathrobe Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","blank","01","02","bathrobe","",0,"","true",800,950))
image kara Bathrobe Blank Flip= Transform("kara Bathrobe Blank",xzoom=-1.0)
image kara Bathrobe Blank Fade Flip= Transform("kara Bathrobe Blank Fade",xzoom=-1.0)
image kara Bathrobe Displeased1 = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","01","02","bathrobe","",0,"","false",800,950))
image kara Bathrobe Displeased1 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","01","02","bathrobe","",0,"","true",800,950))
image kara Bathrobe Displeased1 Flip= Transform("kara Bathrobe Displeased1",xzoom=-1.0)
image kara Bathrobe Displeased1 Fade Flip= Transform("kara Bathrobe Displeased1 Fade",xzoom=-1.0)
image kara Bathrobe Displeased2 = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","03","04","bathrobe","",0,"","false",800,950))
image kara Bathrobe Displeased2 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","03","04","bathrobe","",0,"","true",800,950))
image kara Bathrobe Displeased2 Flip= Transform("kara Bathrobe Displeased2",xzoom=-1.0)
image kara Bathrobe Displeased2 Fade Flip= Transform("kara Bathrobe Displeased2 Fade",xzoom=-1.0)
image kara Bathrobe Happy = DynamicDisplayable(renpy.curry(charComposite)("kara","happy","01","02","bathrobe","",0,"","false",800,950))
image kara Bathrobe Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","happy","01","02","bathrobe","",0,"","true",800,950))
image kara Bathrobe Happy Flip= Transform("kara Bathrobe Happy",xzoom=-1.0)
image kara Bathrobe Happy Fade Flip= Transform("kara Bathrobe Happy Fade",xzoom=-1.0)
image kara Bathrobe Nervous = DynamicDisplayable(renpy.curry(charComposite)("kara","nervous","01","02","bathrobe","",0,"","false",800,950))
image kara Bathrobe Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","nervous","01","02","bathrobe","",0,"","true",800,950))
image kara Bathrobe Nervous Flip= Transform("kara Bathrobe Nervous",xzoom=-1.0)
image kara Bathrobe Nervous Fade Flip= Transform("kara Bathrobe Nervous Fade",xzoom=-1.0)
image kara Bathrobe Neutral = DynamicDisplayable(renpy.curry(charComposite)("kara","neutral","01","02","bathrobe","",0,"","false",800,950))
image kara Bathrobe Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","neutral","01","02","bathrobe","",0,"","true",800,950))
image kara Bathrobe Neutral Flip= Transform("kara Bathrobe Neutral",xzoom=-1.0)
image kara Bathrobe Neutral Fade Flip= Transform("kara Bathrobe Neutral Fade",xzoom=-1.0)
image kara Bathrobe Shocked = DynamicDisplayable(renpy.curry(charComposite)("kara","shocked","01","02","bathrobe","",0,"","false",800,950))
image kara Bathrobe Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","shocked","01","02","bathrobe","",0,"","true",800,950))
image kara Bathrobe Shocked Flip= Transform("kara Bathrobe Shocked",xzoom=-1.0)
image kara Bathrobe Shocked Fade Flip= Transform("kara Bathrobe Shocked Fade",xzoom=-1.0)
image kara Bathrobe Surprised = DynamicDisplayable(renpy.curry(charComposite)("kara","surprised","01","02","bathrobe","",0,"","false",800,950))
image kara Bathrobe Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","surprised","01","02","bathrobe","",0,"","true",800,950))
image kara Bathrobe Surprised Flip= Transform("kara Bathrobe Surprised",xzoom=-1.0)
image kara Bathrobe Surprised Fade Flip= Transform("kara Bathrobe Surprised Fade",xzoom=-1.0)
image kara Bathrobe Thinking = DynamicDisplayable(renpy.curry(charComposite)("kara","thinking","01","02","bathrobe","",0,"","false",800,950))
image kara Bathrobe Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","thinking","01","02","bathrobe","",0,"","true",800,950))
image kara Bathrobe Thinking Flip= Transform("kara Bathrobe Thinking",xzoom=-1.0)
image kara Bathrobe Thinking Fade Flip= Transform("kara Bathrobe Thinking Fade",xzoom=-1.0)
image kara Casual Angry1 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","01","02","casual","",0,"","false",800,950))
image kara Casual Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","01","02","casual","",0,"","true",800,950))
image kara Casual Angry1 Flip= Transform("kara Casual Angry1",xzoom=-1.0)
image kara Casual Angry1 Fade Flip= Transform("kara Casual Angry1 Fade",xzoom=-1.0)
image kara Casual Angry2 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","03","04","casual","",0,"","false",800,950))
image kara Casual Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","03","04","casual","",0,"","true",800,950))
image kara Casual Angry2 Flip= Transform("kara Casual Angry2",xzoom=-1.0)
image kara Casual Angry2 Fade Flip= Transform("kara Casual Angry2 Fade",xzoom=-1.0)
image kara Casual Angry3 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","05","06","casual","",0,"","false",800,950))
image kara Casual Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","05","06","casual","",0,"","true",800,950))
image kara Casual Angry3 Flip= Transform("kara Casual Angry3",xzoom=-1.0)
image kara Casual Angry3 Fade Flip= Transform("kara Casual Angry3 Fade",xzoom=-1.0)
image kara Casual Angry4 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","07","08","casual","",0,"","false",800,950))
image kara Casual Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","07","08","casual","",0,"","true",800,950))
image kara Casual Angry4 Flip= Transform("kara Casual Angry4",xzoom=-1.0)
image kara Casual Angry4 Fade Flip= Transform("kara Casual Angry4 Fade",xzoom=-1.0)
image kara Casual Dark = DynamicDisplayable(renpy.curry(charComposite)("kara","dark","","","casual","",0,"","false",800,950))
image kara Casual Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","dark","","","casual","",0,"","true",800,950))
image kara Casual Dark Flip= Transform("kara Casual Dark",xzoom=-1.0)
image kara Casual Dark Fade Flip= Transform("kara Casual Dark Fade",xzoom=-1.0)
image kara Casual Blank = DynamicDisplayable(renpy.curry(charComposite)("kara","blank","01","02","casual","",0,"","false",800,950))
image kara Casual Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","blank","01","02","casual","",0,"","true",800,950))
image kara Casual Blank Flip= Transform("kara Casual Blank",xzoom=-1.0)
image kara Casual Blank Fade Flip= Transform("kara Casual Blank Fade",xzoom=-1.0)
image kara Casual Displeased1 = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","01","02","casual","",0,"","false",800,950))
image kara Casual Displeased1 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","01","02","casual","",0,"","true",800,950))
image kara Casual Displeased1 Flip= Transform("kara Casual Displeased1",xzoom=-1.0)
image kara Casual Displeased1 Fade Flip= Transform("kara Casual Displeased1 Fade",xzoom=-1.0)
image kara Casual Displeased2 = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","03","04","casual","",0,"","false",800,950))
image kara Casual Displeased2 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","03","04","casual","",0,"","true",800,950))
image kara Casual Displeased2 Flip= Transform("kara Casual Displeased2",xzoom=-1.0)
image kara Casual Displeased2 Fade Flip= Transform("kara Casual Displeased2 Fade",xzoom=-1.0)
image kara Casual Happy = DynamicDisplayable(renpy.curry(charComposite)("kara","happy","01","02","casual","",0,"","false",800,950))
image kara Casual Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","happy","01","02","casual","",0,"","true",800,950))
image kara Casual Happy Flip= Transform("kara Casual Happy",xzoom=-1.0)
image kara Casual Happy Fade Flip= Transform("kara Casual Happy Fade",xzoom=-1.0)
image kara Casual Nervous = DynamicDisplayable(renpy.curry(charComposite)("kara","nervous","01","02","casual","",0,"","false",800,950))
image kara Casual Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","nervous","01","02","casual","",0,"","true",800,950))
image kara Casual Nervous Flip= Transform("kara Casual Nervous",xzoom=-1.0)
image kara Casual Nervous Fade Flip= Transform("kara Casual Nervous Fade",xzoom=-1.0)
image kara Casual Neutral = DynamicDisplayable(renpy.curry(charComposite)("kara","neutral","01","02","casual","",0,"","false",800,950))
image kara Casual Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","neutral","01","02","casual","",0,"","true",800,950))
image kara Casual Neutral Flip= Transform("kara Casual Neutral",xzoom=-1.0)
image kara Casual Neutral Fade Flip= Transform("kara Casual Neutral Fade",xzoom=-1.0)
image kara Casual Shocked = DynamicDisplayable(renpy.curry(charComposite)("kara","shocked","01","02","casual","",0,"","false",800,950))
image kara Casual Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","shocked","01","02","casual","",0,"","true",800,950))
image kara Casual Shocked Flip= Transform("kara Casual Shocked",xzoom=-1.0)
image kara Casual Shocked Fade Flip= Transform("kara Casual Shocked Fade",xzoom=-1.0)
image kara Casual Surprised = DynamicDisplayable(renpy.curry(charComposite)("kara","surprised","01","02","casual","",0,"","false",800,950))
image kara Casual Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","surprised","01","02","casual","",0,"","true",800,950))
image kara Casual Surprised Flip= Transform("kara Casual Surprised",xzoom=-1.0)
image kara Casual Surprised Fade Flip= Transform("kara Casual Surprised Fade",xzoom=-1.0)
image kara Casual Thinking = DynamicDisplayable(renpy.curry(charComposite)("kara","thinking","01","02","casual","",0,"","false",800,950))
image kara Casual Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","thinking","01","02","casual","",0,"","true",800,950))
image kara Casual Thinking Flip= Transform("kara Casual Thinking",xzoom=-1.0)
image kara Casual Thinking Fade Flip= Transform("kara Casual Thinking Fade",xzoom=-1.0)
image kara Mainpark Angry1 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","01","02","mainpark","",0,"","false",800,950))
image kara Mainpark Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","01","02","mainpark","",0,"","true",800,950))
image kara Mainpark Angry1 Flip= Transform("kara Mainpark Angry1",xzoom=-1.0)
image kara Mainpark Angry1 Fade Flip= Transform("kara Mainpark Angry1 Fade",xzoom=-1.0)
image kara Mainpark Angry2 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","03","04","mainpark","",0,"","false",800,950))
image kara Mainpark Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","03","04","mainpark","",0,"","true",800,950))
image kara Mainpark Angry2 Flip= Transform("kara Mainpark Angry2",xzoom=-1.0)
image kara Mainpark Angry2 Fade Flip= Transform("kara Mainpark Angry2 Fade",xzoom=-1.0)
image kara Mainpark Angry3 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","05","06","mainpark","",0,"","false",800,950))
image kara Mainpark Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","05","06","mainpark","",0,"","true",800,950))
image kara Mainpark Angry3 Flip= Transform("kara Mainpark Angry3",xzoom=-1.0)
image kara Mainpark Angry3 Fade Flip= Transform("kara Mainpark Angry3 Fade",xzoom=-1.0)
image kara Mainpark Angry4 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","07","08","mainpark","",0,"","false",800,950))
image kara Mainpark Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","07","08","mainpark","",0,"","true",800,950))
image kara Mainpark Angry4 Flip= Transform("kara Mainpark Angry4",xzoom=-1.0)
image kara Mainpark Angry4 Fade Flip= Transform("kara Mainpark Angry4 Fade",xzoom=-1.0)
image kara Mainpark Dark = DynamicDisplayable(renpy.curry(charComposite)("kara","dark","","","mainpark","",0,"","false",800,950))
image kara Mainpark Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","dark","","","mainpark","",0,"","true",800,950))
image kara Mainpark Dark Flip= Transform("kara Mainpark Dark",xzoom=-1.0)
image kara Mainpark Dark Fade Flip= Transform("kara Mainpark Dark Fade",xzoom=-1.0)
image kara Mainpark Blank = DynamicDisplayable(renpy.curry(charComposite)("kara","blank","01","02","mainpark","",0,"","false",800,950))
image kara Mainpark Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","blank","01","02","mainpark","",0,"","true",800,950))
image kara Mainpark Blank Flip= Transform("kara Mainpark Blank",xzoom=-1.0)
image kara Mainpark Blank Fade Flip= Transform("kara Mainpark Blank Fade",xzoom=-1.0)
image kara Mainpark Displeased1 = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","01","02","mainpark","",0,"","false",800,950))
image kara Mainpark Displeased1 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","01","02","mainpark","",0,"","true",800,950))
image kara Mainpark Displeased1 Flip= Transform("kara Mainpark Displeased1",xzoom=-1.0)
image kara Mainpark Displeased1 Fade Flip= Transform("kara Mainpark Displeased1 Fade",xzoom=-1.0)
image kara Mainpark Displeased2 = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","03","04","mainpark","",0,"","false",800,950))
image kara Mainpark Displeased2 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","03","04","mainpark","",0,"","true",800,950))
image kara Mainpark Displeased2 Flip= Transform("kara Mainpark Displeased2",xzoom=-1.0)
image kara Mainpark Displeased2 Fade Flip= Transform("kara Mainpark Displeased2 Fade",xzoom=-1.0)
image kara Mainpark Happy = DynamicDisplayable(renpy.curry(charComposite)("kara","happy","01","02","mainpark","",0,"","false",800,950))
image kara Mainpark Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","happy","01","02","mainpark","",0,"","true",800,950))
image kara Mainpark Happy Flip= Transform("kara Mainpark Happy",xzoom=-1.0)
image kara Mainpark Happy Fade Flip= Transform("kara Mainpark Happy Fade",xzoom=-1.0)
image kara Mainpark Nervous = DynamicDisplayable(renpy.curry(charComposite)("kara","nervous","01","02","mainpark","",0,"","false",800,950))
image kara Mainpark Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","nervous","01","02","mainpark","",0,"","true",800,950))
image kara Mainpark Nervous Flip= Transform("kara Mainpark Nervous",xzoom=-1.0)
image kara Mainpark Nervous Fade Flip= Transform("kara Mainpark Nervous Fade",xzoom=-1.0)
image kara Mainpark Neutral = DynamicDisplayable(renpy.curry(charComposite)("kara","neutral","01","02","mainpark","",0,"","false",800,950))
image kara Mainpark Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","neutral","01","02","mainpark","",0,"","true",800,950))
image kara Mainpark Neutral Flip= Transform("kara Mainpark Neutral",xzoom=-1.0)
image kara Mainpark Neutral Fade Flip= Transform("kara Mainpark Neutral Fade",xzoom=-1.0)
image kara Mainpark Shocked = DynamicDisplayable(renpy.curry(charComposite)("kara","shocked","01","02","mainpark","",0,"","false",800,950))
image kara Mainpark Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","shocked","01","02","mainpark","",0,"","true",800,950))
image kara Mainpark Shocked Flip= Transform("kara Mainpark Shocked",xzoom=-1.0)
image kara Mainpark Shocked Fade Flip= Transform("kara Mainpark Shocked Fade",xzoom=-1.0)
image kara Mainpark Surprised = DynamicDisplayable(renpy.curry(charComposite)("kara","surprised","01","02","mainpark","",0,"","false",800,950))
image kara Mainpark Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","surprised","01","02","mainpark","",0,"","true",800,950))
image kara Mainpark Surprised Flip= Transform("kara Mainpark Surprised",xzoom=-1.0)
image kara Mainpark Surprised Fade Flip= Transform("kara Mainpark Surprised Fade",xzoom=-1.0)
image kara Mainpark Thinking = DynamicDisplayable(renpy.curry(charComposite)("kara","thinking","01","02","mainpark","",0,"","false",800,950))
image kara Mainpark Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","thinking","01","02","mainpark","",0,"","true",800,950))
image kara Mainpark Thinking Flip= Transform("kara Mainpark Thinking",xzoom=-1.0)
image kara Mainpark Thinking Fade Flip= Transform("kara Mainpark Thinking Fade",xzoom=-1.0)
image kara Maintee Angry1 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","01","02","maintee","",0,"","false",800,950))
image kara Maintee Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","01","02","maintee","",0,"","true",800,950))
image kara Maintee Angry1 Flip= Transform("kara Maintee Angry1",xzoom=-1.0)
image kara Maintee Angry1 Fade Flip= Transform("kara Maintee Angry1 Fade",xzoom=-1.0)
image kara Maintee Angry2 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","03","04","maintee","",0,"","false",800,950))
image kara Maintee Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","03","04","maintee","",0,"","true",800,950))
image kara Maintee Angry2 Flip= Transform("kara Maintee Angry2",xzoom=-1.0)
image kara Maintee Angry2 Fade Flip= Transform("kara Maintee Angry2 Fade",xzoom=-1.0)
image kara Maintee Angry3 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","05","06","maintee","",0,"","false",800,950))
image kara Maintee Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","05","06","maintee","",0,"","true",800,950))
image kara Maintee Angry3 Flip= Transform("kara Maintee Angry3",xzoom=-1.0)
image kara Maintee Angry3 Fade Flip= Transform("kara Maintee Angry3 Fade",xzoom=-1.0)
image kara Maintee Angry4 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","07","08","maintee","",0,"","false",800,950))
image kara Maintee Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","07","08","maintee","",0,"","true",800,950))
image kara Maintee Angry4 Flip= Transform("kara Maintee Angry4",xzoom=-1.0)
image kara Maintee Angry4 Fade Flip= Transform("kara Maintee Angry4 Fade",xzoom=-1.0)
image kara Maintee Dark = DynamicDisplayable(renpy.curry(charComposite)("kara","dark","","","maintee","",0,"","false",800,950))
image kara Maintee Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","dark","","","maintee","",0,"","true",800,950))
image kara Maintee Dark Flip= Transform("kara Maintee Dark",xzoom=-1.0)
image kara Maintee Dark Fade Flip= Transform("kara Maintee Dark Fade",xzoom=-1.0)
image kara Maintee Blank = DynamicDisplayable(renpy.curry(charComposite)("kara","blank","01","02","maintee","",0,"","false",800,950))
image kara Maintee Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","blank","01","02","maintee","",0,"","true",800,950))
image kara Maintee Blank Flip= Transform("kara Maintee Blank",xzoom=-1.0)
image kara Maintee Blank Fade Flip= Transform("kara Maintee Blank Fade",xzoom=-1.0)
image kara Maintee Displeased1 = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","01","02","maintee","",0,"","false",800,950))
image kara Maintee Displeased1 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","01","02","maintee","",0,"","true",800,950))
image kara Maintee Displeased1 Flip= Transform("kara Maintee Displeased1",xzoom=-1.0)
image kara Maintee Displeased1 Fade Flip= Transform("kara Maintee Displeased1 Fade",xzoom=-1.0)
image kara Maintee Displeased2 = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","03","04","maintee","",0,"","false",800,950))
image kara Maintee Displeased2 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","03","04","maintee","",0,"","true",800,950))
image kara Maintee Displeased2 Flip= Transform("kara Maintee Displeased2",xzoom=-1.0)
image kara Maintee Displeased2 Fade Flip= Transform("kara Maintee Displeased2 Fade",xzoom=-1.0)
image kara Maintee Happy = DynamicDisplayable(renpy.curry(charComposite)("kara","happy","01","02","maintee","",0,"","false",800,950))
image kara Maintee Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","happy","01","02","maintee","",0,"","true",800,950))
image kara Maintee Happy Flip= Transform("kara Maintee Happy",xzoom=-1.0)
image kara Maintee Happy Fade Flip= Transform("kara Maintee Happy Fade",xzoom=-1.0)
image kara Maintee Nervous = DynamicDisplayable(renpy.curry(charComposite)("kara","nervous","01","02","maintee","",0,"","false",800,950))
image kara Maintee Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","nervous","01","02","maintee","",0,"","true",800,950))
image kara Maintee Nervous Flip= Transform("kara Maintee Nervous",xzoom=-1.0)
image kara Maintee Nervous Fade Flip= Transform("kara Maintee Nervous Fade",xzoom=-1.0)
image kara Maintee Neutral = DynamicDisplayable(renpy.curry(charComposite)("kara","neutral","01","02","maintee","",0,"","false",800,950))
image kara Maintee Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","neutral","01","02","maintee","",0,"","true",800,950))
image kara Maintee Neutral Flip= Transform("kara Maintee Neutral",xzoom=-1.0)
image kara Maintee Neutral Fade Flip= Transform("kara Maintee Neutral Fade",xzoom=-1.0)
image kara Maintee Shocked = DynamicDisplayable(renpy.curry(charComposite)("kara","shocked","01","02","maintee","",0,"","false",800,950))
image kara Maintee Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","shocked","01","02","maintee","",0,"","true",800,950))
image kara Maintee Shocked Flip= Transform("kara Maintee Shocked",xzoom=-1.0)
image kara Maintee Shocked Fade Flip= Transform("kara Maintee Shocked Fade",xzoom=-1.0)
image kara Maintee Surprised = DynamicDisplayable(renpy.curry(charComposite)("kara","surprised","01","02","maintee","",0,"","false",800,950))
image kara Maintee Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","surprised","01","02","maintee","",0,"","true",800,950))
image kara Maintee Surprised Flip= Transform("kara Maintee Surprised",xzoom=-1.0)
image kara Maintee Surprised Fade Flip= Transform("kara Maintee Surprised Fade",xzoom=-1.0)
image kara Maintee Thinking = DynamicDisplayable(renpy.curry(charComposite)("kara","thinking","01","02","maintee","",0,"","false",800,950))
image kara Maintee Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","thinking","01","02","maintee","",0,"","true",800,950))
image kara Maintee Thinking Flip= Transform("kara Maintee Thinking",xzoom=-1.0)
image kara Maintee Thinking Fade Flip= Transform("kara Maintee Thinking Fade",xzoom=-1.0)
image kara PJ Angry1 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","01","02","pj","",0,"","false",800,950))
image kara PJ Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","01","02","pj","",0,"","true",800,950))
image kara PJ Angry1 Flip= Transform("kara PJ Angry1",xzoom=-1.0)
image kara PJ Angry1 Fade Flip= Transform("kara PJ Angry1 Fade",xzoom=-1.0)
image kara PJ Angry2 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","03","04","pj","",0,"","false",800,950))
image kara PJ Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","03","04","pj","",0,"","true",800,950))
image kara PJ Angry2 Flip= Transform("kara PJ Angry2",xzoom=-1.0)
image kara PJ Angry2 Fade Flip= Transform("kara PJ Angry2 Fade",xzoom=-1.0)
image kara PJ Angry3 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","05","06","pj","",0,"","false",800,950))
image kara PJ Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","05","06","pj","",0,"","true",800,950))
image kara PJ Angry3 Flip= Transform("kara PJ Angry3",xzoom=-1.0)
image kara PJ Angry3 Fade Flip= Transform("kara PJ Angry3 Fade",xzoom=-1.0)
image kara PJ Angry4 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","07","08","pj","",0,"","false",800,950))
image kara PJ Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","07","08","pj","",0,"","true",800,950))
image kara PJ Angry4 Flip= Transform("kara PJ Angry4",xzoom=-1.0)
image kara PJ Angry4 Fade Flip= Transform("kara PJ Angry4 Fade",xzoom=-1.0)
image kara PJ Dark = DynamicDisplayable(renpy.curry(charComposite)("kara","dark","","","pj","",0,"","false",800,950))
image kara PJ Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","dark","","","pj","",0,"","true",800,950))
image kara PJ Dark Flip= Transform("kara PJ Dark",xzoom=-1.0)
image kara PJ Dark Fade Flip= Transform("kara PJ Dark Fade",xzoom=-1.0)
image kara PJ Blank = DynamicDisplayable(renpy.curry(charComposite)("kara","blank","01","02","pj","",0,"","false",800,950))
image kara PJ Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","blank","01","02","pj","",0,"","true",800,950))
image kara PJ Blank Flip= Transform("kara PJ Blank",xzoom=-1.0)
image kara PJ Blank Fade Flip= Transform("kara PJ Blank Fade",xzoom=-1.0)
image kara PJ Displeased1 = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","01","02","pj","",0,"","false",800,950))
image kara PJ Displeased1 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","01","02","pj","",0,"","true",800,950))
image kara PJ Displeased1 Flip= Transform("kara PJ Displeased1",xzoom=-1.0)
image kara PJ Displeased1 Fade Flip= Transform("kara PJ Displeased1 Fade",xzoom=-1.0)
image kara PJ Displeased2 = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","03","04","pj","",0,"","false",800,950))
image kara PJ Displeased2 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","03","04","pj","",0,"","true",800,950))
image kara PJ Displeased2 Flip= Transform("kara PJ Displeased2",xzoom=-1.0)
image kara PJ Displeased2 Fade Flip= Transform("kara PJ Displeased2 Fade",xzoom=-1.0)
image kara PJ Happy = DynamicDisplayable(renpy.curry(charComposite)("kara","happy","01","02","pj","",0,"","false",800,950))
image kara PJ Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","happy","01","02","pj","",0,"","true",800,950))
image kara PJ Happy Flip= Transform("kara PJ Happy",xzoom=-1.0)
image kara PJ Happy Fade Flip= Transform("kara PJ Happy Fade",xzoom=-1.0)
image kara PJ Nervous = DynamicDisplayable(renpy.curry(charComposite)("kara","nervous","01","02","pj","",0,"","false",800,950))
image kara PJ Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","nervous","01","02","pj","",0,"","true",800,950))
image kara PJ Nervous Flip= Transform("kara PJ Nervous",xzoom=-1.0)
image kara PJ Nervous Fade Flip= Transform("kara PJ Nervous Fade",xzoom=-1.0)
image kara PJ Neutral = DynamicDisplayable(renpy.curry(charComposite)("kara","neutral","01","02","pj","",0,"","false",800,950))
image kara PJ Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","neutral","01","02","pj","",0,"","true",800,950))
image kara PJ Neutral Flip= Transform("kara PJ Neutral",xzoom=-1.0)
image kara PJ Neutral Fade Flip= Transform("kara PJ Neutral Fade",xzoom=-1.0)
image kara PJ Shocked = DynamicDisplayable(renpy.curry(charComposite)("kara","shocked","01","02","pj","",0,"","false",800,950))
image kara PJ Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","shocked","01","02","pj","",0,"","true",800,950))
image kara PJ Shocked Flip= Transform("kara PJ Shocked",xzoom=-1.0)
image kara PJ Shocked Fade Flip= Transform("kara PJ Shocked Fade",xzoom=-1.0)
image kara PJ Surprised = DynamicDisplayable(renpy.curry(charComposite)("kara","surprised","01","02","pj","",0,"","false",800,950))
image kara PJ Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","surprised","01","02","pj","",0,"","true",800,950))
image kara PJ Surprised Flip= Transform("kara PJ Surprised",xzoom=-1.0)
image kara PJ Surprised Fade Flip= Transform("kara PJ Surprised Fade",xzoom=-1.0)
image kara PJ Thinking = DynamicDisplayable(renpy.curry(charComposite)("kara","thinking","01","02","pj","",0,"","false",800,950))
image kara PJ Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","thinking","01","02","pj","",0,"","true",800,950))
image kara PJ Thinking Flip= Transform("kara PJ Thinking",xzoom=-1.0)
image kara PJ Thinking Fade Flip= Transform("kara PJ Thinking Fade",xzoom=-1.0)
image kara SchoolS Angry1 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","01","02","schools","",0,"","false",800,950))
image kara SchoolS Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","01","02","schools","",0,"","true",800,950))
image kara SchoolS Angry1 Flip= Transform("kara SchoolS Angry1",xzoom=-1.0)
image kara SchoolS Angry1 Fade Flip= Transform("kara SchoolS Angry1 Fade",xzoom=-1.0)
image kara SchoolS Angry2 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","03","04","schools","",0,"","false",800,950))
image kara SchoolS Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","03","04","schools","",0,"","true",800,950))
image kara SchoolS Angry2 Flip= Transform("kara SchoolS Angry2",xzoom=-1.0)
image kara SchoolS Angry2 Fade Flip= Transform("kara SchoolS Angry2 Fade",xzoom=-1.0)
image kara SchoolS Angry3 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","05","06","schools","",0,"","false",800,950))
image kara SchoolS Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","05","06","schools","",0,"","true",800,950))
image kara SchoolS Angry3 Flip= Transform("kara SchoolS Angry3",xzoom=-1.0)
image kara SchoolS Angry3 Fade Flip= Transform("kara SchoolS Angry3 Fade",xzoom=-1.0)
image kara SchoolS Angry4 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","07","08","schools","",0,"","false",800,950))
image kara SchoolS Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","07","08","schools","",0,"","true",800,950))
image kara SchoolS Angry4 Flip= Transform("kara SchoolS Angry4",xzoom=-1.0)
image kara SchoolS Angry4 Fade Flip= Transform("kara SchoolS Angry4 Fade",xzoom=-1.0)
image kara SchoolS Dark = DynamicDisplayable(renpy.curry(charComposite)("kara","dark","","","schools","",0,"","false",800,950))
image kara SchoolS Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","dark","","","schools","",0,"","true",800,950))
image kara SchoolS Dark Flip= Transform("kara SchoolS Dark",xzoom=-1.0)
image kara SchoolS Dark Fade Flip= Transform("kara SchoolS Dark Fade",xzoom=-1.0)
image kara SchoolS Blank = DynamicDisplayable(renpy.curry(charComposite)("kara","blank","01","02","schools","",0,"","false",800,950))
image kara SchoolS Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","blank","01","02","schools","",0,"","true",800,950))
image kara SchoolS Blank Flip= Transform("kara SchoolS Blank",xzoom=-1.0)
image kara SchoolS Blank Fade Flip= Transform("kara SchoolS Blank Fade",xzoom=-1.0)
image kara SchoolS Displeased1 = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","01","02","schools","",0,"","false",800,950))
image kara SchoolS Displeased1 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","01","02","schools","",0,"","true",800,950))
image kara SchoolS Displeased1 Flip= Transform("kara SchoolS Displeased1",xzoom=-1.0)
image kara SchoolS Displeased1 Fade Flip= Transform("kara SchoolS Displeased1 Fade",xzoom=-1.0)
image kara SchoolS Displeased2 = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","03","04","schools","",0,"","false",800,950))
image kara SchoolS Displeased2 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","03","04","schools","",0,"","true",800,950))
image kara SchoolS Displeased2 Flip= Transform("kara SchoolS Displeased2",xzoom=-1.0)
image kara SchoolS Displeased2 Fade Flip= Transform("kara SchoolS Displeased2 Fade",xzoom=-1.0)
image kara SchoolS Happy = DynamicDisplayable(renpy.curry(charComposite)("kara","happy","01","02","schools","",0,"","false",800,950))
image kara SchoolS Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","happy","01","02","schools","",0,"","true",800,950))
image kara SchoolS Happy Flip= Transform("kara SchoolS Happy",xzoom=-1.0)
image kara SchoolS Happy Fade Flip= Transform("kara SchoolS Happy Fade",xzoom=-1.0)
image kara SchoolS Nervous = DynamicDisplayable(renpy.curry(charComposite)("kara","nervous","01","02","schools","",0,"","false",800,950))
image kara SchoolS Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","nervous","01","02","schools","",0,"","true",800,950))
image kara SchoolS Nervous Flip= Transform("kara SchoolS Nervous",xzoom=-1.0)
image kara SchoolS Nervous Fade Flip= Transform("kara SchoolS Nervous Fade",xzoom=-1.0)
image kara SchoolS Neutral = DynamicDisplayable(renpy.curry(charComposite)("kara","neutral","01","02","schools","",0,"","false",800,950))
image kara SchoolS Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","neutral","01","02","schools","",0,"","true",800,950))
image kara SchoolS Neutral Flip= Transform("kara SchoolS Neutral",xzoom=-1.0)
image kara SchoolS Neutral Fade Flip= Transform("kara SchoolS Neutral Fade",xzoom=-1.0)
image kara SchoolS Shocked = DynamicDisplayable(renpy.curry(charComposite)("kara","shocked","01","02","schools","",0,"","false",800,950))
image kara SchoolS Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","shocked","01","02","schools","",0,"","true",800,950))
image kara SchoolS Shocked Flip= Transform("kara SchoolS Shocked",xzoom=-1.0)
image kara SchoolS Shocked Fade Flip= Transform("kara SchoolS Shocked Fade",xzoom=-1.0)
image kara SchoolS Surprised = DynamicDisplayable(renpy.curry(charComposite)("kara","surprised","01","02","schools","",0,"","false",800,950))
image kara SchoolS Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","surprised","01","02","schools","",0,"","true",800,950))
image kara SchoolS Surprised Flip= Transform("kara SchoolS Surprised",xzoom=-1.0)
image kara SchoolS Surprised Fade Flip= Transform("kara SchoolS Surprised Fade",xzoom=-1.0)
image kara SchoolS Thinking = DynamicDisplayable(renpy.curry(charComposite)("kara","thinking","01","02","schools","",0,"","false",800,950))
image kara SchoolS Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","thinking","01","02","schools","",0,"","true",800,950))
image kara SchoolS Thinking Flip= Transform("kara SchoolS Thinking",xzoom=-1.0)
image kara SchoolS Thinking Fade Flip= Transform("kara SchoolS Thinking Fade",xzoom=-1.0)
image kara SchoolW Angry1 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","01","02","schoolw","",0,"","false",800,950))
image kara SchoolW Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","01","02","schoolw","",0,"","true",800,950))
image kara SchoolW Angry1 Flip= Transform("kara SchoolW Angry1",xzoom=-1.0)
image kara SchoolW Angry1 Fade Flip= Transform("kara SchoolW Angry1 Fade",xzoom=-1.0)
image kara SchoolW Angry2 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","03","04","schoolw","",0,"","false",800,950))
image kara SchoolW Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","03","04","schoolw","",0,"","true",800,950))
image kara SchoolW Angry2 Flip= Transform("kara SchoolW Angry2",xzoom=-1.0)
image kara SchoolW Angry2 Fade Flip= Transform("kara SchoolW Angry2 Fade",xzoom=-1.0)
image kara SchoolW Angry3 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","05","06","schoolw","",0,"","false",800,950))
image kara SchoolW Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","05","06","schoolw","",0,"","true",800,950))
image kara SchoolW Angry3 Flip= Transform("kara SchoolW Angry3",xzoom=-1.0)
image kara SchoolW Angry3 Fade Flip= Transform("kara SchoolW Angry3 Fade",xzoom=-1.0)
image kara SchoolW Angry4 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","07","08","schoolw","",0,"","false",800,950))
image kara SchoolW Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","07","08","schoolw","",0,"","true",800,950))
image kara SchoolW Angry4 Flip= Transform("kara SchoolW Angry4",xzoom=-1.0)
image kara SchoolW Angry4 Fade Flip= Transform("kara SchoolW Angry4 Fade",xzoom=-1.0)
image kara SchoolW Dark = DynamicDisplayable(renpy.curry(charComposite)("kara","dark","","","schoolw","",0,"","false",800,950))
image kara SchoolW Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","dark","","","schoolw","",0,"","true",800,950))
image kara SchoolW Dark Flip= Transform("kara SchoolW Dark",xzoom=-1.0)
image kara SchoolW Dark Fade Flip= Transform("kara SchoolW Dark Fade",xzoom=-1.0)
image kara SchoolW Blank = DynamicDisplayable(renpy.curry(charComposite)("kara","blank","01","02","schoolw","",0,"","false",800,950))
image kara SchoolW Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","blank","01","02","schoolw","",0,"","true",800,950))
image kara SchoolW Blank Flip= Transform("kara SchoolW Blank",xzoom=-1.0)
image kara SchoolW Blank Fade Flip= Transform("kara SchoolW Blank Fade",xzoom=-1.0)
image kara SchoolW Displeased1 = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","01","02","schoolw","",0,"","false",800,950))
image kara SchoolW Displeased1 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","01","02","schoolw","",0,"","true",800,950))
image kara SchoolW Displeased1 Flip= Transform("kara SchoolW Displeased1",xzoom=-1.0)
image kara SchoolW Displeased1 Fade Flip= Transform("kara SchoolW Displeased1 Fade",xzoom=-1.0)
image kara SchoolW Displeased2 = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","03","04","schoolw","",0,"","false",800,950))
image kara SchoolW Displeased2 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","03","04","schoolw","",0,"","true",800,950))
image kara SchoolW Displeased2 Flip= Transform("kara SchoolW Displeased2",xzoom=-1.0)
image kara SchoolW Displeased2 Fade Flip= Transform("kara SchoolW Displeased2 Fade",xzoom=-1.0)
image kara SchoolW Happy = DynamicDisplayable(renpy.curry(charComposite)("kara","happy","01","02","schoolw","",0,"","false",800,950))
image kara SchoolW Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","happy","01","02","schoolw","",0,"","true",800,950))
image kara SchoolW Happy Flip= Transform("kara SchoolW Happy",xzoom=-1.0)
image kara SchoolW Happy Fade Flip= Transform("kara SchoolW Happy Fade",xzoom=-1.0)
image kara SchoolW Nervous = DynamicDisplayable(renpy.curry(charComposite)("kara","nervous","01","02","schoolw","",0,"","false",800,950))
image kara SchoolW Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","nervous","01","02","schoolw","",0,"","true",800,950))
image kara SchoolW Nervous Flip= Transform("kara SchoolW Nervous",xzoom=-1.0)
image kara SchoolW Nervous Fade Flip= Transform("kara SchoolW Nervous Fade",xzoom=-1.0)
image kara SchoolW Neutral = DynamicDisplayable(renpy.curry(charComposite)("kara","neutral","01","02","schoolw","",0,"","false",800,950))
image kara SchoolW Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","neutral","01","02","schoolw","",0,"","true",800,950))
image kara SchoolW Neutral Flip= Transform("kara SchoolW Neutral",xzoom=-1.0)
image kara SchoolW Neutral Fade Flip= Transform("kara SchoolW Neutral Fade",xzoom=-1.0)
image kara SchoolW Shocked = DynamicDisplayable(renpy.curry(charComposite)("kara","shocked","01","02","schoolw","",0,"","false",800,950))
image kara SchoolW Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","shocked","01","02","schoolw","",0,"","true",800,950))
image kara SchoolW Shocked Flip= Transform("kara SchoolW Shocked",xzoom=-1.0)
image kara SchoolW Shocked Fade Flip= Transform("kara SchoolW Shocked Fade",xzoom=-1.0)
image kara SchoolW Surprised = DynamicDisplayable(renpy.curry(charComposite)("kara","surprised","01","02","schoolw","",0,"","false",800,950))
image kara SchoolW Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","surprised","01","02","schoolw","",0,"","true",800,950))
image kara SchoolW Surprised Flip= Transform("kara SchoolW Surprised",xzoom=-1.0)
image kara SchoolW Surprised Fade Flip= Transform("kara SchoolW Surprised Fade",xzoom=-1.0)
image kara SchoolW Thinking = DynamicDisplayable(renpy.curry(charComposite)("kara","thinking","01","02","schoolw","",0,"","false",800,950))
image kara SchoolW Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","thinking","01","02","schoolw","",0,"","true",800,950))
image kara SchoolW Thinking Flip= Transform("kara SchoolW Thinking",xzoom=-1.0)
image kara SchoolW Thinking Fade Flip= Transform("kara SchoolW Thinking Fade",xzoom=-1.0)
image kara Naked Angry1 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","01","02","naked","",0,"","false",800,950))
image kara Naked Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","01","02","naked","",0,"","true",800,950))
image kara Naked Angry1 Flip= Transform("kara Naked Angry1",xzoom=-1.0)
image kara Naked Angry1 Fade Flip= Transform("kara Naked Angry1 Fade",xzoom=-1.0)
image kara Naked Angry2 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","03","04","naked","",0,"","false",800,950))
image kara Naked Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","03","04","naked","",0,"","true",800,950))
image kara Naked Angry2 Flip= Transform("kara Naked Angry2",xzoom=-1.0)
image kara Naked Angry2 Fade Flip= Transform("kara Naked Angry2 Fade",xzoom=-1.0)
image kara Naked Angry3 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","05","06","naked","",0,"","false",800,950))
image kara Naked Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","05","06","naked","",0,"","true",800,950))
image kara Naked Angry3 Flip= Transform("kara Naked Angry3",xzoom=-1.0)
image kara Naked Angry3 Fade Flip= Transform("kara Naked Angry3 Fade",xzoom=-1.0)
image kara Naked Angry4 = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","07","08","naked","",0,"","false",800,950))
image kara Naked Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","angry","07","08","naked","",0,"","true",800,950))
image kara Naked Angry4 Flip= Transform("kara Naked Angry4",xzoom=-1.0)
image kara Naked Angry4 Fade Flip= Transform("kara Naked Angry4 Fade",xzoom=-1.0)
image kara Naked Dark = DynamicDisplayable(renpy.curry(charComposite)("kara","dark","","","naked","",0,"","false",800,950))
image kara Naked Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","dark","","","naked","",0,"","true",800,950))
image kara Naked Dark Flip= Transform("kara Naked Dark",xzoom=-1.0)
image kara Naked Dark Fade Flip= Transform("kara Naked Dark Fade",xzoom=-1.0)
image kara Naked Blank = DynamicDisplayable(renpy.curry(charComposite)("kara","blank","01","02","naked","",0,"","false",800,950))
image kara Naked Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","blank","01","02","naked","",0,"","true",800,950))
image kara Naked Blank Flip= Transform("kara Naked Blank",xzoom=-1.0)
image kara Naked Blank Fade Flip= Transform("kara Naked Blank Fade",xzoom=-1.0)
image kara Naked Displeased1 = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","01","02","naked","",0,"","false",800,950))
image kara Naked Displeased1 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","01","02","naked","",0,"","true",800,950))
image kara Naked Displeased1 Flip= Transform("kara Naked Displeased1",xzoom=-1.0)
image kara Naked Displeased1 Fade Flip= Transform("kara Naked Displeased1 Fade",xzoom=-1.0)
image kara Naked Displeased2 = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","03","04","naked","",0,"","false",800,950))
image kara Naked Displeased2 Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","displeased","03","04","naked","",0,"","true",800,950))
image kara Naked Displeased2 Flip= Transform("kara Naked Displeased2",xzoom=-1.0)
image kara Naked Displeased2 Fade Flip= Transform("kara Naked Displeased2 Fade",xzoom=-1.0)
image kara Naked Happy = DynamicDisplayable(renpy.curry(charComposite)("kara","happy","01","02","naked","",0,"","false",800,950))
image kara Naked Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","happy","01","02","naked","",0,"","true",800,950))
image kara Naked Happy Flip= Transform("kara Naked Happy",xzoom=-1.0)
image kara Naked Happy Fade Flip= Transform("kara Naked Happy Fade",xzoom=-1.0)
image kara Naked Nervous = DynamicDisplayable(renpy.curry(charComposite)("kara","nervous","01","02","naked","",0,"","false",800,950))
image kara Naked Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","nervous","01","02","naked","",0,"","true",800,950))
image kara Naked Nervous Flip= Transform("kara Naked Nervous",xzoom=-1.0)
image kara Naked Nervous Fade Flip= Transform("kara Naked Nervous Fade",xzoom=-1.0)
image kara Naked Neutral = DynamicDisplayable(renpy.curry(charComposite)("kara","neutral","01","02","naked","",0,"","false",800,950))
image kara Naked Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","neutral","01","02","naked","",0,"","true",800,950))
image kara Naked Neutral Flip= Transform("kara Naked Neutral",xzoom=-1.0)
image kara Naked Neutral Fade Flip= Transform("kara Naked Neutral Fade",xzoom=-1.0)
image kara Naked Shocked = DynamicDisplayable(renpy.curry(charComposite)("kara","shocked","01","02","naked","",0,"","false",800,950))
image kara Naked Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","shocked","01","02","naked","",0,"","true",800,950))
image kara Naked Shocked Flip= Transform("kara Naked Shocked",xzoom=-1.0)
image kara Naked Shocked Fade Flip= Transform("kara Naked Shocked Fade",xzoom=-1.0)
image kara Naked Surprised = DynamicDisplayable(renpy.curry(charComposite)("kara","surprised","01","02","naked","",0,"","false",800,950))
image kara Naked Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","surprised","01","02","naked","",0,"","true",800,950))
image kara Naked Surprised Flip= Transform("kara Naked Surprised",xzoom=-1.0)
image kara Naked Surprised Fade Flip= Transform("kara Naked Surprised Fade",xzoom=-1.0)
image kara Naked Thinking = DynamicDisplayable(renpy.curry(charComposite)("kara","thinking","01","02","naked","",0,"","false",800,950))
image kara Naked Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("kara","thinking","01","02","naked","",0,"","true",800,950))
image kara Naked Thinking Flip= Transform("kara Naked Thinking",xzoom=-1.0)
image kara Naked Thinking Fade Flip= Transform("kara Naked Thinking Fade",xzoom=-1.0)