# COMMENTS:
#
# Images are named like this:
# chara Clothes Expression Fade Flip
# Add Fade/Flip when needed
#
# Osomatsu has the following clothes:
# SchoolS SchoolW Bathrobe Bathtowel MainPark Naked Pj Sera
#
# Osomatsu has the following expressions:
# Neutral Angry1 Angry2 Blank Dark Displeased Happy Shock Surprised
#
# Adding New Images:
# Use the same naming convention, copy paste the right code per commented section.
# The numbers are for head animation, for expressions such as dark, leave it as "" if it has no number behind.
# Remember every image needs normal, flip, fade, flip fade.
# Every new outfit also needs all the expressions (just in case)

#Osomatsu Images
image oso Bathrobe Angry1 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","bathrobe","",0,"","false",800,950))
image oso Bathrobe Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","bathrobe","",0,"","true",800,950))
image oso Bathrobe Angry1 Flip= Transform("oso Bathrobe Angry1",xzoom=-1.0)
image oso Bathrobe Angry1 Fade Flip= Transform("oso Bathrobe Angry1 Fade",xzoom=-1.0)
image oso Bathrobe Angry2 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","bathrobe","",0,"","false",800,950))
image oso Bathrobe Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","bathrobe","",0,"","true",800,950))
image oso Bathrobe Angry2 Flip= Transform("oso Bathrobe Angry2",xzoom=-1.0)
image oso Bathrobe Angry2 Fade Flip= Transform("oso Bathrobe Angry2 Fade",xzoom=-1.0)
image oso Bathrobe Angry3 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","bathrobe","",0,"","false",800,950))
image oso Bathrobe Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","bathrobe","",0,"","true",800,950))
image oso Bathrobe Angry3 Flip= Transform("oso Bathrobe Angry3",xzoom=-1.0)
image oso Bathrobe Angry3 Fade Flip= Transform("oso Bathrobe Angry3 Fade",xzoom=-1.0)
image oso Bathrobe Angry4 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","bathrobe","",0,"","false",800,950))
image oso Bathrobe Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","bathrobe","",0,"","true",800,950))
image oso Bathrobe Angry4 Flip= Transform("oso Bathrobe Angry4",xzoom=-1.0)
image oso Bathrobe Angry4 Fade Flip= Transform("oso Bathrobe Angry4 Fade",xzoom=-1.0)
image oso Bathrobe Angry5 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","bathrobe","",0,"","false",800,950))
image oso Bathrobe Angry5 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","bathrobe","",0,"","true",800,950))
image oso Bathrobe Angry5 Flip= Transform("oso Bathrobe Angry5",xzoom=-1.0)
image oso Bathrobe Angry5 Fade Flip= Transform("oso Bathrobe Angry5 Fade",xzoom=-1.0)
image oso Bathrobe Dark = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","bathrobe","",0,"","false",800,950))
image oso Bathrobe Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","bathrobe","",0,"","true",800,950))
image oso Bathrobe Dark Flip= Transform("oso Bathrobe Dark",xzoom=-1.0)
image oso Bathrobe Dark Fade Flip= Transform("oso Bathrobe Dark Fade",xzoom=-1.0)
image oso Bathrobe Blank = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","bathrobe","",0,"","false",800,950))
image oso Bathrobe Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","bathrobe","",0,"","true",800,950))
image oso Bathrobe Blank Flip= Transform("oso Bathrobe Blank",xzoom=-1.0)
image oso Bathrobe Blank Fade Flip= Transform("oso Bathrobe Blank Fade",xzoom=-1.0)
image oso Bathrobe Displeased = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","bathrobe","",0,"","false",800,950))
image oso Bathrobe Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","bathrobe","",0,"","true",800,950))
image oso Bathrobe Displeased Flip= Transform("oso Bathrobe Displeased",xzoom=-1.0)
image oso Bathrobe Displeased Fade Flip= Transform("oso Bathrobe Displeased Fade",xzoom=-1.0)
image oso Bathrobe Gasp = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","bathrobe","",0,"","false",800,950))
image oso Bathrobe Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","bathrobe","",0,"","true",800,950))
image oso Bathrobe Gasp Flip= Transform("oso Bathrobe Gasp",xzoom=-1.0)
image oso Bathrobe Gasp Fade Flip= Transform("oso Bathrobe Gasp Fade",xzoom=-1.0)
image oso Bathrobe Happy = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","bathrobe","",0,"","false",800,950))
image oso Bathrobe Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","bathrobe","",0,"","true",800,950))
image oso Bathrobe Happy Flip= Transform("oso Bathrobe Happy",xzoom=-1.0)
image oso Bathrobe Happy Fade Flip= Transform("oso Bathrobe Happy Fade",xzoom=-1.0)
image oso Bathrobe Nervous = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","bathrobe","",0,"","false",800,950))
image oso Bathrobe Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","bathrobe","",0,"","true",800,950))
image oso Bathrobe Nervous Flip= Transform("oso Bathrobe Nervous",xzoom=-1.0)
image oso Bathrobe Nervous Fade Flip= Transform("oso Bathrobe Nervous Fade",xzoom=-1.0)
image oso Bathrobe Neutral = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","bathrobe","",0,"","false",800,950))
image oso Bathrobe Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","bathrobe","",0,"","true",800,950))
image oso Bathrobe Neutral Flip= Transform("oso Bathrobe Neutral",xzoom=-1.0)
image oso Bathrobe Neutral Fade Flip= Transform("oso Bathrobe Neutral Fade",xzoom=-1.0)
image oso Bathrobe Shocked = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","bathrobe","",0,"","false",800,950))
image oso Bathrobe Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","bathrobe","",0,"","true",800,950))
image oso Bathrobe Shocked Flip= Transform("oso Bathrobe Shocked",xzoom=-1.0)
image oso Bathrobe Shocked Fade Flip= Transform("oso Bathrobe Shocked Fade",xzoom=-1.0)
image oso Bathrobe Surprised = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","bathrobe","",0,"","false",800,950))
image oso Bathrobe Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","bathrobe","",0,"","true",800,950))
image oso Bathrobe Surprised Flip= Transform("oso Bathrobe Surprised",xzoom=-1.0)
image oso Bathrobe Surprised Fade Flip= Transform("oso Bathrobe Surprised Fade",xzoom=-1.0)
image oso Bathrobe Thinking = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","bathrobe","",0,"","false",800,950))
image oso Bathrobe Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","bathrobe","",0,"","true",800,950))
image oso Bathrobe Thinking Flip= Transform("oso Bathrobe Thinking",xzoom=-1.0)
image oso Bathrobe Thinking Fade Flip= Transform("oso Bathrobe Thinking Fade",xzoom=-1.0)
image oso Casual Angry1 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","casual","",0,"","false",800,950))
image oso Casual Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","casual","",0,"","true",800,950))
image oso Casual Angry1 Flip= Transform("oso Casual Angry1",xzoom=-1.0)
image oso Casual Angry1 Fade Flip= Transform("oso Casual Angry1 Fade",xzoom=-1.0)
image oso Casual Angry2 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","casual","",0,"","false",800,950))
image oso Casual Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","casual","",0,"","true",800,950))
image oso Casual Angry2 Flip= Transform("oso Casual Angry2",xzoom=-1.0)
image oso Casual Angry2 Fade Flip= Transform("oso Casual Angry2 Fade",xzoom=-1.0)
image oso Casual Angry3 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","casual","",0,"","false",800,950))
image oso Casual Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","casual","",0,"","true",800,950))
image oso Casual Angry3 Flip= Transform("oso Casual Angry3",xzoom=-1.0)
image oso Casual Angry3 Fade Flip= Transform("oso Casual Angry3 Fade",xzoom=-1.0)
image oso Casual Angry4 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","casual","",0,"","false",800,950))
image oso Casual Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","casual","",0,"","true",800,950))
image oso Casual Angry4 Flip= Transform("oso Casual Angry4",xzoom=-1.0)
image oso Casual Angry4 Fade Flip= Transform("oso Casual Angry4 Fade",xzoom=-1.0)
image oso Casual Angry5 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","casual","",0,"","false",800,950))
image oso Casual Angry5 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","casual","",0,"","true",800,950))
image oso Casual Angry5 Flip= Transform("oso Casual Angry5",xzoom=-1.0)
image oso Casual Angry5 Fade Flip= Transform("oso Casual Angry5 Fade",xzoom=-1.0)
image oso Casual Dark = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","casual","",0,"","false",800,950))
image oso Casual Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","casual","",0,"","true",800,950))
image oso Casual Dark Flip= Transform("oso Casual Dark",xzoom=-1.0)
image oso Casual Dark Fade Flip= Transform("oso Casual Dark Fade",xzoom=-1.0)
image oso Casual Blank = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","casual","",0,"","false",800,950))
image oso Casual Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","casual","",0,"","true",800,950))
image oso Casual Blank Flip= Transform("oso Casual Blank",xzoom=-1.0)
image oso Casual Blank Fade Flip= Transform("oso Casual Blank Fade",xzoom=-1.0)
image oso Casual Displeased = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","casual","",0,"","false",800,950))
image oso Casual Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","casual","",0,"","true",800,950))
image oso Casual Displeased Flip= Transform("oso Casual Displeased",xzoom=-1.0)
image oso Casual Displeased Fade Flip= Transform("oso Casual Displeased Fade",xzoom=-1.0)
image oso Casual Gasp = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","casual","",0,"","false",800,950))
image oso Casual Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","casual","",0,"","true",800,950))
image oso Casual Gasp Flip= Transform("oso Casual Gasp",xzoom=-1.0)
image oso Casual Gasp Fade Flip= Transform("oso Casual Gasp Fade",xzoom=-1.0)
image oso Casual Happy = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","casual","",0,"","false",800,950))
image oso Casual Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","casual","",0,"","true",800,950))
image oso Casual Happy Flip= Transform("oso Casual Happy",xzoom=-1.0)
image oso Casual Happy Fade Flip= Transform("oso Casual Happy Fade",xzoom=-1.0)
image oso Casual Nervous = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","casual","",0,"","false",800,950))
image oso Casual Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","casual","",0,"","true",800,950))
image oso Casual Nervous Flip= Transform("oso Casual Nervous",xzoom=-1.0)
image oso Casual Nervous Fade Flip= Transform("oso Casual Nervous Fade",xzoom=-1.0)
image oso Casual Neutral = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","casual","",0,"","false",800,950))
image oso Casual Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","casual","",0,"","true",800,950))
image oso Casual Neutral Flip= Transform("oso Casual Neutral",xzoom=-1.0)
image oso Casual Neutral Fade Flip= Transform("oso Casual Neutral Fade",xzoom=-1.0)
image oso Casual Shocked = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","casual","",0,"","false",800,950))
image oso Casual Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","casual","",0,"","true",800,950))
image oso Casual Shocked Flip= Transform("oso Casual Shocked",xzoom=-1.0)
image oso Casual Shocked Fade Flip= Transform("oso Casual Shocked Fade",xzoom=-1.0)
image oso Casual Surprised = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","casual","",0,"","false",800,950))
image oso Casual Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","casual","",0,"","true",800,950))
image oso Casual Surprised Flip= Transform("oso Casual Surprised",xzoom=-1.0)
image oso Casual Surprised Fade Flip= Transform("oso Casual Surprised Fade",xzoom=-1.0)
image oso Casual Thinking = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","casual","",0,"","false",800,950))
image oso Casual Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","casual","",0,"","true",800,950))
image oso Casual Thinking Flip= Transform("oso Casual Thinking",xzoom=-1.0)
image oso Casual Thinking Fade Flip= Transform("oso Casual Thinking Fade",xzoom=-1.0)
image oso Casualpants Angry1 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","casualpants","",0,"","false",800,950))
image oso Casualpants Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","casualpants","",0,"","true",800,950))
image oso Casualpants Angry1 Flip= Transform("oso Casualpants Angry1",xzoom=-1.0)
image oso Casualpants Angry1 Fade Flip= Transform("oso Casualpants Angry1 Fade",xzoom=-1.0)
image oso Casualpants Angry2 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","casualpants","",0,"","false",800,950))
image oso Casualpants Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","casualpants","",0,"","true",800,950))
image oso Casualpants Angry2 Flip= Transform("oso Casualpants Angry2",xzoom=-1.0)
image oso Casualpants Angry2 Fade Flip= Transform("oso Casualpants Angry2 Fade",xzoom=-1.0)
image oso Casualpants Angry3 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","casualpants","",0,"","false",800,950))
image oso Casualpants Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","casualpants","",0,"","true",800,950))
image oso Casualpants Angry3 Flip= Transform("oso Casualpants Angry3",xzoom=-1.0)
image oso Casualpants Angry3 Fade Flip= Transform("oso Casualpants Angry3 Fade",xzoom=-1.0)
image oso Casualpants Angry4 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","casualpants","",0,"","false",800,950))
image oso Casualpants Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","casualpants","",0,"","true",800,950))
image oso Casualpants Angry4 Flip= Transform("oso Casualpants Angry4",xzoom=-1.0)
image oso Casualpants Angry4 Fade Flip= Transform("oso Casualpants Angry4 Fade",xzoom=-1.0)
image oso Casualpants Angry5 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","casualpants","",0,"","false",800,950))
image oso Casualpants Angry5 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","casualpants","",0,"","true",800,950))
image oso Casualpants Angry5 Flip= Transform("oso Casualpants Angry5",xzoom=-1.0)
image oso Casualpants Angry5 Fade Flip= Transform("oso Casualpants Angry5 Fade",xzoom=-1.0)
image oso Casualpants Dark = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","casualpants","",0,"","false",800,950))
image oso Casualpants Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","casualpants","",0,"","true",800,950))
image oso Casualpants Dark Flip= Transform("oso Casualpants Dark",xzoom=-1.0)
image oso Casualpants Dark Fade Flip= Transform("oso Casualpants Dark Fade",xzoom=-1.0)
image oso Casualpants Blank = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","casualpants","",0,"","false",800,950))
image oso Casualpants Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","casualpants","",0,"","true",800,950))
image oso Casualpants Blank Flip= Transform("oso Casualpants Blank",xzoom=-1.0)
image oso Casualpants Blank Fade Flip= Transform("oso Casualpants Blank Fade",xzoom=-1.0)
image oso Casualpants Displeased = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","casualpants","",0,"","false",800,950))
image oso Casualpants Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","casualpants","",0,"","true",800,950))
image oso Casualpants Displeased Flip= Transform("oso Casualpants Displeased",xzoom=-1.0)
image oso Casualpants Displeased Fade Flip= Transform("oso Casualpants Displeased Fade",xzoom=-1.0)
image oso Casualpants Gasp = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","casualpants","",0,"","false",800,950))
image oso Casualpants Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","casualpants","",0,"","true",800,950))
image oso Casualpants Gasp Flip= Transform("oso Casualpants Gasp",xzoom=-1.0)
image oso Casualpants Gasp Fade Flip= Transform("oso Casualpants Gasp Fade",xzoom=-1.0)
image oso Casualpants Happy = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","casualpants","",0,"","false",800,950))
image oso Casualpants Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","casualpants","",0,"","true",800,950))
image oso Casualpants Happy Flip= Transform("oso Casualpants Happy",xzoom=-1.0)
image oso Casualpants Happy Fade Flip= Transform("oso Casualpants Happy Fade",xzoom=-1.0)
image oso Casualpants Nervous = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","casualpants","",0,"","false",800,950))
image oso Casualpants Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","casualpants","",0,"","true",800,950))
image oso Casualpants Nervous Flip= Transform("oso Casualpants Nervous",xzoom=-1.0)
image oso Casualpants Nervous Fade Flip= Transform("oso Casualpants Nervous Fade",xzoom=-1.0)
image oso Casualpants Neutral = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","casualpants","",0,"","false",800,950))
image oso Casualpants Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","casualpants","",0,"","true",800,950))
image oso Casualpants Neutral Flip= Transform("oso Casualpants Neutral",xzoom=-1.0)
image oso Casualpants Neutral Fade Flip= Transform("oso Casualpants Neutral Fade",xzoom=-1.0)
image oso Casualpants Shocked = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","casualpants","",0,"","false",800,950))
image oso Casualpants Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","casualpants","",0,"","true",800,950))
image oso Casualpants Shocked Flip= Transform("oso Casualpants Shocked",xzoom=-1.0)
image oso Casualpants Shocked Fade Flip= Transform("oso Casualpants Shocked Fade",xzoom=-1.0)
image oso Casualpants Surprised = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","casualpants","",0,"","false",800,950))
image oso Casualpants Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","casualpants","",0,"","true",800,950))
image oso Casualpants Surprised Flip= Transform("oso Casualpants Surprised",xzoom=-1.0)
image oso Casualpants Surprised Fade Flip= Transform("oso Casualpants Surprised Fade",xzoom=-1.0)
image oso Casualpants Thinking = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","casualpants","",0,"","false",800,950))
image oso Casualpants Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","casualpants","",0,"","true",800,950))
image oso Casualpants Thinking Flip= Transform("oso Casualpants Thinking",xzoom=-1.0)
image oso Casualpants Thinking Fade Flip= Transform("oso Casualpants Thinking Fade",xzoom=-1.0)
image oso Mainpark Angry1 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","mainpark","",0,"","false",800,950))
image oso Mainpark Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","mainpark","",0,"","true",800,950))
image oso Mainpark Angry1 Flip= Transform("oso Mainpark Angry1",xzoom=-1.0)
image oso Mainpark Angry1 Fade Flip= Transform("oso Mainpark Angry1 Fade",xzoom=-1.0)
image oso Mainpark Angry2 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","mainpark","",0,"","false",800,950))
image oso Mainpark Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","mainpark","",0,"","true",800,950))
image oso Mainpark Angry2 Flip= Transform("oso Mainpark Angry2",xzoom=-1.0)
image oso Mainpark Angry2 Fade Flip= Transform("oso Mainpark Angry2 Fade",xzoom=-1.0)
image oso Mainpark Angry3 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","mainpark","",0,"","false",800,950))
image oso Mainpark Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","mainpark","",0,"","true",800,950))
image oso Mainpark Angry3 Flip= Transform("oso Mainpark Angry3",xzoom=-1.0)
image oso Mainpark Angry3 Fade Flip= Transform("oso Mainpark Angry3 Fade",xzoom=-1.0)
image oso Mainpark Angry4 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","mainpark","",0,"","false",800,950))
image oso Mainpark Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","mainpark","",0,"","true",800,950))
image oso Mainpark Angry4 Flip= Transform("oso Mainpark Angry4",xzoom=-1.0)
image oso Mainpark Angry4 Fade Flip= Transform("oso Mainpark Angry4 Fade",xzoom=-1.0)
image oso Mainpark Angry5 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","mainpark","",0,"","false",800,950))
image oso Mainpark Angry5 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","mainpark","",0,"","true",800,950))
image oso Mainpark Angry5 Flip= Transform("oso Mainpark Angry5",xzoom=-1.0)
image oso Mainpark Angry5 Fade Flip= Transform("oso Mainpark Angry5 Fade",xzoom=-1.0)
image oso Mainpark Dark = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","mainpark","",0,"","false",800,950))
image oso Mainpark Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","mainpark","",0,"","true",800,950))
image oso Mainpark Dark Flip= Transform("oso Mainpark Dark",xzoom=-1.0)
image oso Mainpark Dark Fade Flip= Transform("oso Mainpark Dark Fade",xzoom=-1.0)
image oso Mainpark Blank = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","mainpark","",0,"","false",800,950))
image oso Mainpark Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","mainpark","",0,"","true",800,950))
image oso Mainpark Blank Flip= Transform("oso Mainpark Blank",xzoom=-1.0)
image oso Mainpark Blank Fade Flip= Transform("oso Mainpark Blank Fade",xzoom=-1.0)
image oso Mainpark Displeased = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","mainpark","",0,"","false",800,950))
image oso Mainpark Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","mainpark","",0,"","true",800,950))
image oso Mainpark Displeased Flip= Transform("oso Mainpark Displeased",xzoom=-1.0)
image oso Mainpark Displeased Fade Flip= Transform("oso Mainpark Displeased Fade",xzoom=-1.0)
image oso Mainpark Gasp = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","mainpark","",0,"","false",800,950))
image oso Mainpark Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","mainpark","",0,"","true",800,950))
image oso Mainpark Gasp Flip= Transform("oso Mainpark Gasp",xzoom=-1.0)
image oso Mainpark Gasp Fade Flip= Transform("oso Mainpark Gasp Fade",xzoom=-1.0)
image oso Mainpark Happy = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","mainpark","",0,"","false",800,950))
image oso Mainpark Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","mainpark","",0,"","true",800,950))
image oso Mainpark Happy Flip= Transform("oso Mainpark Happy",xzoom=-1.0)
image oso Mainpark Happy Fade Flip= Transform("oso Mainpark Happy Fade",xzoom=-1.0)
image oso Mainpark Nervous = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","mainpark","",0,"","false",800,950))
image oso Mainpark Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","mainpark","",0,"","true",800,950))
image oso Mainpark Nervous Flip= Transform("oso Mainpark Nervous",xzoom=-1.0)
image oso Mainpark Nervous Fade Flip= Transform("oso Mainpark Nervous Fade",xzoom=-1.0)
image oso Mainpark Neutral = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","mainpark","",0,"","false",800,950))
image oso Mainpark Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","mainpark","",0,"","true",800,950))
image oso Mainpark Neutral Flip= Transform("oso Mainpark Neutral",xzoom=-1.0)
image oso Mainpark Neutral Fade Flip= Transform("oso Mainpark Neutral Fade",xzoom=-1.0)
image oso Mainpark Shocked = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","mainpark","",0,"","false",800,950))
image oso Mainpark Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","mainpark","",0,"","true",800,950))
image oso Mainpark Shocked Flip= Transform("oso Mainpark Shocked",xzoom=-1.0)
image oso Mainpark Shocked Fade Flip= Transform("oso Mainpark Shocked Fade",xzoom=-1.0)
image oso Mainpark Surprised = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","mainpark","",0,"","false",800,950))
image oso Mainpark Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","mainpark","",0,"","true",800,950))
image oso Mainpark Surprised Flip= Transform("oso Mainpark Surprised",xzoom=-1.0)
image oso Mainpark Surprised Fade Flip= Transform("oso Mainpark Surprised Fade",xzoom=-1.0)
image oso Mainpark Thinking = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","mainpark","",0,"","false",800,950))
image oso Mainpark Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","mainpark","",0,"","true",800,950))
image oso Mainpark Thinking Flip= Transform("oso Mainpark Thinking",xzoom=-1.0)
image oso Mainpark Thinking Fade Flip= Transform("oso Mainpark Thinking Fade",xzoom=-1.0)
image oso Maintee Angry1 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","maintee","",0,"","false",800,950))
image oso Maintee Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","maintee","",0,"","true",800,950))
image oso Maintee Angry1 Flip= Transform("oso Maintee Angry1",xzoom=-1.0)
image oso Maintee Angry1 Fade Flip= Transform("oso Maintee Angry1 Fade",xzoom=-1.0)
image oso Maintee Angry2 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","maintee","",0,"","false",800,950))
image oso Maintee Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","maintee","",0,"","true",800,950))
image oso Maintee Angry2 Flip= Transform("oso Maintee Angry2",xzoom=-1.0)
image oso Maintee Angry2 Fade Flip= Transform("oso Maintee Angry2 Fade",xzoom=-1.0)
image oso Maintee Angry3 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","maintee","",0,"","false",800,950))
image oso Maintee Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","maintee","",0,"","true",800,950))
image oso Maintee Angry3 Flip= Transform("oso Maintee Angry3",xzoom=-1.0)
image oso Maintee Angry3 Fade Flip= Transform("oso Maintee Angry3 Fade",xzoom=-1.0)
image oso Maintee Angry4 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","maintee","",0,"","false",800,950))
image oso Maintee Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","maintee","",0,"","true",800,950))
image oso Maintee Angry4 Flip= Transform("oso Maintee Angry4",xzoom=-1.0)
image oso Maintee Angry4 Fade Flip= Transform("oso Maintee Angry4 Fade",xzoom=-1.0)
image oso Maintee Angry5 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","maintee","",0,"","false",800,950))
image oso Maintee Angry5 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","maintee","",0,"","true",800,950))
image oso Maintee Angry5 Flip= Transform("oso Maintee Angry5",xzoom=-1.0)
image oso Maintee Angry5 Fade Flip= Transform("oso Maintee Angry5 Fade",xzoom=-1.0)
image oso Maintee Dark = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","maintee","",0,"","false",800,950))
image oso Maintee Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","maintee","",0,"","true",800,950))
image oso Maintee Dark Flip= Transform("oso Maintee Dark",xzoom=-1.0)
image oso Maintee Dark Fade Flip= Transform("oso Maintee Dark Fade",xzoom=-1.0)
image oso Maintee Blank = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","maintee","",0,"","false",800,950))
image oso Maintee Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","maintee","",0,"","true",800,950))
image oso Maintee Blank Flip= Transform("oso Maintee Blank",xzoom=-1.0)
image oso Maintee Blank Fade Flip= Transform("oso Maintee Blank Fade",xzoom=-1.0)
image oso Maintee Displeased = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","maintee","",0,"","false",800,950))
image oso Maintee Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","maintee","",0,"","true",800,950))
image oso Maintee Displeased Flip= Transform("oso Maintee Displeased",xzoom=-1.0)
image oso Maintee Displeased Fade Flip= Transform("oso Maintee Displeased Fade",xzoom=-1.0)
image oso Maintee Gasp = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","maintee","",0,"","false",800,950))
image oso Maintee Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","maintee","",0,"","true",800,950))
image oso Maintee Gasp Flip= Transform("oso Maintee Gasp",xzoom=-1.0)
image oso Maintee Gasp Fade Flip= Transform("oso Maintee Gasp Fade",xzoom=-1.0)
image oso Maintee Happy = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","maintee","",0,"","false",800,950))
image oso Maintee Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","maintee","",0,"","true",800,950))
image oso Maintee Happy Flip= Transform("oso Maintee Happy",xzoom=-1.0)
image oso Maintee Happy Fade Flip= Transform("oso Maintee Happy Fade",xzoom=-1.0)
image oso Maintee Nervous = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","maintee","",0,"","false",800,950))
image oso Maintee Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","maintee","",0,"","true",800,950))
image oso Maintee Nervous Flip= Transform("oso Maintee Nervous",xzoom=-1.0)
image oso Maintee Nervous Fade Flip= Transform("oso Maintee Nervous Fade",xzoom=-1.0)
image oso Maintee Neutral = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","maintee","",0,"","false",800,950))
image oso Maintee Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","maintee","",0,"","true",800,950))
image oso Maintee Neutral Flip= Transform("oso Maintee Neutral",xzoom=-1.0)
image oso Maintee Neutral Fade Flip= Transform("oso Maintee Neutral Fade",xzoom=-1.0)
image oso Maintee Shocked = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","maintee","",0,"","false",800,950))
image oso Maintee Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","maintee","",0,"","true",800,950))
image oso Maintee Shocked Flip= Transform("oso Maintee Shocked",xzoom=-1.0)
image oso Maintee Shocked Fade Flip= Transform("oso Maintee Shocked Fade",xzoom=-1.0)
image oso Maintee Surprised = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","maintee","",0,"","false",800,950))
image oso Maintee Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","maintee","",0,"","true",800,950))
image oso Maintee Surprised Flip= Transform("oso Maintee Surprised",xzoom=-1.0)
image oso Maintee Surprised Fade Flip= Transform("oso Maintee Surprised Fade",xzoom=-1.0)
image oso Maintee Thinking = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","maintee","",0,"","false",800,950))
image oso Maintee Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","maintee","",0,"","true",800,950))
image oso Maintee Thinking Flip= Transform("oso Maintee Thinking",xzoom=-1.0)
image oso Maintee Thinking Fade Flip= Transform("oso Maintee Thinking Fade",xzoom=-1.0)
image oso PJ Angry1 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","pj","",0,"","false",800,950))
image oso PJ Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","pj","",0,"","true",800,950))
image oso PJ Angry1 Flip= Transform("oso PJ Angry1",xzoom=-1.0)
image oso PJ Angry1 Fade Flip= Transform("oso PJ Angry1 Fade",xzoom=-1.0)
image oso PJ Angry2 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","pj","",0,"","false",800,950))
image oso PJ Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","pj","",0,"","true",800,950))
image oso PJ Angry2 Flip= Transform("oso PJ Angry2",xzoom=-1.0)
image oso PJ Angry2 Fade Flip= Transform("oso PJ Angry2 Fade",xzoom=-1.0)
image oso PJ Angry3 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","pj","",0,"","false",800,950))
image oso PJ Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","pj","",0,"","true",800,950))
image oso PJ Angry3 Flip= Transform("oso PJ Angry3",xzoom=-1.0)
image oso PJ Angry3 Fade Flip= Transform("oso PJ Angry3 Fade",xzoom=-1.0)
image oso PJ Angry4 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","pj","",0,"","false",800,950))
image oso PJ Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","pj","",0,"","true",800,950))
image oso PJ Angry4 Flip= Transform("oso PJ Angry4",xzoom=-1.0)
image oso PJ Angry4 Fade Flip= Transform("oso PJ Angry4 Fade",xzoom=-1.0)
image oso PJ Angry5 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","pj","",0,"","false",800,950))
image oso PJ Angry5 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","pj","",0,"","true",800,950))
image oso PJ Angry5 Flip= Transform("oso PJ Angry5",xzoom=-1.0)
image oso PJ Angry5 Fade Flip= Transform("oso PJ Angry5 Fade",xzoom=-1.0)
image oso PJ Dark = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","pj","",0,"","false",800,950))
image oso PJ Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","pj","",0,"","true",800,950))
image oso PJ Dark Flip= Transform("oso PJ Dark",xzoom=-1.0)
image oso PJ Dark Fade Flip= Transform("oso PJ Dark Fade",xzoom=-1.0)
image oso PJ Blank = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","pj","",0,"","false",800,950))
image oso PJ Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","pj","",0,"","true",800,950))
image oso PJ Blank Flip= Transform("oso PJ Blank",xzoom=-1.0)
image oso PJ Blank Fade Flip= Transform("oso PJ Blank Fade",xzoom=-1.0)
image oso PJ Displeased = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","pj","",0,"","false",800,950))
image oso PJ Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","pj","",0,"","true",800,950))
image oso PJ Displeased Flip= Transform("oso PJ Displeased",xzoom=-1.0)
image oso PJ Displeased Fade Flip= Transform("oso PJ Displeased Fade",xzoom=-1.0)
image oso PJ Gasp = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","pj","",0,"","false",800,950))
image oso PJ Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","pj","",0,"","true",800,950))
image oso PJ Gasp Flip= Transform("oso PJ Gasp",xzoom=-1.0)
image oso PJ Gasp Fade Flip= Transform("oso PJ Gasp Fade",xzoom=-1.0)
image oso PJ Happy = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","pj","",0,"","false",800,950))
image oso PJ Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","pj","",0,"","true",800,950))
image oso PJ Happy Flip= Transform("oso PJ Happy",xzoom=-1.0)
image oso PJ Happy Fade Flip= Transform("oso PJ Happy Fade",xzoom=-1.0)
image oso PJ Nervous = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","pj","",0,"","false",800,950))
image oso PJ Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","pj","",0,"","true",800,950))
image oso PJ Nervous Flip= Transform("oso PJ Nervous",xzoom=-1.0)
image oso PJ Nervous Fade Flip= Transform("oso PJ Nervous Fade",xzoom=-1.0)
image oso PJ Neutral = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","pj","",0,"","false",800,950))
image oso PJ Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","pj","",0,"","true",800,950))
image oso PJ Neutral Flip= Transform("oso PJ Neutral",xzoom=-1.0)
image oso PJ Neutral Fade Flip= Transform("oso PJ Neutral Fade",xzoom=-1.0)
image oso PJ Shocked = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","pj","",0,"","false",800,950))
image oso PJ Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","pj","",0,"","true",800,950))
image oso PJ Shocked Flip= Transform("oso PJ Shocked",xzoom=-1.0)
image oso PJ Shocked Fade Flip= Transform("oso PJ Shocked Fade",xzoom=-1.0)
image oso PJ Surprised = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","pj","",0,"","false",800,950))
image oso PJ Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","pj","",0,"","true",800,950))
image oso PJ Surprised Flip= Transform("oso PJ Surprised",xzoom=-1.0)
image oso PJ Surprised Fade Flip= Transform("oso PJ Surprised Fade",xzoom=-1.0)
image oso PJ Thinking = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","pj","",0,"","false",800,950))
image oso PJ Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","pj","",0,"","true",800,950))
image oso PJ Thinking Flip= Transform("oso PJ Thinking",xzoom=-1.0)
image oso PJ Thinking Fade Flip= Transform("oso PJ Thinking Fade",xzoom=-1.0)
image oso SchoolS Angry1 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","schools","",0,"","false",800,950))
image oso SchoolS Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","schools","",0,"","true",800,950))
image oso SchoolS Angry1 Flip= Transform("oso SchoolS Angry1",xzoom=-1.0)
image oso SchoolS Angry1 Fade Flip= Transform("oso SchoolS Angry1 Fade",xzoom=-1.0)
image oso SchoolS Angry2 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","schools","",0,"","false",800,950))
image oso SchoolS Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","schools","",0,"","true",800,950))
image oso SchoolS Angry2 Flip= Transform("oso SchoolS Angry2",xzoom=-1.0)
image oso SchoolS Angry2 Fade Flip= Transform("oso SchoolS Angry2 Fade",xzoom=-1.0)
image oso SchoolS Angry3 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","schools","",0,"","false",800,950))
image oso SchoolS Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","schools","",0,"","true",800,950))
image oso SchoolS Angry3 Flip= Transform("oso SchoolS Angry3",xzoom=-1.0)
image oso SchoolS Angry3 Fade Flip= Transform("oso SchoolS Angry3 Fade",xzoom=-1.0)
image oso SchoolS Angry4 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","schools","",0,"","false",800,950))
image oso SchoolS Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","schools","",0,"","true",800,950))
image oso SchoolS Angry4 Flip= Transform("oso SchoolS Angry4",xzoom=-1.0)
image oso SchoolS Angry4 Fade Flip= Transform("oso SchoolS Angry4 Fade",xzoom=-1.0)
image oso SchoolS Angry5 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","schools","",0,"","false",800,950))
image oso SchoolS Angry5 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","schools","",0,"","true",800,950))
image oso SchoolS Angry5 Flip= Transform("oso SchoolS Angry5",xzoom=-1.0)
image oso SchoolS Angry5 Fade Flip= Transform("oso SchoolS Angry5 Fade",xzoom=-1.0)
image oso SchoolS Dark = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","schools","",0,"","false",800,950))
image oso SchoolS Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","schools","",0,"","true",800,950))
image oso SchoolS Dark Flip= Transform("oso SchoolS Dark",xzoom=-1.0)
image oso SchoolS Dark Fade Flip= Transform("oso SchoolS Dark Fade",xzoom=-1.0)
image oso SchoolS Blank = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","schools","",0,"","false",800,950))
image oso SchoolS Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","schools","",0,"","true",800,950))
image oso SchoolS Blank Flip= Transform("oso SchoolS Blank",xzoom=-1.0)
image oso SchoolS Blank Fade Flip= Transform("oso SchoolS Blank Fade",xzoom=-1.0)
image oso SchoolS Displeased = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","schools","",0,"","false",800,950))
image oso SchoolS Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","schools","",0,"","true",800,950))
image oso SchoolS Displeased Flip= Transform("oso SchoolS Displeased",xzoom=-1.0)
image oso SchoolS Displeased Fade Flip= Transform("oso SchoolS Displeased Fade",xzoom=-1.0)
image oso SchoolS Gasp = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","schools","",0,"","false",800,950))
image oso SchoolS Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","schools","",0,"","true",800,950))
image oso SchoolS Gasp Flip= Transform("oso SchoolS Gasp",xzoom=-1.0)
image oso SchoolS Gasp Fade Flip= Transform("oso SchoolS Gasp Fade",xzoom=-1.0)
image oso SchoolS Happy = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","schools","",0,"","false",800,950))
image oso SchoolS Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","schools","",0,"","true",800,950))
image oso SchoolS Happy Flip= Transform("oso SchoolS Happy",xzoom=-1.0)
image oso SchoolS Happy Fade Flip= Transform("oso SchoolS Happy Fade",xzoom=-1.0)
image oso SchoolS Nervous = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","schools","",0,"","false",800,950))
image oso SchoolS Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","schools","",0,"","true",800,950))
image oso SchoolS Nervous Flip= Transform("oso SchoolS Nervous",xzoom=-1.0)
image oso SchoolS Nervous Fade Flip= Transform("oso SchoolS Nervous Fade",xzoom=-1.0)
image oso SchoolS Neutral = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","schools","",0,"","false",800,950))
image oso SchoolS Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","schools","",0,"","true",800,950))
image oso SchoolS Neutral Flip= Transform("oso SchoolS Neutral",xzoom=-1.0)
image oso SchoolS Neutral Fade Flip= Transform("oso SchoolS Neutral Fade",xzoom=-1.0)
image oso SchoolS Shocked = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","schools","",0,"","false",800,950))
image oso SchoolS Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","schools","",0,"","true",800,950))
image oso SchoolS Shocked Flip= Transform("oso SchoolS Shocked",xzoom=-1.0)
image oso SchoolS Shocked Fade Flip= Transform("oso SchoolS Shocked Fade",xzoom=-1.0)
image oso SchoolS Surprised = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","schools","",0,"","false",800,950))
image oso SchoolS Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","schools","",0,"","true",800,950))
image oso SchoolS Surprised Flip= Transform("oso SchoolS Surprised",xzoom=-1.0)
image oso SchoolS Surprised Fade Flip= Transform("oso SchoolS Surprised Fade",xzoom=-1.0)
image oso SchoolS Thinking = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","schools","",0,"","false",800,950))
image oso SchoolS Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","schools","",0,"","true",800,950))
image oso SchoolS Thinking Flip= Transform("oso SchoolS Thinking",xzoom=-1.0)
image oso SchoolS Thinking Fade Flip= Transform("oso SchoolS Thinking Fade",xzoom=-1.0)
image oso SchoolW Angry1 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","schoolw","",0,"","false",800,950))
image oso SchoolW Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","schoolw","",0,"","true",800,950))
image oso SchoolW Angry1 Flip= Transform("oso SchoolW Angry1",xzoom=-1.0)
image oso SchoolW Angry1 Fade Flip= Transform("oso SchoolW Angry1 Fade",xzoom=-1.0)
image oso SchoolW Angry2 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","schoolw","",0,"","false",800,950))
image oso SchoolW Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","schoolw","",0,"","true",800,950))
image oso SchoolW Angry2 Flip= Transform("oso SchoolW Angry2",xzoom=-1.0)
image oso SchoolW Angry2 Fade Flip= Transform("oso SchoolW Angry2 Fade",xzoom=-1.0)
image oso SchoolW Angry3 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","schoolw","",0,"","false",800,950))
image oso SchoolW Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","schoolw","",0,"","true",800,950))
image oso SchoolW Angry3 Flip= Transform("oso SchoolW Angry3",xzoom=-1.0)
image oso SchoolW Angry3 Fade Flip= Transform("oso SchoolW Angry3 Fade",xzoom=-1.0)
image oso SchoolW Angry4 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","schoolw","",0,"","false",800,950))
image oso SchoolW Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","schoolw","",0,"","true",800,950))
image oso SchoolW Angry4 Flip= Transform("oso SchoolW Angry4",xzoom=-1.0)
image oso SchoolW Angry4 Fade Flip= Transform("oso SchoolW Angry4 Fade",xzoom=-1.0)
image oso SchoolW Angry5 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","schoolw","",0,"","false",800,950))
image oso SchoolW Angry5 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","schoolw","",0,"","true",800,950))
image oso SchoolW Angry5 Flip= Transform("oso SchoolW Angry5",xzoom=-1.0)
image oso SchoolW Angry5 Fade Flip= Transform("oso SchoolW Angry5 Fade",xzoom=-1.0)
image oso SchoolW Dark = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","schoolw","",0,"","false",800,950))
image oso SchoolW Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","schoolw","",0,"","true",800,950))
image oso SchoolW Dark Flip= Transform("oso SchoolW Dark",xzoom=-1.0)
image oso SchoolW Dark Fade Flip= Transform("oso SchoolW Dark Fade",xzoom=-1.0)
image oso SchoolW Blank = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","schoolw","",0,"","false",800,950))
image oso SchoolW Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","schoolw","",0,"","true",800,950))
image oso SchoolW Blank Flip= Transform("oso SchoolW Blank",xzoom=-1.0)
image oso SchoolW Blank Fade Flip= Transform("oso SchoolW Blank Fade",xzoom=-1.0)
image oso SchoolW Displeased = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","schoolw","",0,"","false",800,950))
image oso SchoolW Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","schoolw","",0,"","true",800,950))
image oso SchoolW Displeased Flip= Transform("oso SchoolW Displeased",xzoom=-1.0)
image oso SchoolW Displeased Fade Flip= Transform("oso SchoolW Displeased Fade",xzoom=-1.0)
image oso SchoolW Gasp = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","schoolw","",0,"","false",800,950))
image oso SchoolW Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","schoolw","",0,"","true",800,950))
image oso SchoolW Gasp Flip= Transform("oso SchoolW Gasp",xzoom=-1.0)
image oso SchoolW Gasp Fade Flip= Transform("oso SchoolW Gasp Fade",xzoom=-1.0)
image oso SchoolW Happy = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","schoolw","",0,"","false",800,950))
image oso SchoolW Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","schoolw","",0,"","true",800,950))
image oso SchoolW Happy Flip= Transform("oso SchoolW Happy",xzoom=-1.0)
image oso SchoolW Happy Fade Flip= Transform("oso SchoolW Happy Fade",xzoom=-1.0)
image oso SchoolW Nervous = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","schoolw","",0,"","false",800,950))
image oso SchoolW Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","schoolw","",0,"","true",800,950))
image oso SchoolW Nervous Flip= Transform("oso SchoolW Nervous",xzoom=-1.0)
image oso SchoolW Nervous Fade Flip= Transform("oso SchoolW Nervous Fade",xzoom=-1.0)
image oso SchoolW Neutral = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","schoolw","",0,"","false",800,950))
image oso SchoolW Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","schoolw","",0,"","true",800,950))
image oso SchoolW Neutral Flip= Transform("oso SchoolW Neutral",xzoom=-1.0)
image oso SchoolW Neutral Fade Flip= Transform("oso SchoolW Neutral Fade",xzoom=-1.0)
image oso SchoolW Shocked = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","schoolw","",0,"","false",800,950))
image oso SchoolW Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","schoolw","",0,"","true",800,950))
image oso SchoolW Shocked Flip= Transform("oso SchoolW Shocked",xzoom=-1.0)
image oso SchoolW Shocked Fade Flip= Transform("oso SchoolW Shocked Fade",xzoom=-1.0)
image oso SchoolW Surprised = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","schoolw","",0,"","false",800,950))
image oso SchoolW Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","schoolw","",0,"","true",800,950))
image oso SchoolW Surprised Flip= Transform("oso SchoolW Surprised",xzoom=-1.0)
image oso SchoolW Surprised Fade Flip= Transform("oso SchoolW Surprised Fade",xzoom=-1.0)
image oso SchoolW Thinking = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","schoolw","",0,"","false",800,950))
image oso SchoolW Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","schoolw","",0,"","true",800,950))
image oso SchoolW Thinking Flip= Transform("oso SchoolW Thinking",xzoom=-1.0)
image oso SchoolW Thinking Fade Flip= Transform("oso SchoolW Thinking Fade",xzoom=-1.0)
image oso Sera Angry1 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","sera","",0,"","false",800,950))
image oso Sera Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","sera","",0,"","true",800,950))
image oso Sera Angry1 Flip= Transform("oso Sera Angry1",xzoom=-1.0)
image oso Sera Angry1 Fade Flip= Transform("oso Sera Angry1 Fade",xzoom=-1.0)
image oso Sera Angry2 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","sera","",0,"","false",800,950))
image oso Sera Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","sera","",0,"","true",800,950))
image oso Sera Angry2 Flip= Transform("oso Sera Angry2",xzoom=-1.0)
image oso Sera Angry2 Fade Flip= Transform("oso Sera Angry2 Fade",xzoom=-1.0)
image oso Sera Angry3 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","sera","",0,"","false",800,950))
image oso Sera Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","sera","",0,"","true",800,950))
image oso Sera Angry3 Flip= Transform("oso Sera Angry3",xzoom=-1.0)
image oso Sera Angry3 Fade Flip= Transform("oso Sera Angry3 Fade",xzoom=-1.0)
image oso Sera Angry4 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","sera","",0,"","false",800,950))
image oso Sera Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","sera","",0,"","true",800,950))
image oso Sera Angry4 Flip= Transform("oso Sera Angry4",xzoom=-1.0)
image oso Sera Angry4 Fade Flip= Transform("oso Sera Angry4 Fade",xzoom=-1.0)
image oso Sera Angry5 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","sera","",0,"","false",800,950))
image oso Sera Angry5 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","sera","",0,"","true",800,950))
image oso Sera Angry5 Flip= Transform("oso Sera Angry5",xzoom=-1.0)
image oso Sera Angry5 Fade Flip= Transform("oso Sera Angry5 Fade",xzoom=-1.0)
image oso Sera Dark = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","sera","",0,"","false",800,950))
image oso Sera Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","sera","",0,"","true",800,950))
image oso Sera Dark Flip= Transform("oso Sera Dark",xzoom=-1.0)
image oso Sera Dark Fade Flip= Transform("oso Sera Dark Fade",xzoom=-1.0)
image oso Sera Blank = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","sera","",0,"","false",800,950))
image oso Sera Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","sera","",0,"","true",800,950))
image oso Sera Blank Flip= Transform("oso Sera Blank",xzoom=-1.0)
image oso Sera Blank Fade Flip= Transform("oso Sera Blank Fade",xzoom=-1.0)
image oso Sera Displeased = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","sera","",0,"","false",800,950))
image oso Sera Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","sera","",0,"","true",800,950))
image oso Sera Displeased Flip= Transform("oso Sera Displeased",xzoom=-1.0)
image oso Sera Displeased Fade Flip= Transform("oso Sera Displeased Fade",xzoom=-1.0)
image oso Sera Gasp = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","sera","",0,"","false",800,950))
image oso Sera Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","sera","",0,"","true",800,950))
image oso Sera Gasp Flip= Transform("oso Sera Gasp",xzoom=-1.0)
image oso Sera Gasp Fade Flip= Transform("oso Sera Gasp Fade",xzoom=-1.0)
image oso Sera Happy = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","sera","",0,"","false",800,950))
image oso Sera Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","sera","",0,"","true",800,950))
image oso Sera Happy Flip= Transform("oso Sera Happy",xzoom=-1.0)
image oso Sera Happy Fade Flip= Transform("oso Sera Happy Fade",xzoom=-1.0)
image oso Sera Nervous = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","sera","",0,"","false",800,950))
image oso Sera Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","sera","",0,"","true",800,950))
image oso Sera Nervous Flip= Transform("oso Sera Nervous",xzoom=-1.0)
image oso Sera Nervous Fade Flip= Transform("oso Sera Nervous Fade",xzoom=-1.0)
image oso Sera Neutral = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","sera","",0,"","false",800,950))
image oso Sera Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","sera","",0,"","true",800,950))
image oso Sera Neutral Flip= Transform("oso Sera Neutral",xzoom=-1.0)
image oso Sera Neutral Fade Flip= Transform("oso Sera Neutral Fade",xzoom=-1.0)
image oso Sera Shocked = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","sera","",0,"","false",800,950))
image oso Sera Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","sera","",0,"","true",800,950))
image oso Sera Shocked Flip= Transform("oso Sera Shocked",xzoom=-1.0)
image oso Sera Shocked Fade Flip= Transform("oso Sera Shocked Fade",xzoom=-1.0)
image oso Sera Surprised = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","sera","",0,"","false",800,950))
image oso Sera Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","sera","",0,"","true",800,950))
image oso Sera Surprised Flip= Transform("oso Sera Surprised",xzoom=-1.0)
image oso Sera Surprised Fade Flip= Transform("oso Sera Surprised Fade",xzoom=-1.0)
image oso Sera Thinking = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","sera","",0,"","false",800,950))
image oso Sera Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","sera","",0,"","true",800,950))
image oso Sera Thinking Flip= Transform("oso Sera Thinking",xzoom=-1.0)
image oso Sera Thinking Fade Flip= Transform("oso Sera Thinking Fade",xzoom=-1.0)
image oso Naked Angry1 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","naked","",0,"","false",800,950))
image oso Naked Angry1 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","01","02","naked","",0,"","true",800,950))
image oso Naked Angry1 Flip= Transform("oso Naked Angry1",xzoom=-1.0)
image oso Naked Angry1 Fade Flip= Transform("oso Naked Angry1 Fade",xzoom=-1.0)
image oso Naked Angry2 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","naked","",0,"","false",800,950))
image oso Naked Angry2 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","03","04","naked","",0,"","true",800,950))
image oso Naked Angry2 Flip= Transform("oso Naked Angry2",xzoom=-1.0)
image oso Naked Angry2 Fade Flip= Transform("oso Naked Angry2 Fade",xzoom=-1.0)
image oso Naked Angry3 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","naked","",0,"","false",800,950))
image oso Naked Angry3 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","05","06","naked","",0,"","true",800,950))
image oso Naked Angry3 Flip= Transform("oso Naked Angry3",xzoom=-1.0)
image oso Naked Angry3 Fade Flip= Transform("oso Naked Angry3 Fade",xzoom=-1.0)
image oso Naked Angry4 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","naked","",0,"","false",800,950))
image oso Naked Angry4 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry","07","08","naked","",0,"","true",800,950))
image oso Naked Angry4 Flip= Transform("oso Naked Angry4",xzoom=-1.0)
image oso Naked Angry4 Fade Flip= Transform("oso Naked Angry4 Fade",xzoom=-1.0)
image oso Naked Angry5 = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","naked","",0,"","false",800,950))
image oso Naked Angry5 Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","angry5","01","02","naked","",0,"","true",800,950))
image oso Naked Angry5 Flip= Transform("oso Naked Angry5",xzoom=-1.0)
image oso Naked Angry5 Fade Flip= Transform("oso Naked Angry5 Fade",xzoom=-1.0)
image oso Naked Dark = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","naked","",0,"","false",800,950))
image oso Naked Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","dark","","","naked","",0,"","true",800,950))
image oso Naked Dark Flip= Transform("oso Naked Dark",xzoom=-1.0)
image oso Naked Dark Fade Flip= Transform("oso Naked Dark Fade",xzoom=-1.0)
image oso Naked Blank = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","naked","",0,"","false",800,950))
image oso Naked Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","blank","01","02","naked","",0,"","true",800,950))
image oso Naked Blank Flip= Transform("oso Naked Blank",xzoom=-1.0)
image oso Naked Blank Fade Flip= Transform("oso Naked Blank Fade",xzoom=-1.0)
image oso Naked Displeased = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","naked","",0,"","false",800,950))
image oso Naked Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","displeased","01","02","naked","",0,"","true",800,950))
image oso Naked Displeased Flip= Transform("oso Naked Displeased",xzoom=-1.0)
image oso Naked Displeased Fade Flip= Transform("oso Naked Displeased Fade",xzoom=-1.0)
image oso Naked Gasp = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","naked","",0,"","false",800,950))
image oso Naked Gasp Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","gasp","01","02","naked","",0,"","true",800,950))
image oso Naked Gasp Flip= Transform("oso Naked Gasp",xzoom=-1.0)
image oso Naked Gasp Fade Flip= Transform("oso Naked Gasp Fade",xzoom=-1.0)
image oso Naked Happy = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","naked","",0,"","false",800,950))
image oso Naked Happy Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","happy","01","02","naked","",0,"","true",800,950))
image oso Naked Happy Flip= Transform("oso Naked Happy",xzoom=-1.0)
image oso Naked Happy Fade Flip= Transform("oso Naked Happy Fade",xzoom=-1.0)
image oso Naked Nervous = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","naked","",0,"","false",800,950))
image oso Naked Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","nervous","01","02","naked","",0,"","true",800,950))
image oso Naked Nervous Flip= Transform("oso Naked Nervous",xzoom=-1.0)
image oso Naked Nervous Fade Flip= Transform("oso Naked Nervous Fade",xzoom=-1.0)
image oso Naked Neutral = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","naked","",0,"","false",800,950))
image oso Naked Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","neutral","01","02","naked","",0,"","true",800,950))
image oso Naked Neutral Flip= Transform("oso Naked Neutral",xzoom=-1.0)
image oso Naked Neutral Fade Flip= Transform("oso Naked Neutral Fade",xzoom=-1.0)
image oso Naked Shocked = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","naked","",0,"","false",800,950))
image oso Naked Shocked Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","shocked","01","02","naked","",0,"","true",800,950))
image oso Naked Shocked Flip= Transform("oso Naked Shocked",xzoom=-1.0)
image oso Naked Shocked Fade Flip= Transform("oso Naked Shocked Fade",xzoom=-1.0)
image oso Naked Surprised = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","naked","",0,"","false",800,950))
image oso Naked Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","surprised","01","02","naked","",0,"","true",800,950))
image oso Naked Surprised Flip= Transform("oso Naked Surprised",xzoom=-1.0)
image oso Naked Surprised Fade Flip= Transform("oso Naked Surprised Fade",xzoom=-1.0)
image oso Naked Thinking = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","naked","",0,"","false",800,950))
image oso Naked Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("oso","thinking","01","02","naked","",0,"","true",800,950))
image oso Naked Thinking Flip= Transform("oso Naked Thinking",xzoom=-1.0)
image oso Naked Thinking Fade Flip= Transform("oso Naked Thinking Fade",xzoom=-1.0)