# COMMENTS:
#
# Images are named like this:
# chara Clothes Expression Fade Flip
# Add Fade/Flip when needed
#
# Todomatsu has the following clothes:
# SchoolS SchoolW Bathrobe Bathtowel MainPark Naked Pj Sera
#
# Todomatsu has the following expressions:
# Neutral Angry Blank Displeased Nervous Thinking
#
# Adding New Images:
# Use the same naming convention, copy paste the right code per commented section.
# The numbers are for head animation, for expressions such as dark, leave it as "" if it has no number behind.
# Remember every image needs normal, flip, fade, flip fade.
# Every new outfit also needs all the expressions (just in case)

#Todomatsu Images
image todo Bathrobe Angry = DynamicDisplayable(renpy.curry(charComposite)("todo","angry","01","02","bathrobe","",0,"","false",800,950))
image todo Bathrobe Angry Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","angry","01","02","bathrobe","",0,"","true",800,950))
image todo Bathrobe Angry Flip= Transform("todo Bathrobe Angry",xzoom=-1.0)
image todo Bathrobe Angry Fade Flip= Transform("todo Bathrobe Angry Fade",xzoom=-1.0)
image todo Bathrobe Dark = DynamicDisplayable(renpy.curry(charComposite)("todo","dark","","","bathrobe","",0,"","false",800,950))
image todo Bathrobe Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","dark","","","bathrobe","",0,"","true",800,950))
image todo Bathrobe Dark Flip= Transform("todo Bathrobe Dark",xzoom=-1.0)
image todo Bathrobe Dark Fade Flip= Transform("todo Bathrobe Dark Fade",xzoom=-1.0)
image todo Bathrobe Blank = DynamicDisplayable(renpy.curry(charComposite)("todo","blank","01","02","bathrobe","",0,"","false",800,950))
image todo Bathrobe Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","blank","01","02","bathrobe","",0,"","true",800,950))
image todo Bathrobe Blank Flip= Transform("todo Bathrobe Blank",xzoom=-1.0)
image todo Bathrobe Blank Fade Flip= Transform("todo Bathrobe Blank Fade",xzoom=-1.0)
image todo Bathrobe Displeased = DynamicDisplayable(renpy.curry(charComposite)("todo","displeased","01","02","bathrobe","",0,"","false",800,950))
image todo Bathrobe Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","displeased","01","02","bathrobe","",0,"","true",800,950))
image todo Bathrobe Displeased Flip= Transform("todo Bathrobe Displeased",xzoom=-1.0)
image todo Bathrobe Displeased Fade Flip= Transform("todo Bathrobe Displeased Fade",xzoom=-1.0)
image todo Bathrobe Happy1 = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","01","01","bathrobe","",0,"","false",800,950))
image todo Bathrobe Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","01","01","bathrobe","",0,"","true",800,950))
image todo Bathrobe Happy1 Flip= Transform("todo Bathrobe Happy1",xzoom=-1.0)
image todo Bathrobe Happy1 Fade Flip= Transform("todo Bathrobe Happy1 Fade",xzoom=-1.0)
image todo Bathrobe Happy2 = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","02","02","bathrobe","",0,"","false",800,950))
image todo Bathrobe Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","02","02","bathrobe","",0,"","true",800,950))
image todo Bathrobe Happy2 Flip= Transform("todo Bathrobe Happy2",xzoom=-1.0)
image todo Bathrobe Happy2 Fade Flip= Transform("todo Bathrobe Happy2 Fade",xzoom=-1.0)
image todo Bathrobe Nervous = DynamicDisplayable(renpy.curry(charComposite)("todo","nervous","01","02","bathrobe","",0,"","false",800,950))
image todo Bathrobe Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","nervous","01","02","bathrobe","",0,"","true",800,950))
image todo Bathrobe Nervous Flip= Transform("todo Bathrobe Nervous",xzoom=-1.0)
image todo Bathrobe Nervous Fade Flip= Transform("todo Bathrobe Nervous Fade",xzoom=-1.0)
image todo Bathrobe Neutral = DynamicDisplayable(renpy.curry(charComposite)("todo","neutral","01","02","bathrobe","",0,"","false",800,950))
image todo Bathrobe Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","neutral","01","02","bathrobe","",0,"","true",800,950))
image todo Bathrobe Neutral Flip= Transform("todo Bathrobe Neutral",xzoom=-1.0)
image todo Bathrobe Neutral Fade Flip= Transform("todo Bathrobe Neutral Fade",xzoom=-1.0)
image todo Bathrobe Shocked1 = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","01","02","bathrobe","",0,"","false",800,950))
image todo Bathrobe Shocked1 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","01","02","bathrobe","",0,"","true",800,950))
image todo Bathrobe Shocked1 Flip= Transform("todo Bathrobe Shocked1",xzoom=-1.0)
image todo Bathrobe Shocked1 Fade Flip= Transform("todo Bathrobe Shocked1 Fade",xzoom=-1.0)
image todo Bathrobe Shocked2 = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","03","04","bathrobe","",0,"","false",800,950))
image todo Bathrobe Shocked2 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","03","04","bathrobe","",0,"","true",800,950))
image todo Bathrobe Shocked2 Flip= Transform("todo Bathrobe Shocked2",xzoom=-1.0)
image todo Bathrobe Shocked2 Fade Flip= Transform("todo Bathrobe Shocked2 Fade",xzoom=-1.0)
image todo Bathrobe Surprised = DynamicDisplayable(renpy.curry(charComposite)("todo","surprised","01","02","bathrobe","",0,"","false",800,950))
image todo Bathrobe Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","surprised","01","02","bathrobe","",0,"","true",800,950))
image todo Bathrobe Surprised Flip= Transform("todo Bathrobe Surprised",xzoom=-1.0)
image todo Bathrobe Surprised Fade Flip= Transform("todo Bathrobe Surprised Fade",xzoom=-1.0)
image todo Bathrobe Thinking = DynamicDisplayable(renpy.curry(charComposite)("todo","thinking","01","02","bathrobe","",0,"","false",800,950))
image todo Bathrobe Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","thinking","01","02","bathrobe","",0,"","true",800,950))
image todo Bathrobe Thinking Flip= Transform("todo Bathrobe Thinking",xzoom=-1.0)
image todo Bathrobe Thinking Fade Flip= Transform("todo Bathrobe Thinking Fade",xzoom=-1.0)
image todo Casual Angry = DynamicDisplayable(renpy.curry(charComposite)("todo","angry","01","02","casual","",0,"","false",800,950))
image todo Casual Angry Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","angry","01","02","casual","",0,"","true",800,950))
image todo Casual Angry Flip= Transform("todo Casual Angry",xzoom=-1.0)
image todo Casual Angry Fade Flip= Transform("todo Casual Angry Fade",xzoom=-1.0)
image todo Casual Dark = DynamicDisplayable(renpy.curry(charComposite)("todo","dark","","","casual","",0,"","false",800,950))
image todo Casual Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","dark","","","casual","",0,"","true",800,950))
image todo Casual Dark Flip= Transform("todo Casual Dark",xzoom=-1.0)
image todo Casual Dark Fade Flip= Transform("todo Casual Dark Fade",xzoom=-1.0)
image todo Casual Blank = DynamicDisplayable(renpy.curry(charComposite)("todo","blank","01","02","casual","",0,"","false",800,950))
image todo Casual Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","blank","01","02","casual","",0,"","true",800,950))
image todo Casual Blank Flip= Transform("todo Casual Blank",xzoom=-1.0)
image todo Casual Blank Fade Flip= Transform("todo Casual Blank Fade",xzoom=-1.0)
image todo Casual Displeased = DynamicDisplayable(renpy.curry(charComposite)("todo","displeased","01","02","casual","",0,"","false",800,950))
image todo Casual Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","displeased","01","02","casual","",0,"","true",800,950))
image todo Casual Displeased Flip= Transform("todo Casual Displeased",xzoom=-1.0)
image todo Casual Displeased Fade Flip= Transform("todo Casual Displeased Fade",xzoom=-1.0)
image todo Casual Happy1 = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","01","01","casual","",0,"","false",800,950))
image todo Casual Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","01","01","casual","",0,"","true",800,950))
image todo Casual Happy1 Flip= Transform("todo Casual Happy1",xzoom=-1.0)
image todo Casual Happy1 Fade Flip= Transform("todo Casual Happy1 Fade",xzoom=-1.0)
image todo Casual Happy2 = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","02","02","casual","",0,"","false",800,950))
image todo Casual Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","02","02","casual","",0,"","true",800,950))
image todo Casual Happy2 Flip= Transform("todo Casual Happy2",xzoom=-1.0)
image todo Casual Happy2 Fade Flip= Transform("todo Casual Happy2 Fade",xzoom=-1.0)
image todo Casual Nervous = DynamicDisplayable(renpy.curry(charComposite)("todo","nervous","01","02","casual","",0,"","false",800,950))
image todo Casual Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","nervous","01","02","casual","",0,"","true",800,950))
image todo Casual Nervous Flip= Transform("todo Casual Nervous",xzoom=-1.0)
image todo Casual Nervous Fade Flip= Transform("todo Casual Nervous Fade",xzoom=-1.0)
image todo Casual Neutral = DynamicDisplayable(renpy.curry(charComposite)("todo","neutral","01","02","casual","",0,"","false",800,950))
image todo Casual Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","neutral","01","02","casual","",0,"","true",800,950))
image todo Casual Neutral Flip= Transform("todo Casual Neutral",xzoom=-1.0)
image todo Casual Neutral Fade Flip= Transform("todo Casual Neutral Fade",xzoom=-1.0)
image todo Casual Shocked1 = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","01","02","casual","",0,"","false",800,950))
image todo Casual Shocked1 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","01","02","casual","",0,"","true",800,950))
image todo Casual Shocked1 Flip= Transform("todo Casual Shocked1",xzoom=-1.0)
image todo Casual Shocked1 Fade Flip= Transform("todo Casual Shocked1 Fade",xzoom=-1.0)
image todo Casual Shocked2 = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","03","04","casual","",0,"","false",800,950))
image todo Casual Shocked2 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","03","04","casual","",0,"","true",800,950))
image todo Casual Shocked2 Flip= Transform("todo Casual Shocked2",xzoom=-1.0)
image todo Casual Shocked2 Fade Flip= Transform("todo Casual Shocked2 Fade",xzoom=-1.0)
image todo Casual Surprised = DynamicDisplayable(renpy.curry(charComposite)("todo","surprised","01","02","casual","",0,"","false",800,950))
image todo Casual Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","surprised","01","02","casual","",0,"","true",800,950))
image todo Casual Surprised Flip= Transform("todo Casual Surprised",xzoom=-1.0)
image todo Casual Surprised Fade Flip= Transform("todo Casual Surprised Fade",xzoom=-1.0)
image todo Casual Thinking = DynamicDisplayable(renpy.curry(charComposite)("todo","thinking","01","02","casual","",0,"","false",800,950))
image todo Casual Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","thinking","01","02","casual","",0,"","true",800,950))
image todo Casual Thinking Flip= Transform("todo Casual Thinking",xzoom=-1.0)
image todo Casual Thinking Fade Flip= Transform("todo Casual Thinking Fade",xzoom=-1.0)
image todo Mainpark Angry = DynamicDisplayable(renpy.curry(charComposite)("todo","angry","01","02","mainpark","",0,"","false",800,950))
image todo Mainpark Angry Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","angry","01","02","mainpark","",0,"","true",800,950))
image todo Mainpark Angry Flip= Transform("todo Mainpark Angry",xzoom=-1.0)
image todo Mainpark Angry Fade Flip= Transform("todo Mainpark Angry Fade",xzoom=-1.0)
image todo Mainpark Dark = DynamicDisplayable(renpy.curry(charComposite)("todo","dark","","","mainpark","",0,"","false",800,950))
image todo Mainpark Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","dark","","","mainpark","",0,"","true",800,950))
image todo Mainpark Dark Flip= Transform("todo Mainpark Dark",xzoom=-1.0)
image todo Mainpark Dark Fade Flip= Transform("todo Mainpark Dark Fade",xzoom=-1.0)
image todo Mainpark Blank = DynamicDisplayable(renpy.curry(charComposite)("todo","blank","01","02","mainpark","",0,"","false",800,950))
image todo Mainpark Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","blank","01","02","mainpark","",0,"","true",800,950))
image todo Mainpark Blank Flip= Transform("todo Mainpark Blank",xzoom=-1.0)
image todo Mainpark Blank Fade Flip= Transform("todo Mainpark Blank Fade",xzoom=-1.0)
image todo Mainpark Displeased = DynamicDisplayable(renpy.curry(charComposite)("todo","displeased","01","02","mainpark","",0,"","false",800,950))
image todo Mainpark Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","displeased","01","02","mainpark","",0,"","true",800,950))
image todo Mainpark Displeased Flip= Transform("todo Mainpark Displeased",xzoom=-1.0)
image todo Mainpark Displeased Fade Flip= Transform("todo Mainpark Displeased Fade",xzoom=-1.0)
image todo Mainpark Happy1 = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","01","01","mainpark","",0,"","false",800,950))
image todo Mainpark Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","01","01","mainpark","",0,"","true",800,950))
image todo Mainpark Happy1 Flip= Transform("todo Mainpark Happy1",xzoom=-1.0)
image todo Mainpark Happy1 Fade Flip= Transform("todo Mainpark Happy1 Fade",xzoom=-1.0)
image todo Mainpark Happy2 = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","02","02","mainpark","",0,"","false",800,950))
image todo Mainpark Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","02","02","mainpark","",0,"","true",800,950))
image todo Mainpark Happy2 Flip= Transform("todo Mainpark Happy2",xzoom=-1.0)
image todo Mainpark Happy2 Fade Flip= Transform("todo Mainpark Happy2 Fade",xzoom=-1.0)
image todo Mainpark Nervous = DynamicDisplayable(renpy.curry(charComposite)("todo","nervous","01","02","mainpark","",0,"","false",800,950))
image todo Mainpark Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","nervous","01","02","mainpark","",0,"","true",800,950))
image todo Mainpark Nervous Flip= Transform("todo Mainpark Nervous",xzoom=-1.0)
image todo Mainpark Nervous Fade Flip= Transform("todo Mainpark Nervous Fade",xzoom=-1.0)
image todo Mainpark Neutral = DynamicDisplayable(renpy.curry(charComposite)("todo","neutral","01","02","mainpark","",0,"","false",800,950))
image todo Mainpark Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","neutral","01","02","mainpark","",0,"","true",800,950))
image todo Mainpark Neutral Flip= Transform("todo Mainpark Neutral",xzoom=-1.0)
image todo Mainpark Neutral Fade Flip= Transform("todo Mainpark Neutral Fade",xzoom=-1.0)
image todo Mainpark Shocked1 = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","01","02","mainpark","",0,"","false",800,950))
image todo Mainpark Shocked1 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","01","02","mainpark","",0,"","true",800,950))
image todo Mainpark Shocked1 Flip= Transform("todo Mainpark Shocked1",xzoom=-1.0)
image todo Mainpark Shocked1 Fade Flip= Transform("todo Mainpark Shocked1 Fade",xzoom=-1.0)
image todo Mainpark Shocked2 = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","03","04","mainpark","",0,"","false",800,950))
image todo Mainpark Shocked2 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","03","04","mainpark","",0,"","true",800,950))
image todo Mainpark Shocked2 Flip= Transform("todo Mainpark Shocked2",xzoom=-1.0)
image todo Mainpark Shocked2 Fade Flip= Transform("todo Mainpark Shocked2 Fade",xzoom=-1.0)
image todo Mainpark Surprised = DynamicDisplayable(renpy.curry(charComposite)("todo","surprised","01","02","mainpark","",0,"","false",800,950))
image todo Mainpark Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","surprised","01","02","mainpark","",0,"","true",800,950))
image todo Mainpark Surprised Flip= Transform("todo Mainpark Surprised",xzoom=-1.0)
image todo Mainpark Surprised Fade Flip= Transform("todo Mainpark Surprised Fade",xzoom=-1.0)
image todo Mainpark Thinking = DynamicDisplayable(renpy.curry(charComposite)("todo","thinking","01","02","mainpark","",0,"","false",800,950))
image todo Mainpark Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","thinking","01","02","mainpark","",0,"","true",800,950))
image todo Mainpark Thinking Flip= Transform("todo Mainpark Thinking",xzoom=-1.0)
image todo Mainpark Thinking Fade Flip= Transform("todo Mainpark Thinking Fade",xzoom=-1.0)
image todo Maintee Angry = DynamicDisplayable(renpy.curry(charComposite)("todo","angry","01","02","maintee","",0,"","false",800,950))
image todo Maintee Angry Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","angry","01","02","maintee","",0,"","true",800,950))
image todo Maintee Angry Flip= Transform("todo Maintee Angry",xzoom=-1.0)
image todo Maintee Angry Fade Flip= Transform("todo Maintee Angry Fade",xzoom=-1.0)
image todo Maintee Dark = DynamicDisplayable(renpy.curry(charComposite)("todo","dark","","","maintee","",0,"","false",800,950))
image todo Maintee Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","dark","","","maintee","",0,"","true",800,950))
image todo Maintee Dark Flip= Transform("todo Maintee Dark",xzoom=-1.0)
image todo Maintee Dark Fade Flip= Transform("todo Maintee Dark Fade",xzoom=-1.0)
image todo Maintee Blank = DynamicDisplayable(renpy.curry(charComposite)("todo","blank","01","02","maintee","",0,"","false",800,950))
image todo Maintee Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","blank","01","02","maintee","",0,"","true",800,950))
image todo Maintee Blank Flip= Transform("todo Maintee Blank",xzoom=-1.0)
image todo Maintee Blank Fade Flip= Transform("todo Maintee Blank Fade",xzoom=-1.0)
image todo Maintee Displeased = DynamicDisplayable(renpy.curry(charComposite)("todo","displeased","01","02","maintee","",0,"","false",800,950))
image todo Maintee Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","displeased","01","02","maintee","",0,"","true",800,950))
image todo Maintee Displeased Flip= Transform("todo Maintee Displeased",xzoom=-1.0)
image todo Maintee Displeased Fade Flip= Transform("todo Maintee Displeased Fade",xzoom=-1.0)
image todo Maintee Happy1 = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","01","01","maintee","",0,"","false",800,950))
image todo Maintee Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","01","01","maintee","",0,"","true",800,950))
image todo Maintee Happy1 Flip= Transform("todo Maintee Happy1",xzoom=-1.0)
image todo Maintee Happy1 Fade Flip= Transform("todo Maintee Happy1 Fade",xzoom=-1.0)
image todo Maintee Happy2 = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","02","02","maintee","",0,"","false",800,950))
image todo Maintee Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","02","02","maintee","",0,"","true",800,950))
image todo Maintee Happy2 Flip= Transform("todo Maintee Happy2",xzoom=-1.0)
image todo Maintee Happy2 Fade Flip= Transform("todo Maintee Happy2 Fade",xzoom=-1.0)
image todo Maintee Nervous = DynamicDisplayable(renpy.curry(charComposite)("todo","nervous","01","02","maintee","",0,"","false",800,950))
image todo Maintee Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","nervous","01","02","maintee","",0,"","true",800,950))
image todo Maintee Nervous Flip= Transform("todo Maintee Nervous",xzoom=-1.0)
image todo Maintee Nervous Fade Flip= Transform("todo Maintee Nervous Fade",xzoom=-1.0)
image todo Maintee Neutral = DynamicDisplayable(renpy.curry(charComposite)("todo","neutral","01","02","maintee","",0,"","false",800,950))
image todo Maintee Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","neutral","01","02","maintee","",0,"","true",800,950))
image todo Maintee Neutral Flip= Transform("todo Maintee Neutral",xzoom=-1.0)
image todo Maintee Neutral Fade Flip= Transform("todo Maintee Neutral Fade",xzoom=-1.0)
image todo Maintee Shocked1 = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","01","02","maintee","",0,"","false",800,950))
image todo Maintee Shocked1 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","01","02","maintee","",0,"","true",800,950))
image todo Maintee Shocked1 Flip= Transform("todo Maintee Shocked1",xzoom=-1.0)
image todo Maintee Shocked1 Fade Flip= Transform("todo Maintee Shocked1 Fade",xzoom=-1.0)
image todo Maintee Shocked2 = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","03","04","maintee","",0,"","false",800,950))
image todo Maintee Shocked2 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","03","04","maintee","",0,"","true",800,950))
image todo Maintee Shocked2 Flip= Transform("todo Maintee Shocked2",xzoom=-1.0)
image todo Maintee Shocked2 Fade Flip= Transform("todo Maintee Shocked2 Fade",xzoom=-1.0)
image todo Maintee Surprised = DynamicDisplayable(renpy.curry(charComposite)("todo","surprised","01","02","maintee","",0,"","false",800,950))
image todo Maintee Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","surprised","01","02","maintee","",0,"","true",800,950))
image todo Maintee Surprised Flip= Transform("todo Maintee Surprised",xzoom=-1.0)
image todo Maintee Surprised Fade Flip= Transform("todo Maintee Surprised Fade",xzoom=-1.0)
image todo Maintee Thinking = DynamicDisplayable(renpy.curry(charComposite)("todo","thinking","01","02","maintee","",0,"","false",800,950))
image todo Maintee Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","thinking","01","02","maintee","",0,"","true",800,950))
image todo Maintee Thinking Flip= Transform("todo Maintee Thinking",xzoom=-1.0)
image todo Maintee Thinking Fade Flip= Transform("todo Maintee Thinking Fade",xzoom=-1.0)
image todo PJ Angry = DynamicDisplayable(renpy.curry(charComposite)("todo","angry","01","02","pj","",0,"","false",800,950))
image todo PJ Angry Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","angry","01","02","pj","",0,"","true",800,950))
image todo PJ Angry Flip= Transform("todo PJ Angry",xzoom=-1.0)
image todo PJ Angry Fade Flip= Transform("todo PJ Angry Fade",xzoom=-1.0)
image todo PJ Dark = DynamicDisplayable(renpy.curry(charComposite)("todo","dark","","","pj","",0,"","false",800,950))
image todo PJ Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","dark","","","pj","",0,"","true",800,950))
image todo PJ Dark Flip= Transform("todo PJ Dark",xzoom=-1.0)
image todo PJ Dark Fade Flip= Transform("todo PJ Dark Fade",xzoom=-1.0)
image todo PJ Blank = DynamicDisplayable(renpy.curry(charComposite)("todo","blank","01","02","pj","",0,"","false",800,950))
image todo PJ Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","blank","01","02","pj","",0,"","true",800,950))
image todo PJ Blank Flip= Transform("todo PJ Blank",xzoom=-1.0)
image todo PJ Blank Fade Flip= Transform("todo PJ Blank Fade",xzoom=-1.0)
image todo PJ Displeased = DynamicDisplayable(renpy.curry(charComposite)("todo","displeased","01","02","pj","",0,"","false",800,950))
image todo PJ Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","displeased","01","02","pj","",0,"","true",800,950))
image todo PJ Displeased Flip= Transform("todo PJ Displeased",xzoom=-1.0)
image todo PJ Displeased Fade Flip= Transform("todo PJ Displeased Fade",xzoom=-1.0)
image todo PJ Happy1 = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","01","01","pj","",0,"","false",800,950))
image todo PJ Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","01","01","pj","",0,"","true",800,950))
image todo PJ Happy1 Flip= Transform("todo PJ Happy1",xzoom=-1.0)
image todo PJ Happy1 Fade Flip= Transform("todo PJ Happy1 Fade",xzoom=-1.0)
image todo PJ Happy2 = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","02","02","pj","",0,"","false",800,950))
image todo PJ Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","02","02","pj","",0,"","true",800,950))
image todo PJ Happy2 Flip= Transform("todo PJ Happy2",xzoom=-1.0)
image todo PJ Happy2 Fade Flip= Transform("todo PJ Happy2 Fade",xzoom=-1.0)
image todo PJ Nervous = DynamicDisplayable(renpy.curry(charComposite)("todo","nervous","01","02","pj","",0,"","false",800,950))
image todo PJ Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","nervous","01","02","pj","",0,"","true",800,950))
image todo PJ Nervous Flip= Transform("todo PJ Nervous",xzoom=-1.0)
image todo PJ Nervous Fade Flip= Transform("todo PJ Nervous Fade",xzoom=-1.0)
image todo PJ Neutral = DynamicDisplayable(renpy.curry(charComposite)("todo","neutral","01","02","pj","",0,"","false",800,950))
image todo PJ Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","neutral","01","02","pj","",0,"","true",800,950))
image todo PJ Neutral Flip= Transform("todo PJ Neutral",xzoom=-1.0)
image todo PJ Neutral Fade Flip= Transform("todo PJ Neutral Fade",xzoom=-1.0)
image todo PJ Shocked1 = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","01","02","pj","",0,"","false",800,950))
image todo PJ Shocked1 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","01","02","pj","",0,"","true",800,950))
image todo PJ Shocked1 Flip= Transform("todo PJ Shocked1",xzoom=-1.0)
image todo PJ Shocked1 Fade Flip= Transform("todo PJ Shocked1 Fade",xzoom=-1.0)
image todo PJ Shocked2 = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","03","04","pj","",0,"","false",800,950))
image todo PJ Shocked2 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","03","04","pj","",0,"","true",800,950))
image todo PJ Shocked2 Flip= Transform("todo PJ Shocked2",xzoom=-1.0)
image todo PJ Shocked2 Fade Flip= Transform("todo PJ Shocked2 Fade",xzoom=-1.0)
image todo PJ Surprised = DynamicDisplayable(renpy.curry(charComposite)("todo","surprised","01","02","pj","",0,"","false",800,950))
image todo PJ Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","surprised","01","02","pj","",0,"","true",800,950))
image todo PJ Surprised Flip= Transform("todo PJ Surprised",xzoom=-1.0)
image todo PJ Surprised Fade Flip= Transform("todo PJ Surprised Fade",xzoom=-1.0)
image todo PJ Thinking = DynamicDisplayable(renpy.curry(charComposite)("todo","thinking","01","02","pj","",0,"","false",800,950))
image todo PJ Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","thinking","01","02","pj","",0,"","true",800,950))
image todo PJ Thinking Flip= Transform("todo PJ Thinking",xzoom=-1.0)
image todo PJ Thinking Fade Flip= Transform("todo PJ Thinking Fade",xzoom=-1.0)
image todo SchoolS Angry = DynamicDisplayable(renpy.curry(charComposite)("todo","angry","01","02","schools","",0,"","false",800,950))
image todo SchoolS Angry Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","angry","01","02","schools","",0,"","true",800,950))
image todo SchoolS Angry Flip= Transform("todo SchoolS Angry",xzoom=-1.0)
image todo SchoolS Angry Fade Flip= Transform("todo SchoolS Angry Fade",xzoom=-1.0)
image todo SchoolS Dark = DynamicDisplayable(renpy.curry(charComposite)("todo","dark","","","schools","",0,"","false",800,950))
image todo SchoolS Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","dark","","","schools","",0,"","true",800,950))
image todo SchoolS Dark Flip= Transform("todo SchoolS Dark",xzoom=-1.0)
image todo SchoolS Dark Fade Flip= Transform("todo SchoolS Dark Fade",xzoom=-1.0)
image todo SchoolS Blank = DynamicDisplayable(renpy.curry(charComposite)("todo","blank","01","02","schools","",0,"","false",800,950))
image todo SchoolS Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","blank","01","02","schools","",0,"","true",800,950))
image todo SchoolS Blank Flip= Transform("todo SchoolS Blank",xzoom=-1.0)
image todo SchoolS Blank Fade Flip= Transform("todo SchoolS Blank Fade",xzoom=-1.0)
image todo SchoolS Displeased = DynamicDisplayable(renpy.curry(charComposite)("todo","displeased","01","02","schools","",0,"","false",800,950))
image todo SchoolS Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","displeased","01","02","schools","",0,"","true",800,950))
image todo SchoolS Displeased Flip= Transform("todo SchoolS Displeased",xzoom=-1.0)
image todo SchoolS Displeased Fade Flip= Transform("todo SchoolS Displeased Fade",xzoom=-1.0)
image todo SchoolS Happy1 = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","01","01","schools","",0,"","false",800,950))
image todo SchoolS Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","01","01","schools","",0,"","true",800,950))
image todo SchoolS Happy1 Flip= Transform("todo SchoolS Happy1",xzoom=-1.0)
image todo SchoolS Happy1 Fade Flip= Transform("todo SchoolS Happy1 Fade",xzoom=-1.0)
image todo SchoolS Happy2 = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","02","02","schools","",0,"","false",800,950))
image todo SchoolS Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","02","02","schools","",0,"","true",800,950))
image todo SchoolS Happy2 Flip= Transform("todo SchoolS Happy2",xzoom=-1.0)
image todo SchoolS Happy2 Fade Flip= Transform("todo SchoolS Happy2 Fade",xzoom=-1.0)
image todo SchoolS Nervous = DynamicDisplayable(renpy.curry(charComposite)("todo","nervous","01","02","schools","",0,"","false",800,950))
image todo SchoolS Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","nervous","01","02","schools","",0,"","true",800,950))
image todo SchoolS Nervous Flip= Transform("todo SchoolS Nervous",xzoom=-1.0)
image todo SchoolS Nervous Fade Flip= Transform("todo SchoolS Nervous Fade",xzoom=-1.0)
image todo SchoolS Neutral = DynamicDisplayable(renpy.curry(charComposite)("todo","neutral","01","02","schools","",0,"","false",800,950))
image todo SchoolS Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","neutral","01","02","schools","",0,"","true",800,950))
image todo SchoolS Neutral Flip= Transform("todo SchoolS Neutral",xzoom=-1.0)
image todo SchoolS Neutral Fade Flip= Transform("todo SchoolS Neutral Fade",xzoom=-1.0)
image todo SchoolS Shocked1 = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","01","02","schools","",0,"","false",800,950))
image todo SchoolS Shocked1 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","01","02","schools","",0,"","true",800,950))
image todo SchoolS Shocked1 Flip= Transform("todo SchoolS Shocked1",xzoom=-1.0)
image todo SchoolS Shocked1 Fade Flip= Transform("todo SchoolS Shocked1 Fade",xzoom=-1.0)
image todo SchoolS Shocked2 = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","03","04","schools","",0,"","false",800,950))
image todo SchoolS Shocked2 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","03","04","schools","",0,"","true",800,950))
image todo SchoolS Shocked2 Flip= Transform("todo SchoolS Shocked2",xzoom=-1.0)
image todo SchoolS Shocked2 Fade Flip= Transform("todo SchoolS Shocked2 Fade",xzoom=-1.0)
image todo SchoolS Surprised = DynamicDisplayable(renpy.curry(charComposite)("todo","surprised","01","02","schools","",0,"","false",800,950))
image todo SchoolS Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","surprised","01","02","schools","",0,"","true",800,950))
image todo SchoolS Surprised Flip= Transform("todo SchoolS Surprised",xzoom=-1.0)
image todo SchoolS Surprised Fade Flip= Transform("todo SchoolS Surprised Fade",xzoom=-1.0)
image todo SchoolS Thinking = DynamicDisplayable(renpy.curry(charComposite)("todo","thinking","01","02","schools","",0,"","false",800,950))
image todo SchoolS Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","thinking","01","02","schools","",0,"","true",800,950))
image todo SchoolS Thinking Flip= Transform("todo SchoolS Thinking",xzoom=-1.0)
image todo SchoolS Thinking Fade Flip= Transform("todo SchoolS Thinking Fade",xzoom=-1.0)
image todo SchoolW Angry = DynamicDisplayable(renpy.curry(charComposite)("todo","angry","01","02","schoolw","",0,"","false",800,950))
image todo SchoolW Angry Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","angry","01","02","schoolw","",0,"","true",800,950))
image todo SchoolW Angry Flip= Transform("todo SchoolW Angry",xzoom=-1.0)
image todo SchoolW Angry Fade Flip= Transform("todo SchoolW Angry Fade",xzoom=-1.0)
image todo SchoolW Dark = DynamicDisplayable(renpy.curry(charComposite)("todo","dark","","","schoolw","",0,"","false",800,950))
image todo SchoolW Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","dark","","","schoolw","",0,"","true",800,950))
image todo SchoolW Dark Flip= Transform("todo SchoolW Dark",xzoom=-1.0)
image todo SchoolW Dark Fade Flip= Transform("todo SchoolW Dark Fade",xzoom=-1.0)
image todo SchoolW Blank = DynamicDisplayable(renpy.curry(charComposite)("todo","blank","01","02","schoolw","",0,"","false",800,950))
image todo SchoolW Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","blank","01","02","schoolw","",0,"","true",800,950))
image todo SchoolW Blank Flip= Transform("todo SchoolW Blank",xzoom=-1.0)
image todo SchoolW Blank Fade Flip= Transform("todo SchoolW Blank Fade",xzoom=-1.0)
image todo SchoolW Displeased = DynamicDisplayable(renpy.curry(charComposite)("todo","displeased","01","02","schoolw","",0,"","false",800,950))
image todo SchoolW Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","displeased","01","02","schoolw","",0,"","true",800,950))
image todo SchoolW Displeased Flip= Transform("todo SchoolW Displeased",xzoom=-1.0)
image todo SchoolW Displeased Fade Flip= Transform("todo SchoolW Displeased Fade",xzoom=-1.0)
image todo SchoolW Happy1 = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","01","01","schoolw","",0,"","false",800,950))
image todo SchoolW Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","01","01","schoolw","",0,"","true",800,950))
image todo SchoolW Happy1 Flip= Transform("todo SchoolW Happy1",xzoom=-1.0)
image todo SchoolW Happy1 Fade Flip= Transform("todo SchoolW Happy1 Fade",xzoom=-1.0)
image todo SchoolW Happy2 = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","02","02","schoolw","",0,"","false",800,950))
image todo SchoolW Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","02","02","schoolw","",0,"","true",800,950))
image todo SchoolW Happy2 Flip= Transform("todo SchoolW Happy2",xzoom=-1.0)
image todo SchoolW Happy2 Fade Flip= Transform("todo SchoolW Happy2 Fade",xzoom=-1.0)
image todo SchoolW Nervous = DynamicDisplayable(renpy.curry(charComposite)("todo","nervous","01","02","schoolw","",0,"","false",800,950))
image todo SchoolW Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","nervous","01","02","schoolw","",0,"","true",800,950))
image todo SchoolW Nervous Flip= Transform("todo SchoolW Nervous",xzoom=-1.0)
image todo SchoolW Nervous Fade Flip= Transform("todo SchoolW Nervous Fade",xzoom=-1.0)
image todo SchoolW Neutral = DynamicDisplayable(renpy.curry(charComposite)("todo","neutral","01","02","schoolw","",0,"","false",800,950))
image todo SchoolW Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","neutral","01","02","schoolw","",0,"","true",800,950))
image todo SchoolW Neutral Flip= Transform("todo SchoolW Neutral",xzoom=-1.0)
image todo SchoolW Neutral Fade Flip= Transform("todo SchoolW Neutral Fade",xzoom=-1.0)
image todo SchoolW Shocked1 = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","01","02","schoolw","",0,"","false",800,950))
image todo SchoolW Shocked1 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","01","02","schoolw","",0,"","true",800,950))
image todo SchoolW Shocked1 Flip= Transform("todo SchoolW Shocked1",xzoom=-1.0)
image todo SchoolW Shocked1 Fade Flip= Transform("todo SchoolW Shocked1 Fade",xzoom=-1.0)
image todo SchoolW Shocked2 = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","03","04","schoolw","",0,"","false",800,950))
image todo SchoolW Shocked2 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","03","04","schoolw","",0,"","true",800,950))
image todo SchoolW Shocked2 Flip= Transform("todo SchoolW Shocked2",xzoom=-1.0)
image todo SchoolW Shocked2 Fade Flip= Transform("todo SchoolW Shocked2 Fade",xzoom=-1.0)
image todo SchoolW Surprised = DynamicDisplayable(renpy.curry(charComposite)("todo","surprised","01","02","schoolw","",0,"","false",800,950))
image todo SchoolW Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","surprised","01","02","schoolw","",0,"","true",800,950))
image todo SchoolW Surprised Flip= Transform("todo SchoolW Surprised",xzoom=-1.0)
image todo SchoolW Surprised Fade Flip= Transform("todo SchoolW Surprised Fade",xzoom=-1.0)
image todo SchoolW Thinking = DynamicDisplayable(renpy.curry(charComposite)("todo","thinking","01","02","schoolw","",0,"","false",800,950))
image todo SchoolW Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","thinking","01","02","schoolw","",0,"","true",800,950))
image todo SchoolW Thinking Flip= Transform("todo SchoolW Thinking",xzoom=-1.0)
image todo SchoolW Thinking Fade Flip= Transform("todo SchoolW Thinking Fade",xzoom=-1.0)
image todo Naked Angry = DynamicDisplayable(renpy.curry(charComposite)("todo","angry","01","02","naked","",0,"","false",800,950))
image todo Naked Angry Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","angry","01","02","naked","",0,"","true",800,950))
image todo Naked Angry Flip= Transform("todo Naked Angry",xzoom=-1.0)
image todo Naked Angry Fade Flip= Transform("todo Naked Angry Fade",xzoom=-1.0)
image todo Naked Dark = DynamicDisplayable(renpy.curry(charComposite)("todo","dark","","","naked","",0,"","false",800,950))
image todo Naked Dark Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","dark","","","naked","",0,"","true",800,950))
image todo Naked Dark Flip= Transform("todo Naked Dark",xzoom=-1.0)
image todo Naked Dark Fade Flip= Transform("todo Naked Dark Fade",xzoom=-1.0)
image todo Naked Blank = DynamicDisplayable(renpy.curry(charComposite)("todo","blank","01","02","naked","",0,"","false",800,950))
image todo Naked Blank Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","blank","01","02","naked","",0,"","true",800,950))
image todo Naked Blank Flip= Transform("todo Naked Blank",xzoom=-1.0)
image todo Naked Blank Fade Flip= Transform("todo Naked Blank Fade",xzoom=-1.0)
image todo Naked Displeased = DynamicDisplayable(renpy.curry(charComposite)("todo","displeased","01","02","naked","",0,"","false",800,950))
image todo Naked Displeased Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","displeased","01","02","naked","",0,"","true",800,950))
image todo Naked Displeased Flip= Transform("todo Naked Displeased",xzoom=-1.0)
image todo Naked Displeased Fade Flip= Transform("todo Naked Displeased Fade",xzoom=-1.0)
image todo Naked Happy1 = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","01","01","naked","",0,"","false",800,950))
image todo Naked Happy1 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","01","01","naked","",0,"","true",800,950))
image todo Naked Happy1 Flip= Transform("todo Naked Happy1",xzoom=-1.0)
image todo Naked Happy1 Fade Flip= Transform("todo Naked Happy1 Fade",xzoom=-1.0)
image todo Naked Happy2 = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","02","02","naked","",0,"","false",800,950))
image todo Naked Happy2 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","happy","02","02","naked","",0,"","true",800,950))
image todo Naked Happy2 Flip= Transform("todo Naked Happy2",xzoom=-1.0)
image todo Naked Happy2 Fade Flip= Transform("todo Naked Happy2 Fade",xzoom=-1.0)
image todo Naked Nervous = DynamicDisplayable(renpy.curry(charComposite)("todo","nervous","01","02","naked","",0,"","false",800,950))
image todo Naked Nervous Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","nervous","01","02","naked","",0,"","true",800,950))
image todo Naked Nervous Flip= Transform("todo Naked Nervous",xzoom=-1.0)
image todo Naked Nervous Fade Flip= Transform("todo Naked Nervous Fade",xzoom=-1.0)
image todo Naked Neutral = DynamicDisplayable(renpy.curry(charComposite)("todo","neutral","01","02","naked","",0,"","false",800,950))
image todo Naked Neutral Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","neutral","01","02","naked","",0,"","true",800,950))
image todo Naked Neutral Flip= Transform("todo Naked Neutral",xzoom=-1.0)
image todo Naked Neutral Fade Flip= Transform("todo Naked Neutral Fade",xzoom=-1.0)
image todo Naked Shocked1 = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","01","02","naked","",0,"","false",800,950))
image todo Naked Shocked1 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","01","02","naked","",0,"","true",800,950))
image todo Naked Shocked1 Flip= Transform("todo Naked Shocked1",xzoom=-1.0)
image todo Naked Shocked1 Fade Flip= Transform("todo Naked Shocked1 Fade",xzoom=-1.0)
image todo Naked Shocked2 = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","03","04","naked","",0,"","false",800,950))
image todo Naked Shocked2 Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","shocked","03","04","naked","",0,"","true",800,950))
image todo Naked Shocked2 Flip= Transform("todo Naked Shocked2",xzoom=-1.0)
image todo Naked Shocked2 Fade Flip= Transform("todo Naked Shocked2 Fade",xzoom=-1.0)
image todo Naked Surprised = DynamicDisplayable(renpy.curry(charComposite)("todo","surprised","01","02","naked","",0,"","false",800,950))
image todo Naked Surprised Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","surprised","01","02","naked","",0,"","true",800,950))
image todo Naked Surprised Flip= Transform("todo Naked Surprised",xzoom=-1.0)
image todo Naked Surprised Fade Flip= Transform("todo Naked Surprised Fade",xzoom=-1.0)
image todo Naked Thinking = DynamicDisplayable(renpy.curry(charComposite)("todo","thinking","01","02","naked","",0,"","false",800,950))
image todo Naked Thinking Fade = DynamicDisplayable(renpy.curry(charComposite)("todo","thinking","01","02","naked","",0,"","true",800,950))
image todo Naked Thinking Flip= Transform("todo Naked Thinking",xzoom=-1.0)
image todo Naked Thinking Fade Flip= Transform("todo Naked Thinking Fade",xzoom=-1.0)
